-- Liquidity Hunter HQ — Supabase Schema
-- Run this in your Supabase SQL Editor once.
-- No auth: this is a private personal tool.

-- ─────────────────────────────────────────
-- Clusters table
-- ─────────────────────────────────────────
create table if not exists clusters (
  id         bigint generated by default as identity primary key,
  coin       text        not null,
  level      numeric     not null,
  side       text        not null check (side in ('above', 'below')),
  note       text,
  status     text        not null default 'pending' check (status in ('pending', 'raided', 'expired')),
  added_at   timestamptz not null default now(),
  raided_at  timestamptz
);

-- ─────────────────────────────────────────
-- Signals table (AI Arena history)
-- ─────────────────────────────────────────
create table if not exists signals (
  id          bigint generated by default as identity primary key,
  coin        text    not null,
  signal      text    not null check (signal in ('LONG', 'SHORT', 'FLAT')),
  confidence  int     not null,
  entry_zone  text,
  reasoning   text,
  session     text,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────
-- Row-level security
-- Disable RLS (private single-user tool — access via anon key from your device only)
-- ─────────────────────────────────────────
alter table clusters disable row level security;
alter table signals  disable row level security;

-- Optional: allow anon key full access (needed if RLS is ever re-enabled)
-- create policy "anon_all" on clusters for all to anon using (true) with check (true);
-- create policy "anon_all" on signals  for all to anon using (true) with check (true);
