export interface Secret {
  n: number;
  name: string;
  cat: 'hunt' | 'time' | 'trap' | 'psych';
  text: string;
}

export const SECRETS: Secret[] = [
  { n: 1, name: 'The only truth', cat: 'hunt', text: 'The market is not trying to go up or down. It is only trying to go where the stops are. Everything else is noise created to get price there.' },
  { n: 2, name: 'Liquidity is the only religion', cat: 'hunt', text: 'Big players find where the most money is vulnerable on the liquidation map, engineer the cheapest path to it, then take it. That is the entire game. No exceptions.' },
  { n: 3, name: 'Coinglass 24h Model 2 is your cheat code', cat: 'hunt', text: 'Bright yellow/white = high-density cluster. Price gets sent there on purpose. 24h Model 2 is what real hunters use. 1-week map is stale ancient history.' },
  { n: 4, name: 'Tightness beats dollar size', cat: 'hunt', text: 'A bright $80M cluster in a 1-2% range hits harder than a dark $400M cluster spread over 10%+. Density and brightness matter 10x more than dollar amount.' },
  { n: 5, name: 'The magnet effect', cat: 'hunt', text: 'Once price gets within 0.8% of a massive cluster it almost always gets sucked in. The closer it gets, the harder it accelerates. That final sprint is the fastest part of the whole raid.' },
  { n: 6, name: 'The 2.5% rule', cat: 'hunt', text: 'Price moves more than 2.5% in under 30 minutes with almost no pullback = 90% a liquidity raid, not a real trend. Real moves breathe and pull back. Raids rip straight through.' },
  { n: 7, name: 'Double cluster rule', cat: 'hunt', text: 'Strongest moves happen when two big liquidity pools are stacked close together. Price sweeps both in one violent move — first one side, immediately the other. Highest probability setup.' },
  { n: 8, name: 'The 3-touch rule', cat: 'hunt', text: 'Any pool that gets swept and fails to reverse strongly will get raided again within 48 hours. First touch = warning. Second = setup. Third = slaughter.' },
  { n: 9, name: 'Equal and opposite', cat: 'hunt', text: 'For every raid up there is almost always an equal-sized raid down within 48-72 hours. They rarely leave one side of the book unbalanced. After the short squeeze, longs are next.' },
  { n: 10, name: 'Post-raid collapse', cat: 'hunt', text: 'The most violent moves die within 4-6 hours after the main liquidity is taken. Fuel is gone. Price goes flat or reverses hard. Do not hold after the touch.' },
  { n: 11, name: 'The iceberg', cat: 'hunt', text: 'Bright yellow on Coinglass is only 30-40% of actual liquidity. Real monster clusters are in private order books and OTC desks — invisible until they get hit.' },
  { n: 12, name: 'The nuclear setup', cat: 'hunt', text: 'Highest edge of all: massive bright cluster + extremely high funding rate + price crabbing for 48+ hours. When all three align at once, 10%+ moves happen in hours. Bet big on this.' },
  { n: 13, name: 'Funding rate divergence', cat: 'hunt', text: 'Extremely high positive funding (longs paying) but price keeps pumping = classic sign a short squeeze is being manufactured. They are using the longs own greed against them.' },
  { n: 14, name: 'Exhaustion spike signal', cat: 'hunt', text: 'When funding goes parabolic while price is raiding a zone, that is the top of the squeeze. The moment funding hits extreme levels during the raid — look for your exit immediately.' },
  { n: 15, name: 'The 90-minute rule', cat: 'time', text: 'After any major raid: first 30 minutes = chaos and fake moves. Next 60 minutes = real directional move emerges. Most people trade the first 30 and get wrecked every time.' },
  { n: 16, name: 'Sunday night is hunting season', cat: 'time', text: 'Sunday 11PM – Monday 3AM PHT (Monday 00:30–02:30 UTC). Lowest volume of the entire week. Retail asleep. Easiest time to move price with minimum capital.' },
  { n: 17, name: 'The 4:45AM PHT rule', cat: 'time', text: '4:00–4:45 AM PHT is the single most consistent reversal window. More violent reversals happen here than any other time of day. Watch this window every single night.' },
  { n: 18, name: 'Dead quiet = storm coming', cat: 'time', text: 'The most boring flat 4H period almost always precedes a violent raid. When Twitter is silent and volume is near zero — that is when they are loading positions. Stay alert.' },
  { n: 19, name: 'London open fake (9:30AM UTC)', cat: 'time', text: 'Every day around 5:30-6PM PHT there is almost always a fake move first. They shake out early positions before the real daily direction shows up. Never enter on the first move.' },
  { n: 20, name: '48-hour coil rule', cat: 'time', text: 'Bitcoin stuck in a tight range for 48+ hours = probability of violent raid goes through the roof. The longer the range, the bigger the spring that gets released.' },
  { n: 21, name: 'Bait candle', cat: 'trap', text: 'They create one extremely clean beautiful candle on the 15min or 1H chart to make retail think this is the real move. Once retail FOMOs in, the reversal comes. That clean candle is pure bait.' },
  { n: 22, name: 'Stop sweep — they hunt in pairs', cat: 'trap', text: 'Massive wick up takes out the shorts first. Then immediately a wick down takes out the new longs who just bought the breakout. Two hunts, one move. Called a stop sweep.' },
  { n: 23, name: 'The head fake', cat: 'trap', text: 'Price breaks a level cleanly, retail piles in, then within 20-40 minutes reverses violently. The cleaner the breakout looks, the faster the reversal comes.' },
  { n: 24, name: 'Silence before the scream', cat: 'trap', text: 'The 10-15 minutes right before a major raid, order flow goes completely dead. Spread tightens, volume drops to almost nothing. That silence is the biggest tell. Get ready to enter.' },
  { n: 25, name: 'Never trust the first move after news', cat: 'trap', text: 'The first 30-45 minutes after big news is almost always the fake move designed to trap retail. The real directional move comes on the second leg.' },
  { n: 26, name: 'They fade the news not follow it', cat: 'trap', text: 'Good news = short squeeze first, then dump. Bad news = long squeeze first, then pump. The sharper the headline, the more likely they do the exact opposite of what retail expects.' },
  { n: 27, name: 'The ghost cluster', cat: 'trap', text: 'A bright zone disappears from heatmap while price is still 1% away = big players already swept it OTC in the dark. When you see a zone vanish before price reaches it, exit immediately.' },
  { n: 28, name: 'The reversal fake', cat: 'trap', text: 'Right after raiding a major pool they do one clean strong candle in the same direction to trap late FOMO traders, then immediately reverse. That final clean candle is the last trap.' },
  { n: 29, name: 'The silent killer', cat: 'trap', text: 'Most dangerous raid has zero big candles. Price slowly grinds into the zone on tiny 0.2% candles for 4-6 hours. Retail gets bored and closes positions early, then it explodes.' },
  { n: 30, name: 'The previous day high/low trap', cat: 'trap', text: 'Strongest fakeouts happen exactly at the previous day high or low. That is where the most amateur stops are placed. They hit those levels with surgical precision every time.' },
  { n: 31, name: 'TA is the target not the map', cat: 'psych', text: 'Whales look at TA charts to see exactly where retail has stacked their stops. The more obvious the chart pattern, the more likely it is a trap. They weaponize your own analysis against you.' },
  { n: 32, name: 'They hunt the winners too', cat: 'psych', text: 'Most dangerous time to be long is right after a massive short squeeze. They slaughter the shorts, let the longs feel like geniuses, then slaughter those same longs. They hunt the confident.' },
  { n: 33, name: 'News is the cleanup crew', cat: 'psych', text: 'They decide where to raid liquidity first, push price there, then the news appears to justify the move. They move first. News comes after as the story retail tells themselves about why it happened.' },
  { n: 34, name: 'YouTube lines are kill targets', cat: 'psych', text: 'When thousands of analysts draw the same line at a level and scream breakout, whales see that too. They know exactly where the crowd is gathering and they treat it as a feeding frenzy.' },
  { n: 35, name: 'Crowd consensus = trade against it', cat: 'psych', text: 'When everyone on Twitter and Reddit is extremely bullish or bearish at the same time, the big players do the exact opposite on purpose. Maximum retail consensus = maximum danger.' },
  { n: 36, name: 'DCA buyers are the most consistent food', cat: 'psych', text: 'DCA buyers are the easiest to eat. They buy predictable levels every month. Whales see those levels clearly, dump into them, shake them out, buy back cheaper. They think they are safe.' },
  { n: 37, name: '200-300 players run the whole game', cat: 'psych', text: 'Maybe 200-300 real players worldwide can actually move Bitcoin meaningfully. They do not need to coordinate. They all pay for the same order flow data so they all hunt the same zones at the same time.' },
  { n: 38, name: 'Order flow data is sold by exchanges', cat: 'psych', text: 'Every major exchange sells real-time order flow data to big firms for millions per month. These firms see exactly where every stop-loss is at every price level. They do not guess. They have the full map.' },
  { n: 39, name: 'The real bosses stay flat 90% of the time', cat: 'psych', text: 'The absolute top players are flat 90% of the time. They only get in when the setup is perfect, take their 3-6%, then disappear. Patience is the real edge. Activity is for retail.' },
  { n: 40, name: 'No bull or bear market — only liquidity cycles', cat: 'psych', text: 'There are only periods when liquidity is stacked on one side and periods when it is stacked on the other. The moment one side is cleared, the hunt begins on the opposite side. That is the only cycle.' },
  { n: 41, name: 'The scar level', cat: 'hunt', text: 'Every major raid leaves a long wick scar on the chart. The next time price returns to that exact wick level it has very high probability of reversing again. Market memory is real and predictable.' },
  { n: 42, name: 'Front-run the raid by 0.5-1%', cat: 'hunt', text: 'Real predators do not enter at the liquidity zone. They enter 0.5-1% before it. They are already riding the wave before the cascade starts. Position early, not at the kill zone.' },
  { n: 43, name: 'The mirror raid', cat: 'hunt', text: 'They often run the exact same playbook in the opposite direction within 72 hours. Same wick, same speed, same fakeout. After hunting shorts, they come back to hunt the new longs.' },
  { n: 44, name: 'Never trust three in a row', cat: 'trap', text: 'After two big clusters get raided in the same direction the third almost always fails. They rarely hunt the same side three times consecutively. Direction flip is coming.' },
  { n: 45, name: 'The phantom move', cat: 'trap', text: 'Sometimes they push price slightly first to trigger small stops, use that created momentum to hunt the much bigger pool. They manufacture liquidity then use it as fuel to eat the real target.' },
  { n: 46, name: '4H is boss level', cat: 'time', text: 'The 4H wick is the real one. They raid higher timeframe liquidity first (4H and daily) then use that momentum to clean up lower timeframes. Everything below 4H is just cleanup.' },
  { n: 47, name: 'After a 3% rip with no pullback — get out', cat: 'hunt', text: 'Non-stop moves over 3% are raids, not trends. The moment a raid stops and the first red candle closes below the high of the touch candle, the reversal has begun. Exit on that candle.' },
  { n: 48, name: 'The fake volume trick', cat: 'trap', text: 'They create fake volume spikes between their own accounts to make retail think the move has real conviction. Real volume comes slow and steady. Fake volume comes in violent bursts then vanishes.' },
  { n: 49, name: 'No bright zone = they already ate it OTC', cat: 'hunt', text: 'When a massive liquidity zone gets completely ignored by price and no reaction happens, the big players already took that liquidity in the dark via OTC. The public chart becomes useless after that.' },
  { n: 50, name: 'The chart shows where the slaughter is scheduled', cat: 'psych', text: 'Technical analysis is not the direction. It is the target. Whales look at your lines, see where you put your stops, and drive price exactly there. The chart is a map of where retail will die next.' },
  { n: 51, name: 'The 3-layer filter — real vs fake liquidity', cat: 'hunt', text: 'Every cluster must pass 3 layers: (1) Bright AND tight within 1.5-2% range. (2) Fresh — appeared or brightened in the last 12-18 hours. (3) Price aggressively moving toward it. If even one layer fails, skip the trade. This is how you avoid ghost liquidity.' },
  { n: 52, name: 'Ghost liquidity — the invisible trap', cat: 'trap', text: 'Old clusters that have been sitting untouched for 2+ days are highly suspicious. The real liquidity may have already been taken in the dark via OTC. What you see on the heatmap could be a ghost — the map looks bright but the prey is already gone.' },
  { n: 53, name: 'The already-touched cluster trap', cat: 'trap', text: 'A very bright cluster that price has already touched once and reversed from has a high chance of being already cleaned. Do not trade a second touch expecting the same violent reaction. The fuel is gone — you are walking into an empty room.' },
  { n: 54, name: 'Sudden cluster with no volume = fake', cat: 'trap', text: 'A cluster that appears suddenly on the heatmap with no volume behind the move is manufactured. The big players are baiting you into thinking there is a raid target there. If volume does not confirm the cluster appearance, treat it as fake and ignore it.' },
  { n: 55, name: 'The golden confirmation — all 3 must align', cat: 'hunt', text: 'The best setups have all three at the same time: very bright, very tight range, and price sprinting toward it with increasing volume. If even one is missing the probability drops significantly. Wait for all three before pulling the trigger.' },
];

export function getDailySecret(): Secret {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  return SECRETS[seed % SECRETS.length];
}
