import { readFileSync } from 'fs';
import { join } from 'path';
import type { Page, Route } from '@playwright/test';

/* Controllable market data — the thing `qa/TEST_GAPS.md` §1 says the suite has
 * never had.
 *
 * Every test in this suite runs against whatever the live market is doing, so
 * the product's own domain logic has never been asserted against a KNOWN input.
 * A green run means "nothing crashed given today's prices".
 *
 * This intercepts at the THIRD-PARTY boundary where it can, because Binance and
 * Bybit publish their payload shapes and we do not change them. Our own `/api`
 * shapes are ours to refactor, and pinning tests to them would turn every
 * internal change into a test failure. `/api/funding` is stubbed as well because
 * it is served from a route handler — the browser never sees the upstream call,
 * so there is no third-party request to intercept for that one.
 *
 * Recorded from production 2026-08-08. See `qa/FIXTURES.md` for the full
 * endpoint enumeration and why only some are recorded so far.
 */

const DIR = join(process.cwd(), 'qa', 'fixtures');

/** Filename for a recorded `/api/*` response.
 *
 *  EXPORTED SO THE RECORDER AND THE SERVER SHARE ONE FUNCTION. Two copies of a
 *  key-derivation rule drift invisibly: the recorder writes `proxy-fng.json`,
 *  the installer looks up `fng.json`, every lookup misses, and the suite goes
 *  quietly back to live data with nothing red to show for it. That is the same
 *  failure `_design-tokens.ts` avoids by importing the palette instead of
 *  transcribing it, and it is the failure this whole file is being rewritten to
 *  fix — so it does not get to reappear in the fix.
 *
 *  `/api/proxy?type=fng` → `proxy-fng`; `/api/market/snapshot` →
 *  `market-snapshot`; `/api/cmc?type=global` → `cmc-global`. */
export function fixtureKey(u: URL): string {
  const path = u.pathname.replace(/^\/api\//, '').replace(/\/+$/, '').replace(/\//g, '-');
  const type = u.searchParams.get('type');
  return type ? `${path}-${type}` : path;
}

/* Two directories, and the split is meaningful rather than historical.
 *
 * `qa/fixtures/`       — recorded from production 2026-08-08, trimmed by hand.
 * `qa/fixtures/proxy/` — captured by `_record-proxy.spec.ts`, verbatim.
 *
 * The `proxy-` prefix is what separates them, so a name can only ever resolve to
 * one file; there is no precedence rule to get wrong because the two sets cannot
 * collide. Keeping them apart also keeps the provenance readable: anything under
 * `proxy/` can be regenerated by re-running the recorder, and anything above it
 * cannot. */
const RECORDED_DIR = join(DIR, 'proxy');

function load(name: string): { _url: string; _status: number; body: unknown } {
  const dir = name.startsWith('proxy-') ? RECORDED_DIR : DIR;
  return JSON.parse(readFileSync(join(dir, `${name}.json`), 'utf8'));
}

/** A scenario transforms a recorded payload into the market state under test. */
export type Scenario =
  | 'as-recorded' | 'funding-positive' | 'funding-negative' | 'upstream-500'
  /* Rewrites every coin's last price to a sentinel the live market cannot
   * produce. Exists ONLY so the price-pinning control can fail.
   *
   * The `as-recorded` fixture was captured from the live market on the day it
   * was recorded, so "the recorded BTC price is on screen" was ALSO true of a
   * completely unfixtured run that day — a control that could not fail yet, and
   * would only have become decisive once the market moved. That is a test which
   * has never been tested, dressed as a passing one. */
  | 'price-sentinel';

type FundingBody = { data: Array<{ coin: string; binance: number; bybit: number; nextFundingMs: number }>; ts: number };

/** Flip every funding rate negative, preserving magnitude and shape.
 *
 *  Magnitude is preserved deliberately: a scenario that also changes how LARGE
 *  the number is tests two things at once, and a failure would not say which. */
function fundingSigned(body: FundingBody, sign: -1 | 1): FundingBody {
  return {
    ...body,
    data: body.data.map(d => ({
      ...d,
      binance: sign * (Math.abs(d.binance) || 0.0001),
      bybit: sign * (Math.abs(d.bybit) || 0.0001),
    })),
  };
}

type BinanceFundingRow = { symbol: string; fundingTime: number; fundingRate: string; markPrice: string; rateType: string };
type PremiumIndexRow = { symbol: string; markPrice: string; lastFundingRate: string; nextFundingTime: number };

/* premiumIndex is what actually reaches the screen.
 *
 * Three controls proved it: transforming `/api/funding` changed nothing, and
 * even forcing every `fapi/v1/fundingRate` row positive left all 18 rendered
 * rates negative. This endpoint was the one skipped during recording because it
 * returns 857 symbols at 190KB - so the gap sat exactly where the shortcut was
 * taken. Trimmed to the 48 symbols the app displays: 10KB. */
function premiumIndexSigned(rows: PremiumIndexRow[], sign: -1 | 1): PremiumIndexRow[] {
  return rows.map(r => {
    const mag = Math.abs(parseFloat(r.lastFundingRate)) || 0.0001;
    return { ...r, lastFundingRate: (sign * mag).toFixed(8) };
  });
}

/** Binance's own funding history, negated.
 *
 *  This is the one that actually reaches the screen. `/api/funding` is a
 *  different surface, and transforming only that produced a `funding-negative`
 *  scenario where the rendered rates were unchanged — the test passed against
 *  the recorded payload's own mix of signs (9 of 42 rows are already negative)
 *  and proved nothing. Caught by a negative control, not by the test. */
function binanceFundingSigned(rows: BinanceFundingRow[], sign: -1 | 1): BinanceFundingRow[] {
  return rows.map(r => {
    const mag = Math.abs(parseFloat(r.fundingRate)) || 0.0001; // never 0: sign must be observable
    return { ...r, fundingRate: (sign * mag).toFixed(8) };
  });
}

type BybitFundingBody = { retCode: number; retMsg: string; result: { category: string; list: Array<{ symbol: string; fundingRate: string; fundingRateTimestamp: string }> } };

/* THE endpoint the /funding page actually renders. Found by tracing every
 * request the page makes and diffing against what was intercepted — after four
 * wrong guesses (`/api/funding`, `fapi/v1/fundingRate`, `premiumIndex`, and a
 * non-symmetric transform). `/api/funding` is not even requested by this page.
 *
 * The lesson is cheaper than the four attempts: when a controlled input does not
 * reach the screen, enumerate what the page requests. Do not reason about which
 * endpoint it "should" be. */
function bybitFundingSigned(body: BybitFundingBody, sign: -1 | 1): BybitFundingBody {
  return {
    ...body,
    result: {
      ...body.result,
      list: body.result.list.map(r => {
        const mag = Math.abs(parseFloat(r.fundingRate)) || 0.0001;
        return { ...r, fundingRate: (sign * mag).toFixed(8) };
      }),
    },
  };
}

type BybitTickersBody = { result: { list: Array<{ symbol: string; fundingRate: string }> } };

/* THE funding source. `components/MarketProvider.tsx` `fetchBybit()` calls this
 * endpoint and sets `fundingRate` from each ticker; `useMarket()` serves that to
 * /funding.
 *
 * Skipped during recording for size (805 symbols, 600KB). Trimmed to the 49 the
 * app uses it is 37KB - and the trim is complete: all 49 symbols `BYBIT_SYMS`
 * expects are present, none missing.
 *
 * Found by blocking all 200 intercepted requests and observing the page was
 * unchanged, which ruled out every intercepted route at once. Five prior guesses
 * at "which endpoint" each cost a run and proved nothing. */
function bybitTickersSigned(body: BybitTickersBody, sign: -1 | 1): BybitTickersBody {
  return {
    ...body,
    result: {
      ...body.result,
      list: body.result.list.map(r => {
        const mag = Math.abs(parseFloat(r.fundingRate)) || 0.0001;
        return { ...r, fundingRate: (sign * mag).toFixed(8) };
      }),
    },
  };
}

/** Serve recorded market data instead of the live market.
 *
 *  Returns `count` (routes fulfilled) and `byKey` (which ones), so a spec can
 *  FAIL when the endpoint UNDER TEST was not intercepted. `count > 0` alone is
 *  not enough: it was satisfied by an unrelated route while the values on screen
 *  still came from elsewhere. */
export async function installMarketFixtures(page: Page, scenario: Scenario = 'as-recorded') {
  const served: { count: number; byKey: Record<string, number> } = { count: 0, byKey: {} };

  const fulfil = async (route: Route, name: string, transform?: (b: unknown) => unknown) => {
    const fx = load(name);
    served.count++;
    served.byKey[name] = (served.byKey[name] ?? 0) + 1;
    if (scenario === 'upstream-500') {
      // Upstream failure is a first-class scenario: TEST_GAPS §1 notes the app's
      // behaviour when its data source fails has never been tested, and it is
      // the failure most likely to happen in public.
      return route.fulfill({ status: 500, contentType: 'application/json', body: '{"error":"upstream"}' });
    }
    const body = transform ? transform(fx.body) : fx.body;
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
  };

  /* CLOSE THE PRICE SOCKET. Without this line the function's name is a lie.
   *
   * `MarketProvider.tsx:90` fills `store.coins` from
   * `wss://stream.binance.com:9443/stream?streams=…`, and `page.route` cannot
   * see a WebSocket. So every run that called itself fixtured has been taking
   * LIVE prices — and everything derived from them — while controlling only the
   * secondary HTTP endpoints. Seven spec files, since this file was written.
   *
   * Closing it moves the app onto `restPoll()`, which IS interceptable and is
   * now served from `proxy-binance-24hr`. The app treats that as its documented
   * backup feed rather than as an error state, so this pins the data without
   * putting the page into a failure mode.
   *
   * `!forceOrder@arr` (line 1208) is the liquidation stream and is closed for
   * the same reason: unclosed, it keeps pushing live events into a run that
   * claims to be deterministic. */
  await page.routeWebSocket(/stream\.binance\.com|fstream\.binance\.com/, ws => ws.close());

  /** Implausible on purpose: no real BTC print rounds to this. */
  const SENTINEL_PRICE = '11111.11';

  const sign: -1 | 1 | null =
    scenario === 'funding-negative' ? -1 : scenario === 'funding-positive' ? 1 : null;

  await page.route('**/api/funding**', r =>
    fulfil(r, 'lhq-funding', sign ? (b) => fundingSigned(b as FundingBody, sign) : undefined));
  await page.route('**/api/market/rsi**', r => fulfil(r, 'lhq-market-rsi'));

  /* `/api/market/funding-rate` — the source /funding actually charts, and the
   * one this file missed entirely until 2026-08-11.
   *
   * `app/funding/page.tsx:40` fetches it on mount and charts the result. It was
   * invisible while the page ALSO called Bybit directly and that call dominated
   * what rendered; #242 moved the direct call behind the proxy, and the moment it
   * stopped competing, this route's LIVE data showed through untouched. The
   * `funding-negative` scenario then rendered 39 positive rates and said so.
   *
   * The header of this file says our own `/api` shapes are ours to refactor and
   * pinning to them turns internal changes into test failures. That still holds -
   * which is why this does NOT serve a recorded fixture. It fetches the real
   * response and negates every `fundingRate` in place, so the shape stays
   * whatever the route currently returns and cannot drift.
   *
   * Only intercepted when a sign scenario is active. `as-recorded` wants real
   * data and `upstream-500` is about third-party failure, not ours. */
  if (sign) {
    await page.route('**/api/market/funding-rate**', async (route) => {
      const res = await route.fetch();
      const json = await res.json() as { data?: Record<string, Array<{ fundingRate: string; fundingTime: number }>> };
      const data: Record<string, Array<{ fundingRate: string; fundingTime: number }>> = {};
      for (const [sym, rows] of Object.entries(json.data ?? {})) {
        data[sym] = rows.map(r => {
          const mag = Math.abs(parseFloat(r.fundingRate)) || 0.0001;  // never 0: the sign must be observable
          return { ...r, fundingRate: (sign * mag).toFixed(8) };
        });
      }
      served.count++;
      served.byKey['lhq-market-funding-rate'] = (served.byKey['lhq-market-funding-rate'] ?? 0) + 1;
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ ...json, data }) });
    });
  }
  await page.route('**/api/market/snapshot**', r => fulfil(r, 'lhq-market-snapshot'));
  await page.route('**fapi.binance.com/fapi/v1/fundingRate**', r =>
    fulfil(r, 'binance-fundingRate', sign ? (b) => binanceFundingSigned(b as BinanceFundingRow[], sign) : undefined));
  await page.route('**fapi.binance.com/fapi/v1/premiumIndex**', r =>
    fulfil(r, 'binance-premiumIndex', sign ? (b) => premiumIndexSigned(b as PremiumIndexRow[], sign) : undefined));
  await page.route('**api.bybit.com/v5/market/funding/history**', r =>
    fulfil(r, 'bybit-funding-history', sign ? (b) => bybitFundingSigned(b as BybitFundingBody, sign) : undefined));
  await page.route('**/v5/market/tickers**', r =>
    fulfil(r, 'bybit-tickers', sign ? (b) => bybitTickersSigned(b as BybitTickersBody, sign) : undefined));
  await page.route('**api.bybit.com/v5/market/kline**', r => fulfil(r, 'bybit-kline'));
  await page.route('**api.bybit.com/v5/market/open-interest**', r => fulfil(r, 'bybit-open-interest'));

  /* The remaining third-party surface. Enumerated by measuring all 32 routes in
   * ROUTES: 17 distinct endpoints, and 29 of 32 routes call at least one -
   * MarketProvider mounts on every page, so /about and /privacy are as chatty as
   * /arena. There is no "static routes only" subset.
   *
   * Pass-through, no transform: these exist so the contrast sweep stops
   * depending on live market state, not to assert anything about their values.
   * Large payloads are trimmed to the first 40-60 entries - shape is what the
   * app parses, volume is not. */
  await page.route('**/v5/market/account-ratio**', r => fulfil(r, 'bybit-account-ratio'));
  await page.route('**/v5/market/recent-trade**', r => fulfil(r, 'bybit-recent-trade'));
  await page.route('**api.binance.com/api/v3/aggTrades**', r => fulfil(r, 'binance-aggTrades'));
  await page.route('**api.binance.com/api/v3/klines**', r => fulfil(r, 'binance-klines'));
  await page.route('**api.binance.com/api/v3/depth**', r => fulfil(r, 'binance-depth'));
  await page.route('**fapi.binance.com/fapi/v1/klines**', r => fulfil(r, 'binance-fapi-klines'));
  await page.route('**futures/data/openInterestHist**', r => fulfil(r, 'binance-oi-hist'));
  await page.route('**futures/data/globalLongShortAccountRatio**', r => fulfil(r, 'binance-global-lsr'));
  await page.route('**futures/data/topLongShortPositionRatio**', r => fulfil(r, 'binance-top-lsr'));
  await page.route('**alternative.me/fng**', r => fulfil(r, 'alternative-fng'));
  await page.route('**deribit.com/api/v2/public/get_book_summary_by_currency**', r => fulfil(r, 'deribit-book-summary'));

  /* ── EVERY PATTERN ABOVE MATCHES A CALL THE BROWSER NO LONGER MAKES ─────────
   *
   * #238/#242 moved all of it behind `/api/proxy?type=...`, and the upstream
   * fetch now happens SERVER-SIDE where `page.route` cannot reach. So the
   * browser requests `/api/proxy?type=bybit-tickers`, nothing above matches, and
   * the fixture never fires.
   *
   * That is how it surfaced: `market-scenarios` failed with
   *
   *     bybit tickers was not intercepted - the rates on screen are live data
   *     served.byKey['bybit-tickers'] = 0
   *
   * The spec's own control caught it. Without that guard these would have gone
   * on "passing" against whatever the live market happened to be doing, which is
   * the failure this file exists to prevent.
   *
   * The patterns above are KEPT rather than replaced. They are now a tripwire: if
   * any of them ever fires again, a direct browser->exchange call has come back
   * and #238 has regressed. `byKey` names which one, so the regression arrives
   * labelled.
   *
   * Fixture bodies need no change. `/api/proxy` is a passthrough - it returns
   * `r.json()` from the upstream verbatim - so the recorded exchange payload is
   * exactly what the proxy would have served. */
  const PROXY_FIXTURES: Array<[type: string, key: string, transform?: (b: unknown) => unknown]> = [
    ['bybit-tickers',   'bybit-tickers',         sign ? (b) => bybitTickersSigned(b as BybitTickersBody, sign) : undefined],
    ['funding-history', 'bybit-funding-history', sign ? (b) => bybitFundingSigned(b as BybitFundingBody, sign) : undefined],
    ['funding-rate-1',  'binance-fundingRate',   sign ? (b) => binanceFundingSigned(b as BinanceFundingRow[], sign) : undefined],
    ['premium-index',   'binance-premiumIndex',  sign ? (b) => premiumIndexSigned(b as PremiumIndexRow[], sign) : undefined],
    ['open-interest-1', 'bybit-open-interest'],
    ['account-ratio-1', 'bybit-account-ratio'],
    ['recent-trade',    'bybit-recent-trade'],
    ['depth',           'binance-depth'],
    ['oi-hist',         'binance-oi-hist'],
    ['lsr-global',      'binance-global-lsr'],
    ['lsr-top',         'binance-top-lsr'],
    ['fng',             'alternative-fng'],
    ['deribit-book',    'deribit-book-summary'],

    /* ── THE FOUR THAT WERE GOING LIVE, AND THE ONE THAT MATTERS ──────────────
     *
     * Computed rather than eyeballed: browser-called proxy types minus
     * intercepted ones came to exactly four — `binance-24hr`, `etf`,
     * `llama-stables`, `trends`.
     *
     * `binance-24hr` IS #439. It is `restPoll()` in `MarketProvider.tsx:169`,
     * the fallback that fills `store.coins` when the price WebSocket is down —
     * which in CI it always is. Unintercepted, it went to the live network,
     * failed, left `store.coins` empty, and the Arena evidence grid (a pure
     * function over `CoinData`) rendered nothing. I spent five attempts blaming
     * `lib/arenaEvidence.ts` for a value that never arrived.
     *
     * Recorded with the socket deliberately blocked, because that is the state
     * CI runs in — see the header of `_record-proxy.spec.ts`. */
    ['binance-24hr',    'proxy-binance-24hr',
      scenario === 'price-sentinel'
        ? (b) => (b as Array<Record<string, string>>).map(r => ({ ...r, lastPrice: SENTINEL_PRICE }))
        : undefined],
    ['etf',             'proxy-etf'],
    ['llama-stables',   'proxy-llama-stables'],

    /* `trends` IS STILL LIVE, DELIBERATELY LISTED AS ABSENT RATHER THAN OMITTED.
     *
     * It never fired during three recording runs across `/`, `/arena`,
     * `/dashboard`, `/markets` and `/funding`, so there is nothing on disk to
     * serve and I will not hand-write one — a fixture typed from reading the
     * route asserts my reading of the route, which is the error this file spent
     * the day recovering from.
     *
     * Named here so the gap is visible in the list it is missing from. An
     * endpoint that is silently absent looks exactly like one that is covered. */
  ];

  for (const [type, key, transform] of PROXY_FIXTURES) {
    /* Anchored on a `&` or end-of-string so `type=funding-history` cannot be
       satisfied by `type=funding-rate-1` or vice versa - the two share a prefix
       and a loose pattern would silently serve the wrong fixture. */
    await page.route(
      new RegExp(`/api/proxy\\?(?:[^#]*&)?type=${type}(?:&|$)`),
      r => fulfil(r, key, transform),
    );
  }

  return served;
}


