-- FUNDING_*, CORRELATION_* rows (app/funding/page.tsx, app/correlation/page.tsx).
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('FUNDING_PAGE_TITLE','en','Funding Rate History'),
('FUNDING_PAGE_SUBTITLE','en','8-hour settlement · red above zero = longs paying · green below = shorts paying'),
('FUNDING_REGIME_OVERVIEW_TIP','en','A snapshot of every coin''s current funding regime: crowded-short setups (squeeze candidates), crowded-long setups (dump risk), and coins whose funding rate is extreme enough to arbitrage.'),
('FUNDING_REGIME_OVERVIEW_LABEL','en','Regime Overview'),
('FUNDING_CONTRARIAN_SHORT_TIP','en','Coins where longs are overcrowded and overpaying to hold - contrarian read: the crowd is positioned to get flushed, so a short setup on weakness has an edge.'),
('FUNDING_CONTRARIAN_SHORT_COUNT','en','{count} Contrarian Short{plural}'),
('FUNDING_CONTRARIAN_LONG_TIP','en','Coins where shorts are overcrowded and overpaying to hold - contrarian read: the crowd is positioned to get squeezed, so a long setup on dips has an edge.'),
('FUNDING_CONTRARIAN_LONG_COUNT','en','{count} Contrarian Long{plural}'),
('FUNDING_CARRY_ARB_TIP','en','Funding rate is extreme enough (over ~0.03%/8h) that a delta-neutral trade - long spot, short perp, or vice versa - can collect the funding payment with no directional price risk.'),
('FUNDING_CARRY_ARB_COUNT','en','{count} Carry Arb'),
('FUNDING_BADGE_SHORT_LABEL','en','Short'),
('FUNDING_BADGE_LONG_LABEL','en','Long'),
('FUNDING_BADGE_ARB_LABEL','en','Arb'),
('FUNDING_CARRY_ARB_FOOTNOTE','en','Carry Arb: annualized rate exceeds ~40% (|FR| greater than 0.03%/8h) - long spot + short perp captures the premium delta-neutral.'),
('FUNDING_RANGE_24H','en','24h'),
('FUNDING_RANGE_3D','en','3d'),
('FUNDING_RANGE_7D','en','7d'),
('FUNDING_RANGE_14D','en','14d'),
('FUNDING_RANGE_ROW_HINT','en','- avg column · sparklines · chart'),
('FUNDING_LOADING_MESSAGE','en','Fetching funding history…'),
('FUNDING_MARKET_LEAN_HEADING','en','Market lean'),
('FUNDING_LONG_HEAVY_LABEL','en','Long-heavy'),
('FUNDING_SHORT_HEAVY_LABEL','en','Short-heavy'),
('FUNDING_NEUTRAL_LABEL','en','Neutral'),
('FUNDING_SEARCH_PLACEHOLDER','en','Search coins…'),
('FUNDING_CLEAR_SEARCH_ARIA','en','Clear search'),
('FUNDING_TABLE_COIN_COL','en','Coin'),
('FUNDING_TABLE_CURRENT_COL','en','Current'),
('FUNDING_TABLE_AVG_COL','en','Avg {range}'),
('FUNDING_TABLE_SIGNAL_COL','en','Signal'),
('FUNDING_TABLE_LAST_COL','en','Last {range}'),
('FUNDING_NO_PERP_LABEL','en','No perp'),
('FUNDING_CHART_SUFFIX','en','CHART'),
('FUNDING_NOW_SUFFIX','en','now'),
('FUNDING_EXTREME_COUNT','en','{count} extreme{plural}'),
('FUNDING_NO_PERP_DATA','en','No perp data for {coin}'),
('FUNDING_LEGEND_POSITIVE_LABEL','en','● Positive FR'),
('FUNDING_LEGEND_POSITIVE_DESC','en','longs paying shorts → bearish pressure, expect dump'),
('FUNDING_LEGEND_NEGATIVE_LABEL','en','● Negative FR'),
('FUNDING_LEGEND_NEGATIVE_DESC','en','shorts paying longs → bullish pressure, expect squeeze'),
('FUNDING_SIG_LONGS_OVERCROWDED_CROWD','en','Longs Overcrowded'),
('FUNDING_SIG_LONGS_OVERCROWDED_HINT','en','Short on weakness'),
('FUNDING_SIG_LONGS_OVERCROWDED_LABEL','en','Longs Overcrowded - Dump Risk'),
('FUNDING_SIG_LONGS_OVERCROWDED_ACTION','en','Avoid new longs. Look to short on weakness.'),
('FUNDING_SIG_LONGS_OVERCROWDED_DESC','en','The market is extremely long-heavy. Traders are paying 0.05%+ every 8h just to stay long - they are overleveraged. Whales have maximum incentive to dump price and mass-liquidate these longs. High probability of a violent raid in the next 1–3 sessions.'),
('FUNDING_SIG_LONGS_HEAVY_CROWD','en','Longs Heavy'),
('FUNDING_SIG_LONGS_HEAVY_HINT','en','Reduce longs'),
('FUNDING_SIG_LONGS_HEAVY_LABEL','en','Longs Heavy - Elevated Dump Risk'),
('FUNDING_SIG_LONGS_HEAVY_ACTION','en','Reduce long exposure. Consider short entries.'),
('FUNDING_SIG_LONGS_HEAVY_DESC','en','The market is significantly long-heavy. Every 8-hour settlement, longs are bleeding fees to hold their position. This builds pressure for a flush - the crowd is positioned for a pump, which makes a dump more likely.'),
('FUNDING_SIG_LONGS_DOMINANT_CROWD','en','Longs Dominant'),
('FUNDING_SIG_LONGS_DOMINANT_HINT','en','Trade carefully'),
('FUNDING_SIG_LONGS_DOMINANT_LABEL','en','Long Bias - Watch for FR Spike'),
('FUNDING_SIG_LONGS_DOMINANT_ACTION','en','Trade cautiously. Exit if FR keeps climbing.'),
('FUNDING_SIG_LONGS_DOMINANT_DESC','en','More longs than shorts in the market. Not dangerous yet, but trending toward overload. If funding rate keeps rising above 0.02%, exit or hedge your long exposure.'),
('FUNDING_SIG_SLIGHT_LONG_CROWD','en','Slight Long Bias'),
('FUNDING_SIG_SLIGHT_LONG_HINT','en','No clear edge'),
('FUNDING_SIG_SLIGHT_LONG_LABEL','en','Slight Long Bias - No Clear Edge'),
('FUNDING_SIG_SLIGHT_LONG_ACTION','en','No derivatives edge. Trade based on price action.'),
('FUNDING_SIG_SLIGHT_LONG_DESC','en','Mildly more longs than shorts, but not enough to create a squeeze or dump setup. Price movement here is driven by spot buying and selling, not derivatives pressure.'),
('FUNDING_SIG_BALANCED_CROWD','en','Balanced'),
('FUNDING_SIG_BALANCED_HINT','en','No clear edge'),
('FUNDING_SIG_BALANCED_LABEL','en','Neutral - No Derivatives Edge'),
('FUNDING_SIG_BALANCED_ACTION','en','Wait for a clearer FR signal.'),
('FUNDING_SIG_BALANCED_DESC','en','Longs and shorts are balanced. Nobody is paying a significant premium to hold their position. The derivatives market is not a driver right now - focus on chart structure and spot flow.'),
('FUNDING_SIG_SHORTS_DOMINANT_CROWD','en','Shorts Dominant'),
('FUNDING_SIG_SHORTS_DOMINANT_HINT','en','Watch for squeeze'),
('FUNDING_SIG_SHORTS_DOMINANT_LABEL','en','Shorts Dominant - Squeeze Pressure Building'),
('FUNDING_SIG_SHORTS_DOMINANT_ACTION','en','Slight bullish lean. Small long positions on dips.'),
('FUNDING_SIG_SHORTS_DOMINANT_DESC','en','More shorts than longs in the market. Shorts are paying longs every 8h to hold their position. Mild squeeze pressure is building - not actionable yet, but watch for FR going deeper negative.'),
('FUNDING_SIG_SHORTS_CROWDED_CROWD','en','Shorts Crowded'),
('FUNDING_SIG_SHORTS_CROWDED_HINT','en','Buy dips'),
('FUNDING_SIG_SHORTS_CROWDED_LABEL','en','Shorts Crowded - Squeeze Setup'),
('FUNDING_SIG_SHORTS_CROWDED_ACTION','en','Look for long entries on dips. Do NOT short here.'),
('FUNDING_SIG_SHORTS_CROWDED_DESC','en','The market is heavily positioned short. Shorts are paying longs every 8 hours just to hold their position - they are the fuel for the next pump. Whales can push price up to mass-liquidate these shorts and collect their money. This is a squeeze setup, not a short signal.'),
('FUNDING_SIG_SHORTS_OVERCROWDED_CROWD','en','Shorts Overcrowded'),
('FUNDING_SIG_SHORTS_OVERCROWDED_HINT','en','Size up longs'),
('FUNDING_SIG_SHORTS_OVERCROWDED_LABEL','en','Shorts Overcrowded - High Squeeze Risk'),
('FUNDING_SIG_SHORTS_OVERCROWDED_ACTION','en','Strong long setup. Do NOT short. Size up on dips.'),
('FUNDING_SIG_SHORTS_OVERCROWDED_DESC','en','Extreme short crowding - traders are paying 0.03%+ every 8h just to stay short. This is unsustainable. Historically, this level of negative funding precedes a violent squeeze pump as whales push price up to liquidate the overleveraged shorts.'),
('CORRELATION_RANGE_24H','en','24h'),
('CORRELATION_RANGE_7D','en','7d'),
('CORRELATION_RANGE_30D','en','30d'),
('CORRELATION_PAGE_TITLE','en','Correlation Heatmap'),
('CORRELATION_PAGE_SUBTITLE','en','How coins move together · based on {range} price returns'),
('CORRELATION_LOADING_MESSAGE','en','Calculating correlations…'),
('CORRELATION_ALT_SIG_LOADING_LABEL','en','Loading…'),
('CORRELATION_ALT_SIG_ALT_SEASON_LABEL','en','Alt Season Conditions'),
('CORRELATION_ALT_SIG_ALT_SEASON_DESC','en','BTC-alt avg correlation is {avg} - very low. Altcoins are moving independently from BTC. This is when alts can outperform BTC significantly. Rotate into high-conviction alt setups.'),
('CORRELATION_ALT_SIG_MIXED_LABEL','en','Mixed Market'),
('CORRELATION_ALT_SIG_MIXED_DESC','en','Moderate BTC-alt correlation ({avg}). Some alts following BTC, others moving on their own catalyst. Selective alt plays possible but watch BTC direction first.'),
('CORRELATION_ALT_SIG_BTC_LEADING_LABEL','en','BTC Leading'),
('CORRELATION_ALT_SIG_BTC_LEADING_DESC','en','High BTC-alt correlation ({avg}). BTC is dragging most alts. Get BTC direction right before trading alts - individual setups matter less when correlation is this high.'),
('CORRELATION_ALT_SIG_LOCKSTEP_LABEL','en','BTC Dominance - Alts Lockstep'),
('CORRELATION_ALT_SIG_LOCKSTEP_DESC','en','Very high BTC-alt correlation ({avg}). Everything pumps and dumps with BTC. No independent alt edge right now - trade BTC or wait for correlation to break.'),
('CORRELATION_AVG_BTC_ALT_LABEL','en','avg BTC-alt: {avg}'),
('CORRELATION_MATRIX_TIP','en','Measures how tightly two coins'' price returns move together over the window, from +1 (identical moves) to -1 (opposite). High correlation means holding both gives little diversification - you are effectively doubling the same bet.'),
('CORRELATION_MATRIX_LABEL','en','Price Return Correlation'),
('CORRELATION_MATRIX_SCALE_HINT','en','+1.00 = perfect sync · 0.00 = no relation · −1.00 = opposite'),
('CORRELATION_SCROLL_HINT','en','swipe to see all coins →'),
('CORRELATION_LEGEND_GREEN_LABEL','en','■ Green'),
('CORRELATION_LEGEND_GREEN_DESC','en','moves together'),
('CORRELATION_LEGEND_RED_LABEL','en','■ Red'),
('CORRELATION_LEGEND_RED_DESC','en','moves opposite'),
('CORRELATION_LEGEND_BRIGHTNESS_HINT','en','Brighter = stronger relationship'),
('CORRELATION_STRONGEST_PAIRS_TITLE','en','Most Correlated Pairs'),
('CORRELATION_WEAKEST_PAIRS_TITLE','en','Least Correlated Pairs'),
('CORRELATION_WEAKEST_PAIRS_HINT','en','- potential diversification')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
