-- Wave 11 (final content wave): SOTD, BacktestStatsUI, TradeJournal, LiqFeed,
-- CoinMarketSnapshot, OnboardingFlow, SpotlightTour, LearnContent.
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('SOTD_STATIC_BADGE_TOOLTIP','en','Reference content - a fixed library of trading concepts, not computed from current market data'),
('SOTD_BADGE_LABEL','en','Playbook'),
('SOTD_NUM_LABEL','en','#{n} of {total}'),
('SOTD_NEW_PLAY_BUTTON','en','new play'),
('SOTD_FOOTER','en','Educational reference, not a live signal. Tap "new play" for another - a different one also loads automatically each day.'),
('BACKTEST_STATS_UI_EMPTY_CHART','en','Not enough resolved trades to chart'),
('BACKTEST_STATS_UI_LABEL_WIN_RATE','en','Win Rate'),
('BACKTEST_STATS_UI_TIP_WIN_RATE','en','The share of signals that hit take-profit before stop-loss. On its own it can mislead - a strategy can win under half its trades and still profit if the wins are larger than the losses.'),
('BACKTEST_STATS_UI_LABEL_TRADES','en','Trades'),
('BACKTEST_STATS_UI_TRADES_VALUE','en','{total} ({wins}W / {losses}L / {open} open)'),
('BACKTEST_STATS_UI_LABEL_PROFIT_FACTOR','en','Profit Factor'),
('BACKTEST_STATS_UI_TIP_PROFIT_FACTOR','en','Gross profit divided by gross loss. Above 1.0 means the strategy made money overall, and 1.5+ is strong; below 1.0 means it lost money across all trades.'),
('BACKTEST_STATS_UI_LABEL_AVG_R','en','Avg R / Trade'),
('BACKTEST_STATS_UI_TIP_AVG_R','en','Average result per trade in R - multiples of the amount risked. +0.20R means each trade netted a fifth of what was risked on average, which is the clearest single measure of a real edge.'),
('BACKTEST_STATS_UI_LABEL_MAX_DRAWDOWN','en','Max Drawdown'),
('BACKTEST_STATS_UI_TIP_MAX_DRAWDOWN','en','The largest peak-to-trough drop in cumulative R before the strategy recovered. It shows the worst losing streak you would have had to sit through - how painful the strategy is to actually hold.'),
('COIN_MARKET_SNAPSHOT_VWAP_TOOLTIP','en','Volume Weighted Average Price - the average price across the day, weighted by how much was traded at each level. Price above VWAP signals buy-side control; below signals sellers are in charge.'),
('COIN_MARKET_SNAPSHOT_VWAP_LABEL','en','VWAP'),
('COIN_MARKET_SNAPSHOT_VWAP_SIGNAL','en','{arrow} {pct} vs VWAP'),
('COIN_MARKET_SNAPSHOT_OI_TOOLTIP','en','Open Interest is the total number of live futures contracts, with its 1-hour change. Rising OI + rising price = new longs entering (real conviction). Falling OI + rising price = shorts covering (weaker signal). The 1h change shows how fast money is entering or leaving right now.'),
('COIN_MARKET_SNAPSHOT_OI_LABEL','en','Open Interest'),
('COIN_MARKET_SNAPSHOT_OI_STRONG_UP_TXT','en','▲ New buyers'),
('COIN_MARKET_SNAPSHOT_OI_STRONG_UP_SUB','en','OI + price up · real trend'),
('COIN_MARKET_SNAPSHOT_OI_STRONG_DOWN_TXT','en','▼ New sellers'),
('COIN_MARKET_SNAPSHOT_OI_STRONG_DOWN_SUB','en','OI up, price down · real dump'),
('COIN_MARKET_SNAPSHOT_OI_WEAK_UP_TXT','en','△ Short covering'),
('COIN_MARKET_SNAPSHOT_OI_WEAK_UP_SUB','en','OI down, price up · weak'),
('COIN_MARKET_SNAPSHOT_OI_WEAK_DOWN_TXT','en','▽ Long exits'),
('COIN_MARKET_SNAPSHOT_OI_WEAK_DOWN_SUB','en','OI + price down · no panic'),
('COIN_MARKET_SNAPSHOT_OI_1H_PCT_SUFFIX','en',' · {pct} 1h'),
('COIN_MARKET_SNAPSHOT_OI_FLAT','en','Flat'),
('COIN_MARKET_SNAPSHOT_OI_1H_TREND_SUFFIX','en','{txt} · 1h'),
('COIN_MARKET_SNAPSHOT_OI_NO_SIGNAL','en','No strong signal'),
('COIN_MARKET_SNAPSHOT_FUNDING_TOOLTIP','en','The fee longs pay shorts every 8 hours to keep perpetual futures positions open. Strongly positive means too many people are leveraged long - whales often dump price to liquidate them and pocket the fee.'),
('COIN_MARKET_SNAPSHOT_FUNDING_LABEL','en','Funding Rate'),
('COIN_MARKET_SNAPSHOT_FR_LOADING','en','Loading…'),
('COIN_MARKET_SNAPSHOT_FR_LONGS_OVERCROWDED','en','Longs overcrowded ↓'),
('COIN_MARKET_SNAPSHOT_FR_MILD_LONG_BIAS','en','Mild long bias'),
('COIN_MARKET_SNAPSHOT_FR_SHORTS_OVERCROWDED','en','Shorts overcrowded ↑'),
('COIN_MARKET_SNAPSHOT_FR_MILD_SHORT_BIAS','en','Mild short bias'),
('COIN_MARKET_SNAPSHOT_FR_NEUTRAL','en','Neutral'),
('LEARN_CONTENT_NAV_OPEN_DASHBOARD','en','Open Dashboard'),
('LEARN_CONTENT_NAV_SIGN_IN','en','Sign In'),
('LEARN_CONTENT_NAV_GET_STARTED','en','Get Started'),
('LEARN_CONTENT_HEADING_MAIN','en','Crypto Trading'),
('LEARN_CONTENT_HEADING_ACCENT','en','Glossary'),
('LEARN_CONTENT_HERO_SUB','en','Plain-English definitions for the momentum, order-flow, sentiment, and risk terms used throughout LiquidityHQ - and across crypto trading generally.'),
('LEARN_CONTENT_SEARCH_PLACEHOLDER','en','Search terms…'),
('LEARN_CONTENT_SEARCH_ARIA_LABEL','en','Search glossary terms'),
('LEARN_CONTENT_EMPTY_STATE','en','No terms match "{query}".'),
('LEARN_CONTENT_CTA_HEADING','en','See these signals live, not just defined.'),
('LEARN_CONTENT_CTA_BUTTON','en','Get Started Free'),
('ONBOARDING_FLOW_STEP_PROFILE','en','Profile'),
('ONBOARDING_FLOW_STEP_EXPERIENCE','en','Experience'),
('ONBOARDING_FLOW_STEP_STYLE','en','Style'),
('ONBOARDING_FLOW_STEP_GOALS','en','Goals'),
('ONBOARDING_FLOW_STEP_SOURCE','en','Source'),
('ONBOARDING_FLOW_HEADLINE_PROFILE_1','en','Set up your'),
('ONBOARDING_FLOW_HEADLINE_PROFILE_2','en','profile.'),
('ONBOARDING_FLOW_DESC_PROFILE','en','Personalizes your signals, alerts, and position sizing.'),
('ONBOARDING_FLOW_HEADLINE_EXPERIENCE_1','en','How long have you been'),
('ONBOARDING_FLOW_HEADLINE_EXPERIENCE_2','en','trading crypto?'),
('ONBOARDING_FLOW_DESC_EXPERIENCE','en','Sets Beginner Mode on or off for your dashboard.'),
('ONBOARDING_FLOW_HEADLINE_STYLE_1','en','How do you'),
('ONBOARDING_FLOW_HEADLINE_STYLE_2','en','mainly trade?'),
('ONBOARDING_FLOW_DESC_STYLE','en','Pre-selects your default chart timeframe in Arena.'),
('ONBOARDING_FLOW_HEADLINE_GOALS_1','en','What is your biggest'),
('ONBOARDING_FLOW_HEADLINE_GOALS_2','en','challenge?'),
('ONBOARDING_FLOW_DESC_GOALS','en','Surfaces the most relevant signals and education for you.'),
('ONBOARDING_FLOW_HEADLINE_SOURCE_1','en','Where did you find'),
('ONBOARDING_FLOW_HEADLINE_SOURCE_2','en','LiquidityHQ?'),
('ONBOARDING_FLOW_DESC_SOURCE','en','Optional - helps us know where to invest our energy.'),
('ONBOARDING_FLOW_STEP_PREFIX','en','STEP {num}'),
('ONBOARDING_FLOW_SELECT_COUNTRY_PLACEHOLDER','en','Select your country…'),
('ONBOARDING_FLOW_SEARCH_COUNTRY_PLACEHOLDER','en','Search country…'),
('ONBOARDING_FLOW_NO_MATCH','en','No match'),
('ONBOARDING_FLOW_ACCT_1K_5K','en','$1k - $5k'),
('ONBOARDING_FLOW_ACCT_5K_25K','en','$5k - $25k'),
('ONBOARDING_FLOW_ACCT_25K_100K','en','$25k - $100k'),
('ONBOARDING_FLOW_ACCT_100K_PLUS','en','$100k+'),
('ONBOARDING_FLOW_DISPLAY_NAME_LABEL','en','Display name'),
('ONBOARDING_FLOW_OPTIONAL','en','(optional)'),
('ONBOARDING_FLOW_DISPLAY_NAME_PLACEHOLDER','en','e.g. trader_dom'),
('ONBOARDING_FLOW_COUNTRY_LABEL','en','Country'),
('ONBOARDING_FLOW_ACCOUNT_RANGE_LABEL','en','Trading account range'),
('ONBOARDING_FLOW_EXP_LT6M_LABEL','en','Less than 6 months'),
('ONBOARDING_FLOW_EXP_LT6M_SUB','en','Just getting started - Beginner Mode enabled'),
('ONBOARDING_FLOW_EXP_6TO12M_LABEL','en','6-12 months'),
('ONBOARDING_FLOW_EXP_6TO12M_SUB','en','Finding my footing - Beginner Mode enabled'),
('ONBOARDING_FLOW_EXP_1TO3Y_LABEL','en','1-3 years'),
('ONBOARDING_FLOW_EXP_1TO3Y_SUB','en','Getting comfortable - full tools unlocked'),
('ONBOARDING_FLOW_EXP_3PLUS_LABEL','en','3+ years'),
('ONBOARDING_FLOW_EXP_3PLUS_SUB','en','I know what I am doing - full access'),
('ONBOARDING_FLOW_STYLE_SCALP_LABEL','en','Scalp'),
('ONBOARDING_FLOW_STYLE_SCALP_SUB','en','Minutes to hours - defaults to 5m chart'),
('ONBOARDING_FLOW_STYLE_SWING_LABEL','en','Swing trade'),
('ONBOARDING_FLOW_STYLE_SWING_SUB','en','Days to weeks - defaults to 4h chart'),
('ONBOARDING_FLOW_STYLE_BOTH_LABEL','en','Both'),
('ONBOARDING_FLOW_STYLE_BOTH_SUB','en','Depends on the setup - defaults to 15m chart'),
('ONBOARDING_FLOW_STYLE_LEARNING_LABEL','en','Still learning'),
('ONBOARDING_FLOW_STYLE_LEARNING_SUB','en','Not sure yet - Beginner Mode on'),
('ONBOARDING_FLOW_CHALLENGE_SIGNALS_LABEL','en','Reading the signals correctly'),
('ONBOARDING_FLOW_CHALLENGE_SIGNALS_SUB','en','Not sure what the data is telling me'),
('ONBOARDING_FLOW_CHALLENGE_ENTRY_EXIT_LABEL','en','Knowing when to enter and exit'),
('ONBOARDING_FLOW_CHALLENGE_ENTRY_EXIT_SUB','en','Always too early, too late, or too scared'),
('ONBOARDING_FLOW_CHALLENGE_RISK_LABEL','en','Managing risk and not overtrading'),
('ONBOARDING_FLOW_CHALLENGE_RISK_SUB','en','Position sizing, stop losses, overexposure'),
('ONBOARDING_FLOW_CHALLENGE_DISCIPLINE_LABEL','en','Staying disciplined and patient'),
('ONBOARDING_FLOW_CHALLENGE_DISCIPLINE_SUB','en','Chasing trades, revenge trading, FOMO'),
('ONBOARDING_FLOW_SOURCE_SOCIAL','en','Facebook / Instagram'),
('ONBOARDING_FLOW_SOURCE_YOUTUBE','en','YouTube'),
('ONBOARDING_FLOW_SOURCE_TIKTOK','en','TikTok'),
('ONBOARDING_FLOW_SOURCE_SEARCH','en','Search'),
('ONBOARDING_FLOW_SOURCE_WORD','en','Word of mouth'),
('ONBOARDING_FLOW_SOURCE_OTHER','en','Other'),
('ONBOARDING_FLOW_BACK','en','← Back'),
('ONBOARDING_FLOW_SAVING','en','Setting up…'),
('ONBOARDING_FLOW_LAUNCH_DASHBOARD','en','Launch Dashboard →'),
('ONBOARDING_FLOW_CONTINUE','en','Continue →'),
('ONBOARDING_FLOW_SKIP_QUESTION','en','Skip this question →'),
('ONBOARDING_FLOW_LOADING','en','Loading…'),
('ONBOARDING_FLOW_FOOTER_DISCLAIMER','en','LiquidityHQ provides data analytics and software tools for informational purposes only. This is not financial, investment, or trading advice. Trade at your own risk.'),
('ONBOARDING_FLOW_FOOTER_TERMS','en','Terms of Use'),
('ONBOARDING_FLOW_FOOTER_PRIVACY','en','Privacy Policy'),
('ONBOARDING_FLOW_FOOTER_DISCLAIMER_LINK','en','Full Disclaimer'),
('ONBOARDING_FLOW_FOOTER_COPYRIGHT','en','© {year} LIQUIDITYHQ'),
('SPOTLIGHT_TOUR_CARD1_LABEL','en','Funding Rate'),
('SPOTLIGHT_TOUR_CARD1_SUB','en','3× more shorts'),
('SPOTLIGHT_TOUR_CARD2_LABEL','en','OI Change 4h'),
('SPOTLIGHT_TOUR_CARD2_SUB','en','New shorts piling in'),
('SPOTLIGHT_TOUR_CARD3_LABEL','en','Squeeze Score'),
('SPOTLIGHT_TOUR_CARD3_SUB','en','SHORT_SQ forming'),
('SPOTLIGHT_TOUR_FUNDING_HEADER','en','Funding Rate - BTC'),
('SPOTLIGHT_TOUR_CHIP_SHORTS_PAYING','en','Shorts paying longs'),
('SPOTLIGHT_TOUR_CHIP_OVERCROWDED','en','Overcrowded short side'),
('SPOTLIGHT_TOUR_CHIP_SQUEEZE_FUEL','en','Squeeze fuel building'),
('SPOTLIGHT_TOUR_OI_HEADER','en','Open Interest Change - BTC'),
('SPOTLIGHT_TOUR_OI_CAPTION','en','Each red bar = more shorts entering. The last 3 bars (red) accelerated - a squeeze is loading.'),
('SPOTLIGHT_TOUR_TELEGRAM_SENT','en','Telegram alert sent'),
('SPOTLIGHT_TOUR_TELEGRAM_BODY','en','BTC SHORT_SQ 82/100 - squeeze forming'),
('SPOTLIGHT_TOUR_ALERT_FIRED','en','Alert fired - BTC LONG_SQ 87/100'),
('SPOTLIGHT_TOUR_STEP1_TAG','en','THE SETUP'),
('SPOTLIGHT_TOUR_STEP1_TITLE','en','This is a squeeze setup.'),
('SPOTLIGHT_TOUR_STEP1_BODY','en','When shorts overcrowd a market and price reverses, they all close at once - that spike is the squeeze. LiquidityHQ detects it before it fires.'),
('SPOTLIGHT_TOUR_STEP2_TAG','en','SIGNAL 1 OF 3'),
('SPOTLIGHT_TOUR_STEP2_TITLE','en','Funding rate goes negative.'),
('SPOTLIGHT_TOUR_STEP2_BODY','en','When funding is negative, shorts pay longs to hold their position. It means the market is overcrowded on the short side - and that''s exactly the fuel a squeeze needs.'),
('SPOTLIGHT_TOUR_STEP3_TAG','en','SIGNAL 2 OF 3'),
('SPOTLIGHT_TOUR_STEP3_TITLE','en','Open interest climbs.'),
('SPOTLIGHT_TOUR_STEP3_BODY','en','More shorts are opening. Every new short is potential energy. When price reverses even slightly, margin calls cascade - that acceleration is the squeeze.'),
('SPOTLIGHT_TOUR_STEP4_TAG','en','SIGNAL 3 OF 3'),
('SPOTLIGHT_TOUR_STEP4_TITLE','en','LiquidityHQ scores it and alerts you.'),
('SPOTLIGHT_TOUR_STEP4_BODY','en','Funding rate, OI change, volume, and RSI are combined into a single score. When it hits 70+, a Telegram alert fires before the crowd sees the move.'),
('SPOTLIGHT_TOUR_STEP5_TAG','en','YOU''RE READY'),
('SPOTLIGHT_TOUR_STEP5_TITLE','en','Your scanner is live right now.'),
('SPOTLIGHT_TOUR_STEP5_BODY','en','LiquidityHQ is scanning every major coin in real time. Open Arena to see live scores, pick a coin, and let LiquidityAI analyze the setup for you.'),
('SPOTLIGHT_TOUR_SKIP_ARIA','en','Skip tour'),
('SPOTLIGHT_TOUR_BACK_BTN','en','← Back'),
('SPOTLIGHT_TOUR_NEXT_BTN','en','Next →'),
('SPOTLIGHT_TOUR_OPEN_ARENA_BTN','en','Open Arena →'),
('LIQ_FEED_TITLE','en','Live Liquidations'),
('LIQ_FEED_TOOLTIP','en','Every leveraged position force-closed for >$10K on Binance or Bybit, in real time. A burst of same-side liquidations in a short window (''cascade'') can accelerate a move as forced selling/buying feeds on itself.'),
('LIQ_FEED_BINANCE_STATUS_TITLE','en','Binance: {status}'),
('LIQ_FEED_BYBIT_STATUS_TITLE','en','Bybit: {status}'),
('LIQ_FEED_SOURCES_LINE','en','Binance + Bybit · >$10K · {status}'),
('LIQ_FEED_EVENTS_COUNT','en','{count} events'),
('LIQ_FEED_WAITING','en','waiting…'),
('LIQ_FEED_CASCADE_LONG','en','LONG CASCADE'),
('LIQ_FEED_CASCADE_SHORT','en','SHORT CASCADE'),
('LIQ_FEED_CASCADE_MIXED','en','CASCADE'),
('LIQ_FEED_CASCADE_WIPED','en','{amount} wiped in 30s'),
('LIQ_FEED_STAT_LONGS','en','Longs liq''d (1h)'),
('LIQ_FEED_STAT_EVENTS','en','Events'),
('LIQ_FEED_STAT_SHORTS','en','Shorts liq''d (1h)'),
('LIQ_FEED_BIAS_LONG_DOM','en','Longs getting wrecked - price accelerating down'),
('LIQ_FEED_BIAS_SHORT_DOM','en','Shorts getting wrecked - price accelerating up'),
('LIQ_FEED_BIAS_BALANCED','en','Balanced - no dominant side liquidating'),
('LIQ_FEED_CLUSTERS_TITLE','en','Hot price levels · 24h cluster'),
('LIQ_FEED_CLUSTERS_SUBTITLE','en','- where liqs are concentrating'),
('LIQ_FEED_DOM_LONG_ABBR','en','L'),
('LIQ_FEED_DOM_SHORT_ABBR','en','S'),
('LIQ_FEED_SR_WATCHING','en','Watching for {coin} liquidations > $10K…'),
('LIQ_FEED_ALL_MARKETS','en','all markets'),
('LIQ_FEED_SR_CONNECTING','en','Connecting to Binance + Bybit…'),
('LIQ_FEED_ROW_LONG','en','LONG LIQ'),
('LIQ_FEED_ROW_SHORT','en','SHORT LIQ'),
('TRADE_JOURNAL_NO_DB_TITLE','en','Supabase not configured'),
('TRADE_JOURNAL_NO_DB_MESSAGE','en','Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to enable the trade journal.'),
('TRADE_JOURNAL_PAGE_TITLE','en','Trade Journal'),
('TRADE_JOURNAL_PAGE_SUBTITLE','en','Log every trade · track results · build discipline'),
('TRADE_JOURNAL_TAB_LOG','en','+ Log Trade'),
('TRADE_JOURNAL_TAB_HISTORY','en','History ({count})'),
('TRADE_JOURNAL_TAB_STATS','en','Stats'),
('TRADE_JOURNAL_TAB_RULES','en','Rules'),
('TRADE_JOURNAL_TAB_SHADOW','en','Shadow Account'),
('TRADE_JOURNAL_TAB_BIAS','en','Bias Diagnostics'),
('TRADE_JOURNAL_TAB_THESIS','en','Thesis Tracker'),
('TRADE_JOURNAL_CONFIRM_DELETE_TRADE','en','Delete this trade?'),
('TRADE_JOURNAL_SHADOW_NEED_MORE_TRADES','en','Need at least 5 closed trades to run analysis (you have {count}).'),
('TRADE_JOURNAL_BIAS_NEED_MORE_TRADES','en','Need at least 5 closed trades (you have {count}).'),
('TRADE_JOURNAL_ANALYSIS_FAILED','en','Analysis failed'),
('TRADE_JOURNAL_NETWORK_ERROR','en','Network error - try again'),
('TRADE_JOURNAL_SHADOW_SECTION_IMPLICIT_RULES','en','Implicit Trading Rules'),
('TRADE_JOURNAL_SHADOW_SECTION_BEHAVIORAL_PATTERNS','en','Behavioral Patterns'),
('TRADE_JOURNAL_SHADOW_SECTION_STRATEGY','en','Shadow Strategy'),
('TRADE_JOURNAL_SHADOW_SECTION_VIOLATIONS','en','Rule Violations'),
('TRADE_JOURNAL_SHADOW_SECTION_RECOMMENDATIONS','en','Recommendations'),
('TRADE_JOURNAL_SHADOW_SECTION_KEY_INSIGHT','en','Key Insight'),
('TRADE_JOURNAL_BIAS_SECTION_DISPOSITION_EFFECT','en','Disposition Effect'),
('TRADE_JOURNAL_BIAS_SECTION_OVERTRADING','en','Overtrading'),
('TRADE_JOURNAL_BIAS_SECTION_MOMENTUM_CHASING','en','Momentum Chasing'),
('TRADE_JOURNAL_BIAS_SECTION_ANCHORING','en','Anchoring Bias'),
('TRADE_JOURNAL_BIAS_SECTION_PNL_IMPACT','en','P&L Impact by Bias'),
('TRADE_JOURNAL_BIAS_SECTION_PRIORITY_FIX','en','Priority Fix'),
('TRADE_JOURNAL_WARN_STOP_ABOVE_ENTRY_LONG','en','Stop ${stop} is above entry ${entry} on a LONG - stop should be below entry.'),
('TRADE_JOURNAL_WARN_STOP_BELOW_ENTRY_SHORT','en','Stop ${stop} is below entry ${entry} on a SHORT - stop should be above entry.'),
('TRADE_JOURNAL_WARN_TP_BELOW_ENTRY_LONG','en','Take-profit ${tp} is at or below entry ${entry} on a LONG - TP should be above entry.'),
('TRADE_JOURNAL_WARN_TP_ABOVE_ENTRY_SHORT','en','Take-profit ${tp} is at or above entry ${entry} on a SHORT - TP should be below entry.'),
('TRADE_JOURNAL_LOG_COIN_DIRECTION_LABEL','en','Coin & Direction'),
('TRADE_JOURNAL_LOG_DIR_LONG_BUTTON','en','LONG'),
('TRADE_JOURNAL_LOG_DIR_SHORT_BUTTON','en','SHORT'),
('TRADE_JOURNAL_LOG_SETUP_TYPE_LABEL','en','Setup Type'),
('TRADE_JOURNAL_LOG_PRICE_LEVELS_LABEL','en','Price Levels'),
('TRADE_JOURNAL_LOG_ENTRY_LABEL','en','Entry *'),
('TRADE_JOURNAL_LOG_ENTRY_ARIA','en','Entry'),
('TRADE_JOURNAL_LOG_STOP_LOSS_LABEL','en','Stop Loss *'),
('TRADE_JOURNAL_LOG_STOP_LOSS_ARIA','en','Stop Loss'),
('TRADE_JOURNAL_LOG_TAKE_PROFIT_LABEL','en','Take Profit'),
('TRADE_JOURNAL_LOG_POSITION_SIZE_LABEL','en','Position Size ($)'),
('TRADE_JOURNAL_LOG_POSITION_SIZE_ARIA','en','Position Size'),
('TRADE_JOURNAL_LOG_POSITION_SIZE_PLACEHOLDER','en','from calc'),
('TRADE_JOURNAL_LOG_RISK_LINE','en','✓ Risk: ${amount}'),
('TRADE_JOURNAL_LOG_RISK_AUTO_SUFFIX','en','(auto from Position Sizer)'),
('TRADE_JOURNAL_LOG_LEVERAGE_LABEL','en','Leverage'),
('TRADE_JOURNAL_LOG_LEVERAGE_VALUE_ARIA','en','Leverage value'),
('TRADE_JOURNAL_LOG_LEV_WARN_EXTREME','en','Liquidation risk is extreme - positions can vanish instantly'),
('TRADE_JOURNAL_LOG_LEV_WARN_VERY_HIGH','en','Very high leverage - use micro position sizes only'),
('TRADE_JOURNAL_LOG_LEV_WARN_HIGH','en','High leverage - ensure your stop loss is tight'),
('TRADE_JOURNAL_LOG_NOTES_LABEL','en','Notes'),
('TRADE_JOURNAL_LOG_NOTES_ARIA','en','Trade notes'),
('TRADE_JOURNAL_LOG_NOTES_PLACEHOLDER','en','Why you took this trade, market context, setup quality…'),
('TRADE_JOURNAL_LOG_LEVEL_WARNINGS_TITLE','en','Price levels don''t match direction'),
('TRADE_JOURNAL_LOG_RULE_VIOLATION_TITLE','en','Rule violation{plural} - review before logging'),
('TRADE_JOURNAL_LOG_SAVING_BUTTON','en','Saving…'),
('TRADE_JOURNAL_LOG_SUBMIT_WITH_VIOLATIONS','en','Log Trade ({count} violation{plural})'),
('TRADE_JOURNAL_LOG_SUBMIT_BUTTON','en','Log Trade'),
('TRADE_JOURNAL_HISTORY_LOADING_MESSAGE','en','Loading trades…'),
('TRADE_JOURNAL_HISTORY_EMPTY_TITLE','en','Your trade history starts here'),
('TRADE_JOURNAL_HISTORY_EMPTY_DESC','en','Log your first trade to start tracking P&L, win rate, R-factor, and behavioral patterns across your entire trading history.'),
('TRADE_JOURNAL_HISTORY_EMPTY_BULLET_PNL','en','Track P&L and R-factor'),
('TRADE_JOURNAL_HISTORY_EMPTY_BULLET_WINRATE','en','Win rate by setup type'),
('TRADE_JOURNAL_HISTORY_EMPTY_BULLET_BIAS','en','Spot your behavioral biases'),
('TRADE_JOURNAL_HISTORY_EMPTY_CTA','en','Log your first trade'),
('TRADE_JOURNAL_HISTORY_RULE_VIOLATION_TITLE','en','Violated one or more active rules'),
('TRADE_JOURNAL_HISTORY_RULE_BADGE','en','RULE'),
('TRADE_JOURNAL_HISTORY_EDIT_TITLE','en','Edit'),
('TRADE_JOURNAL_HISTORY_TP_ENTRY_LABEL','en','Entry'),
('TRADE_JOURNAL_HISTORY_TP_STOP_LABEL','en','Stop'),
('TRADE_JOURNAL_HISTORY_TP_TP_LABEL','en','TP'),
('TRADE_JOURNAL_HISTORY_TP_EXIT_LABEL','en','Exit'),
('TRADE_JOURNAL_HISTORY_TP_PNL_LABEL','en','P&L'),
('TRADE_JOURNAL_HISTORY_TP_R_LABEL','en','R'),
('TRADE_JOURNAL_HISTORY_EXIT_PRICE_PLACEHOLDER','en','Exit price'),
('TRADE_JOURNAL_HISTORY_CLOSE_CONFIRM_BUTTON','en','Close'),
('TRADE_JOURNAL_HISTORY_CANCEL_BUTTON','en','Cancel'),
('TRADE_JOURNAL_HISTORY_CLOSE_TRADE_BUTTON','en','Close Trade'),
('TRADE_JOURNAL_HISTORY_EDIT_RESULT_LABEL','en','Result'),
('TRADE_JOURNAL_HISTORY_RESULT_OPEN','en','OPEN'),
('TRADE_JOURNAL_HISTORY_RESULT_WIN','en','WIN'),
('TRADE_JOURNAL_HISTORY_RESULT_LOSS','en','LOSS'),
('TRADE_JOURNAL_HISTORY_RESULT_BE','en','BE'),
('TRADE_JOURNAL_HISTORY_EDIT_EXIT_PRICE_LABEL','en','Exit Price'),
('TRADE_JOURNAL_HISTORY_EDIT_PNL_LABEL','en','P&L ($)'),
('TRADE_JOURNAL_HISTORY_EDIT_NOTES_LABEL','en','Notes'),
('TRADE_JOURNAL_HISTORY_SAVE_BUTTON','en','Save'),
('TRADE_JOURNAL_HISTORY_PAGE_RANGE','en','{start}–{end} of {total}'),
('TRADE_JOURNAL_HISTORY_PREV_BUTTON','en','Prev'),
('TRADE_JOURNAL_HISTORY_NEXT_BUTTON','en','Next'),
('TRADE_JOURNAL_RULES_FIELD_COIN','en','Coin'),
('TRADE_JOURNAL_RULES_FIELD_DIRECTION','en','Direction'),
('TRADE_JOURNAL_RULES_FIELD_SETUP','en','Setup'),
('TRADE_JOURNAL_RULES_FIELD_LEVERAGE','en','Leverage'),
('TRADE_JOURNAL_RULES_FIELD_SESSION','en','Session'),
('TRADE_JOURNAL_RULES_OP_IS','en','is'),
('TRADE_JOURNAL_RULES_OP_IS_NOT','en','is not'),
('TRADE_JOURNAL_RULES_OP_LTE','en','≤'),
('TRADE_JOURNAL_RULES_OP_GTE','en','≥'),
('TRADE_JOURNAL_RULES_PRESET_LONG_BTC_ETH','en','Only long BTC/ETH'),
('TRADE_JOURNAL_RULES_PRESET_MAX_20X_LEVERAGE','en','Max 20x leverage'),
('TRADE_JOURNAL_RULES_PRESET_ONLY_LONG','en','Only LONG trades'),
('TRADE_JOURNAL_RULES_PRESET_SQUEEZE_ONLY','en','Squeeze setups only'),
('TRADE_JOURNAL_RULES_PRESET_NY_LONDON','en','NY or London only'),
('TRADE_JOURNAL_RULES_PRESET_NO_OTHER_SETUP','en','No Other setup'),
('TRADE_JOURNAL_RULES_PAGE_TITLE','en','Trading Rules'),
('TRADE_JOURNAL_RULES_PAGE_SUBTITLE','en','Define your rules - violations flag in real time when logging a trade and badge past trades in History.'),
('TRADE_JOURNAL_RULES_QUICK_ADD_LABEL','en','Quick Add'),
('TRADE_JOURNAL_RULES_ACTIVE_RULES_LABEL','en','Active Rules ({enabled} of {total} enabled)'),
('TRADE_JOURNAL_RULES_TOGGLE_DISABLE_TITLE','en','Disable'),
('TRADE_JOURNAL_RULES_TOGGLE_ENABLE_TITLE','en','Enable'),
('TRADE_JOURNAL_RULES_EMPTY_STATE','en','No rules yet - add a preset above or create a custom rule below.'),
('TRADE_JOURNAL_RULES_CANCEL_BUTTON','en','Cancel'),
('TRADE_JOURNAL_RULES_CUSTOM_RULE_BUTTON','en','Custom Rule'),
('TRADE_JOURNAL_RULES_FORM_TITLE','en','New Rule'),
('TRADE_JOURNAL_RULES_SELECT_COIN_PLACEHOLDER','en','Select coin'),
('TRADE_JOURNAL_RULES_SELECT_DIRECTION_PLACEHOLDER','en','Select direction'),
('TRADE_JOURNAL_RULES_DIRECTION_LONG','en','LONG'),
('TRADE_JOURNAL_RULES_DIRECTION_SHORT','en','SHORT'),
('TRADE_JOURNAL_RULES_SELECT_SETUP_PLACEHOLDER','en','Select setup'),
('TRADE_JOURNAL_RULES_SELECT_SESSION_PLACEHOLDER','en','Select session'),
('TRADE_JOURNAL_RULES_LEVERAGE_PLACEHOLDER','en','e.g. 20'),
('TRADE_JOURNAL_RULES_NAME_PLACEHOLDER','en','Rule name (e.g. No high leverage)'),
('TRADE_JOURNAL_RULES_ADD_RULE_BUTTON','en','Add Rule'),
('TRADE_JOURNAL_SHADOW_PAGE_TITLE','en','Shadow Account'),
('TRADE_JOURNAL_SHADOW_PAGE_SUBTITLE','en','AI analysis of your trade history - extracts your implicit trading rules, identifies your best and worst patterns, flags rule violations, and shows what your stats would look like if you only took your highest-probability setups.'),
('TRADE_JOURNAL_SHADOW_ANALYZING_BUTTON','en','Analyzing your trades…'),
('TRADE_JOURNAL_SHADOW_ANALYZE_BUTTON','en','Analyze My Trades'),
('TRADE_JOURNAL_SHADOW_RERUN_BUTTON','en','Re-run Analysis'),
('TRADE_JOURNAL_BIAS_PAGE_TITLE','en','Behavioral Bias Diagnostics'),
('TRADE_JOURNAL_BIAS_PAGE_SUBTITLE','en','Analyzes your trade history for the four most damaging trader biases - disposition effect, overtrading, momentum chasing, and anchoring - with specific examples from your actual trades and estimated P&L drag per bias.'),
('TRADE_JOURNAL_BIAS_ANALYZING_BUTTON','en','Analyzing your trades…'),
('TRADE_JOURNAL_BIAS_RUN_BUTTON','en','Run Bias Diagnostics'),
('TRADE_JOURNAL_BIAS_RERUN_BUTTON','en','Re-run Analysis'),
('TRADE_JOURNAL_THESIS_SECTION_ASSUMPTION_CHECK','en','Assumption Check'),
('TRADE_JOURNAL_THESIS_SECTION_HEALTH_SCORE','en','Thesis Health Score'),
('TRADE_JOURNAL_THESIS_SECTION_KEY_RISK','en','Key Risk'),
('TRADE_JOURNAL_THESIS_SECTION_RECOMMENDATION','en','Recommendation'),
('TRADE_JOURNAL_THESIS_PAGE_TITLE','en','Thesis Tracker'),
('TRADE_JOURNAL_THESIS_PAGE_SUBTITLE','en','Write a trade thesis with measurable assumptions. Grok checks whether your assumptions still hold and scores thesis health 1-10.'),
('TRADE_JOURNAL_THESIS_CANCEL_BUTTON','en','Cancel'),
('TRADE_JOURNAL_THESIS_NEW_BUTTON','en','+ New Thesis'),
('TRADE_JOURNAL_THESIS_FORM_TITLE','en','New Thesis'),
('TRADE_JOURNAL_THESIS_TICKER_PLACEHOLDER','en','Ticker (e.g. BTC)'),
('TRADE_JOURNAL_THESIS_DIRECTION_LONG','en','LONG'),
('TRADE_JOURNAL_THESIS_DIRECTION_SHORT','en','SHORT'),
('TRADE_JOURNAL_THESIS_TEXT_PLACEHOLDER','en','Your trade thesis - why are you taking this position? What is the setup?'),
('TRADE_JOURNAL_THESIS_ASSUMPTIONS_LABEL','en','Measurable Assumptions (3-5) - these get checked by Grok'),
('TRADE_JOURNAL_THESIS_ASSUMPTION_PLACEHOLDER','en','Assumption {n} - e.g. "BTC holds above $95k support"'),
('TRADE_JOURNAL_THESIS_ADD_ASSUMPTION_BUTTON','en','+ Add Assumption'),
('TRADE_JOURNAL_THESIS_REMOVE_LAST_BUTTON','en','Remove Last'),
('TRADE_JOURNAL_THESIS_SAVE_BUTTON','en','Save Thesis'),
('TRADE_JOURNAL_THESIS_EMPTY_STATE','en','No theses yet - click New Thesis to track your first position thesis.'),
('TRADE_JOURNAL_THESIS_ENTRY_DATE_LABEL','en','Entry: {date}'),
('TRADE_JOURNAL_THESIS_LAST_CHECKED_LABEL','en','Last checked: {date}'),
('TRADE_JOURNAL_THESIS_CHECKING_BUTTON','en','Checking…'),
('TRADE_JOURNAL_THESIS_RECHECK_BUTTON','en','Re-check Health'),
('TRADE_JOURNAL_THESIS_CHECK_HEALTH_BUTTON','en','Check Thesis Health'),
('TRADE_JOURNAL_THESIS_DELETE_BUTTON','en','Delete'),
('TRADE_JOURNAL_STATS_EMPTY_STATE','en','Close at least one trade to see stats'),
('TRADE_JOURNAL_STATS_RULE_COMPLIANCE_LABEL','en','Rule Compliance'),
('TRADE_JOURNAL_STATS_RULE_COMPLIANCE_DESC','en','{clean} of {total} closed trades followed all rules'),
('TRADE_JOURNAL_STATS_WIN_RATE_LABEL','en','Win Rate'),
('TRADE_JOURNAL_STATS_WIN_RATE_TOOLTIP','en','The share of your closed trades that finished in profit. On its own it can mislead - a low win rate is still profitable if your wins are bigger than your losses (see Avg R).'),
('TRADE_JOURNAL_STATS_TOTAL_PNL_LABEL','en','Total P&L'),
('TRADE_JOURNAL_STATS_AVG_R_LABEL','en','Avg R/Trade'),
('TRADE_JOURNAL_STATS_AVG_R_TOOLTIP','en','Your average result per trade in R - multiples of what you risked. +0.20R means each trade netted a fifth of your risk on average. Positive over many trades is the real proof of an edge.'),
('TRADE_JOURNAL_STATS_RECORD_LABEL','en','Record'),
('TRADE_JOURNAL_STATS_CURRENT_STREAK_LABEL','en','Current Streak'),
('TRADE_JOURNAL_STATS_BEST_WIN_STREAK_LABEL','en','Best Win Streak'),
('TRADE_JOURNAL_STATS_EQUITY_CURVE_LABEL','en','Equity Curve'),
('TRADE_JOURNAL_STATS_PERFORMANCE_BY_COIN_LABEL','en','Performance by Coin'),
('TRADE_JOURNAL_STATS_PERFORMANCE_BY_SETUP_LABEL','en','Performance by Setup'),
('TRADE_JOURNAL_STATS_TRADES_COUNT','en','{wins}/{total} trades'),
('TRADE_JOURNAL_AUTH_TITLE','en','Sign in to access your Journal'),
('TRADE_JOURNAL_AUTH_DESC','en','Your trade history, P&L stats, and setups are private to your account.'),
('TRADE_JOURNAL_LOADING_MESSAGE','en','Loading…')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
