-- ALERTS_* rows (app/alerts/page.tsx). Run once against BOTH lhq_labels
-- (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('ALERTS_SAVE_FAILED','en','Save failed'),
('ALERTS_COIN_CAP_OVER_MSG','en','You have {onCount} coins on, above the {cap}-coin limit - turn some off before adding another.'),
('ALERTS_COIN_CAP_REACHED_MSG','en','Limit reached ({cap}/{cap} coins) - turn one off to add another.'),
('ALERTS_ADD_ALERT_FAILED','en','Failed to add alert'),
('ALERTS_REMOVE_ALERT_FAILED','en','Failed to remove alert'),
('ALERTS_UNKNOWN_ERROR','en','Unknown error'),
('ALERTS_NETWORK_ERROR','en','Network error'),
('ALERTS_DETECT_FAILED','en','Could not detect. Send /start to the bot first.'),
('ALERTS_SERVER_ERROR','en','Server error {status}'),
('ALERTS_CHECK_REQUEST_FAILED','en','Request failed'),
('ALERTS_BOT_FALLBACK_NAME','en','LiquidityHQ Bot'),
('ALERTS_SECTION_TRADING_SIGNALS','en','Trading Signals'),
('ALERTS_EMA_SETUP_4H_TITLE','en','Entry Signal - EMA Ribbon Setup (4H)'),
('ALERTS_EMA_SETUP_4H_DESC','en','Potential LONG or SHORT entry: price pulls into the EMA 9–20 value zone with trend, ribbon spread, and funding aligned · includes stop loss and take profit levels · 6h cooldown'),
('ALERTS_EMA_SETUP_1H_TITLE','en','Entry Signal - EMA Ribbon Setup (1H)'),
('ALERTS_EMA_SETUP_1H_DESC','en','Same EMA ribbon value-zone setup, checked on the 1H chart · includes stop loss and take profit levels · 2h cooldown'),
('ALERTS_EMA_SETUP_30M_TITLE','en','Entry Signal - EMA Ribbon Setup (30M)'),
('ALERTS_EMA_SETUP_30M_DESC','en','Same EMA ribbon value-zone setup, checked on the 30M chart for faster-moving entries · includes stop loss and take profit levels · 1h cooldown'),
('ALERTS_EMA_SETUP_15M_TITLE','en','Entry Signal - EMA Ribbon Setup (15M)'),
('ALERTS_EMA_SETUP_15M_DESC','en','Same EMA ribbon value-zone setup, checked on the 15M chart for the fastest entries · includes stop loss and take profit levels · 30min cooldown'),
('ALERTS_SECTION_MOMENTUM','en','Momentum'),
('ALERTS_RSI_TITLE','en','RSI (1H)'),
('ALERTS_RSI_DESC','en','> 78 overbought · < 22 oversold · 4h cooldown'),
('ALERTS_RAPID_MOVES_TITLE','en','Rapid Moves'),
('ALERTS_RAPID_MOVES_DESC','en','±5% 1H candle · ±10% 4H candle · flash ±4% in 5 min · 30min–4h cooldowns'),
('ALERTS_SECTION_TREND','en','Trend'),
('ALERTS_EMA_CROSS_TITLE','en','200 EMA Cross (1H)'),
('ALERTS_EMA_CROSS_DESC','en','Price reclaims (bullish) or loses (bearish) the major moving average · 12h cooldown'),
('ALERTS_SECTION_FLOW','en','Flow'),
('ALERTS_WHALES_TITLE','en','Whale Trades'),
('ALERTS_WHALES_DESC','en','BTC >$5M · ETH >$2M · SOL >$1M · XRP/BNB >$750K · others >$500K · 30min cooldown'),
('ALERTS_OI_SPIKE_TITLE','en','Open Interest Spike ±15% / 1h'),
('ALERTS_OI_SPIKE_DESC','en','New money entering - big move building · 2h cooldown'),
('ALERTS_CVD_TITLE','en','CVD Divergence'),
('ALERTS_CVD_DESC','en','Bullish: price down but buyers absorbing · Bearish: price up but sellers dominate · 1h cooldown'),
('ALERTS_SQUEEZE_TITLE','en','Squeeze / Flush ≥ 70'),
('ALERTS_SQUEEZE_DESC','en','Crowd positioning extreme - squeeze score threshold hit · 4h cooldown'),
('ALERTS_DISTRIBUTION_TITLE','en','Distribution - Big Players Taking Profit'),
('ALERTS_DISTRIBUTION_DESC','en','Coin still up on the day but sellers hit into strength, open interest unwinds, whales lean out, retail keeps paying funding · fires at score ≥ 70 · 4h cooldown'),
('ALERTS_SECTION_NEWS_SENTIMENT','en','News & Sentiment'),
('ALERTS_NEWS_TITLE','en','Breaking News'),
('ALERTS_NEWS_DESC','en','Geopolitical / macro Finnhub headlines · 15min cooldown'),
('ALERTS_FEAR_GREED_TITLE','en','Fear & Greed Extremes'),
('ALERTS_FEAR_GREED_DESC','en','≤ 15 extreme fear · ≥ 85 extreme greed · 23h cooldown'),
('ALERTS_SENTIMENT_EXTREMES_TITLE','en','Sentiment Extremes'),
('ALERTS_SENTIMENT_EXTREMES_DESC','en','F&G + BTC funding + BTC L/S ratio all at extremes simultaneously · 4h cooldown'),
('ALERTS_SECTION_PRICE_SUMMARY','en','Price & Summary'),
('ALERTS_PRICE_LEVEL_TITLE','en','Price Level Alerts'),
('ALERTS_PRICE_LEVEL_DESC','en','Your saved price targets · fires once then deactivates'),
('ALERTS_DAILY_SUMMARY_TITLE','en','Daily {time} Summary'),
('ALERTS_DAILY_SUMMARY_DESC','en','FR snapshot + F&G + active price alerts + LiquidityAI outlook · once daily at {time}'),
('ALERTS_PAGE_TITLE','en','Telegram Alerts'),
('ALERTS_PAGE_SUBTITLE','en','Real-time push alerts to your phone - funding, momentum, whale flow, sentiment, and price levels'),
('ALERTS_CONNECT_TELEGRAM_TITLE','en','Connect Telegram'),
('ALERTS_LOCKED_FEATURE_DESC','en','Push alerts for funding rate extremes, RSI signals, open interest spikes, whale moves, and price levels - sent directly to Telegram.'),
('ALERTS_UPGRADE_GATE_FEATURE_LABEL','en','Telegram Alerts'),
('ALERTS_STATUS_CONNECTED','en','Connected'),
('ALERTS_STATUS_NOT_CONNECTED','en','Not connected'),
('ALERTS_CHAT_ID_LABEL','en','Chat ID:'),
('ALERTS_CHANGE_BUTTON','en','Change'),
('ALERTS_TEST_SENDING','en','Sending…'),
('ALERTS_TEST_SENT_OK','en','✓ Message sent!'),
('ALERTS_TEST_FAILED','en','✕ Failed'),
('ALERTS_SEND_TEST_BUTTON','en','Send Test Message'),
('ALERTS_WIZARD_INTRO','en','Get trading alerts straight to your phone. Takes 30 seconds.'),
('ALERTS_WEBHOOK_FAILED_WARNING','en','Bot webhook registration failed - the bot may not reply to /start. Try refreshing, or enter your Chat ID manually below.'),
('ALERTS_STEP1_TITLE','en','Open the bot on Telegram'),
('ALERTS_OPEN_BOT_BUTTON','en','Open {bot} →'),
('ALERTS_SEARCH_BOT_PRE','en','Search'),
('ALERTS_SEARCH_BOT_BOLD','en','LiquidityHQ'),
('ALERTS_SEARCH_BOT_POST','en','on Telegram'),
('ALERTS_STEP2_SEND_PRE','en','Send'),
('ALERTS_STEP2_SEND_POST','en','in the chat'),
('ALERTS_STEP2_HINT_PRE','en','The bot replies with your'),
('ALERTS_STEP2_HINT_BOLD','en','Chat ID'),
('ALERTS_STEP2_HINT_POST','en','- copy that number.'),
('ALERTS_STEP3_TITLE','en','Connect your Chat ID'),
('ALERTS_CHAT_ID_ARIA','en','Telegram Chat ID'),
('ALERTS_CHAT_ID_PLACEHOLDER','en','e.g. 123456789'),
('ALERTS_DETECT_DETECTING','en','↺ Detecting…'),
('ALERTS_DETECT_DETECTED','en','✓ Detected'),
('ALERTS_DETECT_AUTO','en','↺ Auto-detect'),
('ALERTS_DETECT_SUCCESS_MSG','en','✓ Chat ID detected and copied to clipboard'),
('ALERTS_SAVE_SAVING','en','Saving…'),
('ALERTS_SAVE_CONNECTED','en','✓ Connected!'),
('ALERTS_SAVE_CONNECT_BUTTON','en','Save & Connect'),
('ALERTS_AUTHGATE_TITLE','en','Sign in to use Price Alerts'),
('ALERTS_AUTHGATE_DESC','en','Save price targets and get Telegram pings when they''re hit. Free account required.'),
('ALERTS_PRICE_ALERTS_LABEL','en','Price Alerts'),
('ALERTS_COIN_ARIA','en','Coin'),
('ALERTS_DIRECTION_ARIA','en','Alert direction'),
('ALERTS_DIR_ABOVE_OPTION','en','↑ Above'),
('ALERTS_DIR_BELOW_OPTION','en','↓ Below'),
('ALERTS_PRICE_ARIA','en','Alert price'),
('ALERTS_PRICE_PLACEHOLDER','en','Price (e.g. 95000)'),
('ALERTS_NOTE_ARIA','en','Alert note'),
('ALERTS_NOTE_PLACEHOLDER','en','Note (optional)'),
('ALERTS_ADDING','en','Adding…'),
('ALERTS_ADD_ALERT_BUTTON','en','+ Add Alert'),
('ALERTS_LOADING','en','Loading…'),
('ALERTS_NO_PRICE_ALERTS_TITLE','en','No price alerts'),
('ALERTS_NO_PRICE_ALERTS_SUB','en','Add a coin, direction, and target above to get started.'),
('ALERTS_PRICE_ALERT_FOOTER','en','Fires once when price crosses your target → LiquidityAI analysis included → alert deactivates automatically.'),
('ALERTS_RECENTLY_FIRED_LABEL','en','Recently Fired'),
('ALERTS_REFRESH_BUTTON','en','↻ refresh'),
('ALERTS_NO_HISTORY_TITLE','en','No alerts fired yet'),
('ALERTS_NO_HISTORY_SUB','en','Alerts fire once when price crosses your target - history appears here.'),
('ALERTS_AGO_JUST_NOW','en','just now'),
('ALERTS_AGO_MINUTES','en','{n}m ago'),
('ALERTS_AGO_HOURS','en','{n}h ago'),
('ALERTS_AGO_DAYS','en','{n}d ago'),
('ALERTS_AUTO_REFRESH_NOTE','en','Auto-refreshes every 60s'),
('ALERTS_MANUAL_CHECK_LABEL','en','Manual Check'),
('ALERTS_CHECKING','en','Checking…'),
('ALERTS_CHECK_FAILED_RETRY','en','✕ Failed - retry?'),
('ALERTS_CHECK_NOW_BUTTON','en','Check Alerts Now'),
('ALERTS_NO_CONDITIONS_ACTIVE','en','✓ No conditions active right now.'),
('ALERTS_FIRED_LIST','en','Fired: {list}'),
('ALERTS_CHECK_TIMEOUT_FALLBACK','en','Request timed out - server may be cold starting. Try again in 30s.'),
('ALERTS_CONDITIONS_LABEL','en','Alert Conditions'),
('ALERTS_MUTE_HINT_PREFIX','en','Toggle off to mute.'),
('ALERTS_AI_BADGE_LABEL','en','AI'),
('ALERTS_MUTE_HINT_SUFFIX','en','= includes LiquidityAI analysis.'),
('ALERTS_MUTED_BADGE','en','MUTED'),
('ALERTS_UNMUTE_VERB','en','Unmute'),
('ALERTS_MUTE_VERB','en','Mute'),
('ALERTS_CONFLUENCE_ALERT_TITLE','en','Confluence Alert'),
('ALERTS_ALWAYS_ON_BADGE','en','ALWAYS ON'),
('ALERTS_CONFLUENCE_ALERT_DESC','en','2+ signals on the same coin in one run → single combined ping · LiquidityAI weighs all signals together'),
('ALERTS_SIGNAL_DIRECTION_LABEL','en','Signal Direction'),
('ALERTS_SIGNAL_DIRECTION_DESC','en','Silence one side of directional signals (entry setups, 200 EMA crosses, squeeze/flush warnings).'),
('ALERTS_DIR_LONG_LABEL','en','Long signals'),
('ALERTS_DIR_SHORT_LABEL','en','Short signals'),
('ALERTS_MUTED_SUFFIX','en','- muted'),
('ALERTS_COINS_OVER_LIMIT','en','Alert Coins - {onCount} on (limit {cap} - turn some off)'),
('ALERTS_COINS_COUNT','en','Alert Coins - {onCount}/{cap} on'),
('ALERTS_COIN_SELECTION_DESC','en','Tap a coin to stop all alerts for it, including which coins the EMA Ribbon Setup entry signals scan. Your saved price alerts are not affected.'),
('ALERTS_COIN_SEARCH_PLACEHOLDER','en','Search coins...'),
('ALERTS_COIN_SEARCH_ARIA','en','Search alert coins'),
('ALERTS_NO_COINS_MATCH','en','No coins match "{search}"'),
('ALERTS_COOLDOWN_FOOTER_NOTE','en','Cooldown timers may occasionally reset after routine maintenance - you might see a rare duplicate alert')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
