-- Wave 10: DryPowder, HigherTfMoveBadge, SessionCountdown, EconCalendarWidget,
-- ConfluenceScore, CycleDayCounter, StopLossZone, BtcRiskLevel.
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('DRY_POWDER_TOOLTIP','en','Tracks total stablecoin market cap (USDT, USDC, DAI, etc.) via DeFi Llama. Expansion means fresh capital entering crypto - bullish dry powder. Contraction means money leaving or already deployed. Grok provides the narrative context.'),
('DRY_POWDER_TITLE','en','Stablecoin Dry Powder'),
('DRY_POWDER_LOADING_SR','en','Loading stablecoin data…'),
('DRY_POWDER_SIGN_IN','en','Sign in to view dry powder analysis.'),
('DRY_POWDER_RETRY','en','Retry'),
('DRY_POWDER_30D_CHANGE','en','{pct} / 30d'),
('DRY_POWDER_90D_AGO','en','90d ago: {value} ({pct})'),
('DRY_POWDER_WATCH_LABEL','en','Watch: '),
('DRY_POWDER_REFRESH','en','Refresh (4h cache)'),
('HIGHER_TF_MOVE_BADGE_TOOLTIP','en','Informational only, not a filter - no signal is hidden based on this. 4h price moves this size sometimes precede sideways chop, sometimes continue trending; a fixed rule can''t reliably tell which in advance, so this just surfaces the context for you to judge.'),
('HIGHER_TF_MOVE_BADGE_PUMPED','en','pumped'),
('HIGHER_TF_MOVE_BADGE_DUMPED','en','dumped'),
('HIGHER_TF_MOVE_BADGE_MOVE_TEXT','en','4H {direction} {pct}% in ~24h'),
('HIGHER_TF_MOVE_BADGE_BUY','en','buy'),
('HIGHER_TF_MOVE_BADGE_SELL','en','sell'),
('HIGHER_TF_MOVE_BADGE_AGREES_TEXT','en',' - this {side} signal is chasing the same direction. Could be continuation, could be relief-rally chop.'),
('SESSION_COUNTDOWN_DEAD_ZONE','en','DEAD ZONE'),
('SESSION_COUNTDOWN_OFF_PEAK','en','OFF-PEAK'),
('SESSION_COUNTDOWN_CLOSES_IN','en','currently open - closes in'),
('SESSION_COUNTDOWN_STAY_OUT','en','Stay out - no follow-through'),
('SESSION_COUNTDOWN_NO_WINDOW','en','No high-probability window active'),
('SESSION_COUNTDOWN_NEXT','en','Next'),
('SESSION_COUNTDOWN_OPENS_IN','en','opens in'),
('SESSION_COUNTDOWN_HOLIDAY','en','Holiday'),
('SESSION_COUNTDOWN_HOLIDAY_ITEM','en','{region} closed - {name}'),
('ECON_CALENDAR_WIDGET_TITLE','en','Economic calendar'),
('ECON_CALENDAR_WIDGET_UPCOMING','en','Upcoming'),
('ECON_CALENDAR_WIDGET_LOAD_ERROR','en','Failed to load calendar'),
('ECON_CALENDAR_WIDGET_LOADING','en','Loading…'),
('ECON_CALENDAR_WIDGET_NO_EVENTS','en','No upcoming high-impact events'),
('ECON_CALENDAR_WIDGET_TODAY','en','Today'),
('ECON_CALENDAR_WIDGET_SEE_FULL','en','See full calendar'),
('CONFLUENCE_SCORE_VERDICT_STRONG_BULL','en','STRONG BULL CONFLUENCE'),
('CONFLUENCE_SCORE_VERDICT_LEANING_BULL','en','LEANING BULL'),
('CONFLUENCE_SCORE_VERDICT_MIXED','en','MIXED / NO EDGE'),
('CONFLUENCE_SCORE_VERDICT_LEANING_BEAR','en','LEANING BEAR'),
('CONFLUENCE_SCORE_VERDICT_STRONG_BEAR','en','STRONG BEAR CONFLUENCE'),
('CONFLUENCE_SCORE_TITLE','en','Confluence Score'),
('CONFLUENCE_SCORE_TOOLTIP','en','Weighted blend of the EMA Ribbon verdict, the 9-signal Order Flow bias, and 15m/1h/4h RSI alignment. For BTC, options gamma (GEX) acts as a regime modifier - in a long-gamma (ranging) market it dampens confidence since these trend signals are less reliable, and stays clear in a short-gamma (trending) market. Choppiness and an active RSI-divergence warning likewise reduce confidence without flipping direction. Macro/event risk is shown separately below - it''s not blended into this number since an FOMC print doesn''t change the technicals, only the risk of holding through it.'),
('CONFLUENCE_SCORE_SUBTITLE','en','{coin} · technical signals combined'),
('CONFLUENCE_SCORE_FACTOR_EMA_RIBBON','en','EMA Ribbon Strategy'),
('CONFLUENCE_SCORE_FACTOR_CHOPPINESS','en','Choppiness Index'),
('CONFLUENCE_SCORE_FACTOR_RSI_DIVERGENCE','en','RSI Divergence Warning'),
('CONFLUENCE_SCORE_PENALTY_ACTIVE','en','−{weight} confidence'),
('CONFLUENCE_SCORE_PENALTY_CLEAR','en','clear'),
('CYCLE_DAY_COUNTER_HEADER','en','Cycle Day'),
('CYCLE_DAY_COUNTER_ZONE_IN_PEAK','en','In peak zone'),
('CYCLE_DAY_COUNTER_ZONE_POST_PEAK','en','Post-peak zone'),
('CYCLE_DAY_COUNTER_ZONE_PRE_PEAK','en','Pre-peak zone'),
('CYCLE_DAY_COUNTER_DAYS_SINCE_LABEL','en','days since 4th halving'),
('CYCLE_DAY_COUNTER_HALVING_DATE_LABEL','en','Halving · Apr 20, 2024'),
('CYCLE_DAY_COUNTER_PEAK_ZONE_RANGE','en','Est. peak zone: Day {start}-{end}'),
('CYCLE_DAY_COUNTER_DAYS_TO_PEAK_LABEL','en','Days to peak zone'),
('CYCLE_DAY_COUNTER_DAYS_IN_PEAK_LABEL','en','Days in peak zone'),
('CYCLE_DAY_COUNTER_DAYS_PAST_PEAK_LABEL','en','Days past peak zone'),
('CYCLE_DAY_COUNTER_NEXT_HALVING_LABEL','en','Est. next halving'),
('CYCLE_DAY_COUNTER_NEXT_HALVING_VALUE','en','~{days}d (Mar 2028)'),
('CYCLE_DAY_COUNTER_HISTORICAL_CONTEXT_LABEL','en','Historical context'),
('CYCLE_DAY_COUNTER_HISTORICAL_CONTEXT_DESC','en','2020: peaked Day 546 · 2016: Day 526'),
('STOP_LOSS_ZONE_TITLE','en','Order Flow Setup'),
('STOP_LOSS_ZONE_INDICATOR_COUNT','en','{score}/{total} indicators'),
('STOP_LOSS_ZONE_NEUTRAL_HINT','en','Signals are split - wait for RSI and OI to agree on direction before entering.'),
('STOP_LOSS_ZONE_CONFLICT_PREFIX','en','AI analysis leans'),
('STOP_LOSS_ZONE_CONFLICT_SUFFIX','en','- indicators may not reflect recent catalysts. Check the AI result below.'),
('STOP_LOSS_ZONE_BULLISH','en','▲ Bullish'),
('STOP_LOSS_ZONE_BEARISH','en','▼ Bearish'),
('STOP_LOSS_ZONE_RR_LABEL','en','R:R'),
('STOP_LOSS_ZONE_REWARD','en','Reward'),
('STOP_LOSS_ZONE_RISK','en','Risk'),
('STOP_LOSS_ZONE_ROLE_SL','en','Stop Loss'),
('STOP_LOSS_ZONE_ROLE_TP','en','Take Profit'),
('STOP_LOSS_ZONE_ROLE_ENTRY','en','Entry'),
('STOP_LOSS_ZONE_CURRENT','en','current'),
('BTC_RISK_LEVEL_TITLE','en','BTC Risk Level'),
('BTC_RISK_LEVEL_TOOLTIP','en','Blends Fear & Greed, BTC''s daily RSI, and funding rate into one score for downside/dump risk specifically - not general volatility. Extreme Risk means longs are overheated and a pullback is more likely.'),
('BTC_RISK_LEVEL_FNG_LABEL','en','Fear & Greed'),
('BTC_RISK_LEVEL_RSI_LABEL','en','BTC RSI (Daily)'),
('BTC_RISK_LEVEL_FUNDING_LABEL','en','Funding Rate'),
('BTC_RISK_LEVEL_UNKNOWN','en','-'),
('BTC_RISK_LEVEL_LOW','en','Low Risk'),
('BTC_RISK_LEVEL_MODERATE','en','Moderate'),
('BTC_RISK_LEVEL_HIGH','en','High Risk'),
('BTC_RISK_LEVEL_EXTREME','en','Extreme Risk'),
('BTC_RISK_LEVEL_OUT_OF_100','en','/ 100'),
('BTC_RISK_LEVEL_BTC_DOM','en','BTC Dom {value}%'),
('BTC_RISK_LEVEL_BAR_LOW','en','Low'),
('BTC_RISK_LEVEL_BAR_MODERATE','en','Moderate'),
('BTC_RISK_LEVEL_BAR_HIGH','en','High'),
('BTC_RISK_LEVEL_BAR_EXTREME','en','Extreme'),
('BTC_RISK_LEVEL_EMPTY','en','Waiting for market data…')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
