-- ARENA_* rows part 2/2 (app/arena/page.tsx: AI Read hero, signal card,
-- workspace section, evidence/advanced + session history). Run once against
-- BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('ARENA_QUICK_SIGNIN_TITLE','en','Sign in to use Quick Analysis'),
('ARENA_QUICK_LOCAL_ONLY_TITLE','en','Uses local data only - no web search'),
('ARENA_WORKING','en','Working…'),
('ARENA_QUICK_RESEARCH_BUTTON','en','Quick Research'),
('ARENA_DEEP_SIGNIN_TITLE','en','Sign in to use Deep Analysis'),
('ARENA_DEEP_WEB_SEARCH_TITLE','en','Searches live web + X for catalysts'),
('ARENA_DEEP_RESEARCH_BUTTON','en','Deep Research'),
('ARENA_SET_ALERT_TITLE','en','Set a price alert for this coin'),
('ARENA_SET_ALERT_BUTTON','en','Set Alert'),
('ARENA_CHAT_PROMPT_WITH_RESULT','en','I just ran a full market read on {coin}: {signal} signal at {confidence}% confidence. Entry zone: {entryZone}. {reasoning} What should I watch out for, and are there any scenarios that would invalidate this signal?'),
('ARENA_CHAT_PROMPT_NO_RESULT','en','Give me a complete analysis of {coin}/USDT right now. What''s the trend, key levels, directional bias, best entry if any, and should I trade or wait?'),
('ARENA_ASK_LIQUIDITYAI_BUTTON','en','Ask LiquidityAI'),
('ARENA_ALERT_SET_SUCCESS','en','✓ Alert set for {coin}'),
('ARENA_VIEW_ALL_ALERTS_LINK','en','View all alerts →'),
('ARENA_ALERT_DIR_ABOVE','en','▲ Above'),
('ARENA_ALERT_DIR_BELOW','en','▼ Below'),
('ARENA_ALERT_TARGET_PRICE_LABEL','en','Target price'),
('ARENA_ALERT_PRICE_PLACEHOLDER','en','0.00'),
('ARENA_ALERT_LABEL_FIELD','en','Label'),
('ARENA_ALERT_LABEL_OPTIONAL_HINT','en','(optional)'),
('ARENA_ALERT_LABEL_PLACEHOLDER','en','e.g. breakout level'),
('ARENA_ALERT_SAVING','en','Saving…'),
('ARENA_ALERT_SET_CTA','en','Set Alert - {coin}'),
('ARENA_ALERT_CANCEL_BUTTON','en','Cancel'),
('ARENA_AUTH_NOTICE','en','Sign in to run Quick and Deep analysis - required to control API costs.'),
('ARENA_AUTH_SIGN_IN_LINK','en','Sign In →'),
('ARENA_VERDICT_LONG','en','Long'),
('ARENA_VERDICT_LEAN_LONG','en','Lean long'),
('ARENA_VERDICT_SHORT','en','Short'),
('ARENA_VERDICT_LEAN_SHORT','en','Lean short'),
('ARENA_VERDICT_WAIT','en','Wait'),
('ARENA_FRESHNESS_JUST_NOW','en','just now'),
('ARENA_FRESHNESS_MINUTES_AGO','en','{n}m ago'),
('ARENA_FRESHNESS_HOURS_AGO','en','{n}h ago'),
('ARENA_AI_READ_EYEBROW','en','AI Read · {coin}/USDT · {tf}'),
('ARENA_UPDATED_FRESHNESS','en','▲ Updated {freshness}'),
('ARENA_LEANING_BEARISH','en','Leaning bearish'),
('ARENA_LEANING_BULLISH','en','Leaning bullish'),
('ARENA_DIRECTIONAL_READ','en','Directional read'),
('ARENA_CONFIDENCE_LABEL','en','Confidence'),
('ARENA_OVERRIDE_NOTICE_PRE','en','Deep overrides Quick - web search found a catalyst that shifted the signal from'),
('ARENA_OVERRIDE_NOTICE_TO','en','to'),
('ARENA_OVERRIDE_NOTICE_POST','en','. See Catalysts below.'),
('ARENA_COPY_ENTRY_TITLE','en','Copy entry zone'),
('ARENA_ENTRY_ZONE_LABEL','en','Entry zone'),
('ARENA_COPIED_LONG','en','✓ Copied'),
('ARENA_COPY_STOP_TITLE','en','Copy stop'),
('ARENA_STOP_LABEL','en','Stop'),
('ARENA_COPIED_SHORT','en','✓'),
('ARENA_COPY_TARGET_TITLE','en','Copy target'),
('ARENA_TARGETS_LABEL','en','Targets'),
('ARENA_RR_LABEL','en','R : R'),
('ARENA_CONFIRMS_TO_SHORT','en','Confirms to SHORT:'),
('ARENA_CONFIRMS_TO_LONG','en','Confirms to LONG:'),
('ARENA_WAIT_FOR','en','Wait for:'),
('ARENA_LEANING_BEARISH_ARROW','en','↓ leaning bearish'),
('ARENA_LEANING_BULLISH_ARROW','en','↑ leaning bullish'),
('ARENA_RAID_HEADER','en','LIQUIDITY RAID - {setup}'),
('ARENA_RAID_TARGET_LABEL','en','Target'),
('ARENA_RAID_TRIGGER_LABEL','en','Trigger'),
('ARENA_ANTICHOP_TIP','en','Adds a stricter confirmation step: requires the EMA9/20 ribbon to clearly separate, price to close meaningfully past EMA50, and the move to hold for several candles before a marker confirms. Fewer, calmer-looking signals - but a 3-year backtest found this filter cuts a real edge down to a coin flip (1.13 profit factor raw vs 0.98 filtered). OFF (default) shows every raw cross immediately, including some that reverse fast, but has the better track record. ON trades quieter alerts for a worse actual outcome.'),
('ARENA_ANTICHOP_LABEL','en','Anti-Chop Filter'),
('ARENA_ANTICHOP_ON_HINT','en','Rejects tangled-ribbon and marginal EMA50 crosses'),
('ARENA_ANTICHOP_OFF_HINT','en','Raw EMA9/20 cross signals - no chop filtering'),
('ARENA_MARKET_SNAPSHOT_HEADER','en','Market snapshot'),
('ARENA_CONFLUENCE_GATE_TITLE','en','Confluence Score'),
('ARENA_CONFLUENCE_GATE_DESC','en','Order flow bias, absorption detection, and the combined confluence verdict are part of Pro.'),
('ARENA_CONFLUENCE_GATE_FEATURE_LABEL','en','The Confluence Score'),
('ARENA_DIST_WARN_PULLBACK','en','Potential pullback - pump is getting weaker'),
('ARENA_DIST_WARN_EARLY_WEAKNESS','en','Early weakness - watch for a pullback'),
('ARENA_BREAKDOWN_HIDE','en','Hide full breakdown'),
('ARENA_BREAKDOWN_SHOW','en','Full breakdown — multi-timeframe, order flow, patterns, reasoning'),
('ARENA_REASONING_CHART_TITLE','en','Chart'),
('ARENA_REASONING_PATTERNS_TITLE','en','Patterns'),
('ARENA_REASONING_TITLE','en','Reasoning'),
('ARENA_SESSION_HISTORY_HEADER','en','Session History'),
('ARENA_SESSION_HISTORY_CLEAR_BUTTON','en','Clear'),
('ARENA_HIST_BADGE_LONG','en','▲ LONG'),
('ARENA_HIST_BADGE_LEAN_LONG','en','↗ LEAN LONG'),
('ARENA_HIST_BADGE_SHORT','en','▼ SHORT'),
('ARENA_HIST_BADGE_LEAN_SHORT','en','↘ LEAN SHORT'),
('ARENA_HIST_BADGE_FLAT','en','- FLAT'),
('ARENA_HIST_CONFIDENCE_PCT','en','{pct}% confidence'),
('ARENA_HIST_ENTRY_ZONE_LABEL','en','Entry Zone'),
('ARENA_REASONING_LINK_FALLBACK','en','link')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
