-- OI_TREND_*, DASH_* rows (app/dashboard/page.tsx). Run once against BOTH
-- lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('OI_TREND_STRONG_UP_TXT','en','▲ New buyers opening'),
('OI_TREND_STRONG_UP_SUB','en','Open interest rising with price - real trend'),
('OI_TREND_STRONG_DOWN_TXT','en','▼ New sellers opening'),
('OI_TREND_STRONG_DOWN_SUB','en','Open interest rising as price falls - real dump'),
('OI_TREND_WEAK_UP_TXT','en','△ Short covering'),
('OI_TREND_WEAK_UP_SUB','en','Open interest falling as price rises - weak pump'),
('OI_TREND_WEAK_DOWN_TXT','en','▽ Long exits'),
('OI_TREND_WEAK_DOWN_SUB','en','Open interest falling with price - no panic'),
('DASH_PULSE_BTC_DOM_LABEL','en','BTC.D'),
('DASH_PULSE_ALT_LABEL','en','ALT'),
('DASH_PULSE_VOL_LABEL','en','VOL'),
('DASH_PULSE_VOL_NOTE','en','BTC regime'),
('DASH_PULSE_NOTE_BTC_LEADS','en','BTC leads'),
('DASH_PULSE_NOTE_ELEVATED','en','Elevated'),
('DASH_PULSE_NOTE_NORMAL','en','Normal'),
('DASH_PULSE_NOTE_ALT_SEASON','en','Alt season'),
('DASH_PULSE_NOTE_LEAN_ALTS','en','Lean alts'),
('DASH_PULSE_NOTE_BTC_SEASON','en','BTC season'),
('DASH_CASCADE_LABEL_LONG','en','LONG LIQ CASCADE'),
('DASH_CASCADE_LABEL_SHORT','en','SHORT LIQ CASCADE'),
('DASH_CASCADE_LABEL_NEUTRAL','en','LIQ CASCADE'),
('DASH_CASCADE_HINT_LONG','en','Longs wiped - short squeeze window open'),
('DASH_CASCADE_HINT_SHORT','en','Shorts flushed - continuation window open'),
('DASH_CASCADE_HINT_NEUTRAL','en','Multi-directional flush - vol spike imminent'),
('DASH_CASCADE_TITLE','en','{coin} - {label}'),
('DASH_CASCADE_SUB','en','{usd} in 60s · {hint}'),
('DASH_SIDEBAR_SIG_LONGS_OVERCROWDED','en','Longs overcrowded'),
('DASH_SIDEBAR_SIG_SHORTS_SQUEEZED','en','Shorts squeezed'),
('DASH_SIDEBAR_SIG_SMART_BUYERS','en','Smart buyers active'),
('DASH_SIDEBAR_SIG_SMART_SELLERS','en','Smart sellers active'),
('DASH_SIDEBAR_SIG_NEW_BUYERS','en','New buyers opening'),
('DASH_SIDEBAR_SIG_NEW_SELLERS','en','New sellers opening'),
('DASH_SIDEBAR_SIG_SHORTS_CLOSING','en','Shorts closing (weak up)'),
('DASH_SIDEBAR_SIG_BUYERS_PROFIT','en','Buyers taking profit'),
('DASH_SIDEBAR_SIG_FUNDING_VERY_HIGH','en','Funding very high'),
('DASH_SIDEBAR_SIG_FUNDING_SLIGHTLY_HIGH','en','Funding slightly high'),
('DASH_SIDEBAR_SIG_FUNDING_VERY_LOW','en','Funding very low'),
('DASH_SIDEBAR_SIG_FUNDING_SLIGHTLY_LOW','en','Funding slightly low'),
('DASH_SIDEBAR_SIG_FUNDING_NEUTRAL','en','Funding neutral'),
('DASH_SIDEBAR_MORE_COINS','en','▼ +{count} more coins'),
('DASH_SIDEBAR_STATUS_BACKUP','en','Backup'),
('DASH_SIDEBAR_STATUS_LIVE','en','Live'),
('DASH_SIDEBAR_STATUS_CONNECTING','en','Connecting'),
('DASH_EDGE_CB_LOADING','en','Loading…'),
('DASH_EDGE_CB_FOMO','en','US retail FOMO ▲'),
('DASH_EDGE_CB_MILD_BUY','en','Mild US buy pressure'),
('DASH_EDGE_CB_RETAIL_SELLING','en','US retail selling ▼'),
('DASH_EDGE_CB_MILD_SELL','en','Mild US sell pressure'),
('DASH_EDGE_CB_NEUTRAL','en','Neutral - no CB premium'),
('DASH_EDGE_VWAP_TIP','en','Volume Weighted Average Price - the average price across the day, weighted by how much was traded at each level. Price above VWAP signals buy-side control; below signals sellers are in charge.'),
('DASH_EDGE_VWAP_LABEL','en','VWAP - {coin}'),
('DASH_EDGE_VWAP_SUB_PREFIX','en','VWAP'),
('DASH_EDGE_VWAP_SIG_ABOVE','en','▲ Above VWAP - bullish'),
('DASH_EDGE_VWAP_SIG_BELOW','en','▼ Below VWAP - bearish'),
('DASH_EDGE_OI_TIP','en','Open Interest is the total number of live futures contracts. Rising OI + rising price = new longs entering (real conviction). Falling OI + rising price = shorts covering (weaker signal).'),
('DASH_EDGE_OI_LABEL','en','Open Interest - {coin}'),
('DASH_EDGE_OI_FLAT','en','Flat - no strong signal'),
('DASH_EDGE_FUNDING_TIP','en','The fee longs pay shorts every 8 hours to keep perpetual futures positions open. Strongly positive means too many people are leveraged long - whales often dump price to liquidate them and pocket the fee.'),
('DASH_EDGE_FUNDING_LABEL','en','Funding Rate - {coin}'),
('DASH_EDGE_SETUP_TIP','en','Squeeze setup score: funding rate (0–40 pts) + long/short ratio positioning (0–40 pts) + volume spike bonus (0–20 pts). LONG_LIQ = longs overcrowded, ripe for a dump. SHORT_SQ = shorts overcrowded, ripe for a pump.'),
('DASH_EDGE_SETUP_LABEL','en','Setup Scanner - {coin}'),
('DASH_EDGE_SETUP_SHORT_SQ','en','▲ Short squeeze setup'),
('DASH_EDGE_SETUP_LONG_LIQ','en','▼ Long liquidation risk'),
('DASH_EDGE_SETUP_BALANCED','en','Balanced positioning'),
('DASH_EDGE_CB_TIP','en','Coinbase price minus Binance price, as a %. Positive = US retail buyers are paying a premium (bullish signal). Negative = US retail selling at a discount (bearish signal).'),
('DASH_EDGE_CB_LABEL','en','CB Premium'),
('DASH_EDGE_OI1H_TIP','en','How much the total value of open futures positions changed in the last hour. A sharp rise means new money is entering aggressively; a sharp drop means mass liquidations or traders closing positions.'),
('DASH_EDGE_OI1H_LABEL','en','Open Interest 1h - {coin}'),
('DASH_COIN_SIGNALS_HEADER','en','Coin Signals - {coin}'),
('DASH_BEST_SETUP_TODAY_HEADER','en','Best Setup Today')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
