-- Wave 7: WhaleTradesFeed, SignalAccuracy, AccumulationTracker, DistributionTracker,
-- AlertOutcomes, AbsorptionDetector, SetupScanner, HypothesisTracker.
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('WHALE_TRADES_FEED_TOOLTIP','en','Live single trades over $50K on Binance futures. Large clusters of buys or sells often signal institutional positioning before smaller traders react.'),
('WHALE_TRADES_FEED_TITLE','en','Whale Trades'),
('WHALE_TRADES_FEED_ALL_MARKETS','en','All markets · >$50K ·'),
('WHALE_TRADES_FEED_MSG_COUNT','en','{count} msgs'),
('WHALE_TRADES_FEED_WAITING','en','waiting…'),
('WHALE_TRADES_FEED_STAT_BUYS','en','Whale Buys (1h)'),
('WHALE_TRADES_FEED_STAT_NET_FLOW','en','Net Flow'),
('WHALE_TRADES_FEED_STAT_SELLS','en','Whale Sells (1h)'),
('WHALE_TRADES_FEED_BIAS_NET_BUY','en','Whales net buying - institutional accumulation'),
('WHALE_TRADES_FEED_BIAS_NET_SELL','en','Whales net selling - institutional distribution'),
('WHALE_TRADES_FEED_BIAS_BALANCED','en','Balanced whale flow - watching both sides'),
('WHALE_TRADES_FEED_SR_CONNECTING','en','Connecting to live trade feed…'),
('WHALE_TRADES_FEED_SR_WATCHING','en','Watching for trades > $50K…'),
('WHALE_TRADES_FEED_BADGE_MEGA','en','MEGA'),
('WHALE_TRADES_FEED_BADGE_WHALE','en','WHALE'),
('SIGNAL_ACCURACY_TOOLTIP','en','Backtests each signal against real BTC 4H history: every time it fired in the past, did price move favorably within 12h and 24h? Win rate is the honest hit-rate, misses included - not a guarantee, a track record.'),
('SIGNAL_ACCURACY_TITLE','en','Signal Accuracy Tracker'),
('SIGNAL_ACCURACY_CANDLES_INFO','en','BTC · 4H · last {candles} candles'),
('SIGNAL_ACCURACY_CACHE_NOTE','en','10 min cache'),
('SIGNAL_ACCURACY_SR_COMPUTING','en','Computing signal accuracy…'),
('SIGNAL_ACCURACY_LOAD_ERROR','en','Failed to load:'),
('SIGNAL_ACCURACY_COL_SIGNAL','en','Signal'),
('SIGNAL_ACCURACY_COL_TF','en','TF'),
('SIGNAL_ACCURACY_COL_WIN_RATE_12H','en','Win Rate 12h'),
('SIGNAL_ACCURACY_COL_WIN_RATE_24H','en','Win Rate 24h'),
('SIGNAL_ACCURACY_COL_COUNT','en','Count'),
('SIGNAL_ACCURACY_TIP_WIN_RATE_12H','en','% of past firings where price moved favorably within 12 hours.'),
('SIGNAL_ACCURACY_TIP_WIN_RATE_24H','en','% of past firings where price moved favorably within 24 hours.'),
('SIGNAL_ACCURACY_TIP_COUNT','en','How many times this signal fired in the backtested window - low counts mean less statistical confidence.'),
('SIGNAL_ACCURACY_AVG_RETURN','en','avg {sign}{value}% at 24h'),
('SIGNAL_ACCURACY_FOOTER_NOTE','en','Win Rate = % of signals where price moved in the expected direction after 12h or 24h'),
('ACCUMULATION_TRACKER_TITLE','en','Accumulation Tracker'),
('ACCUMULATION_TRACKER_TOOLTIP','en','Scores every coin for stealth accumulation: price still flat while CVD shows absorption, taker buys dominate, open interest builds, whale positioning leans long, and funding stays calm (crowd not in yet). High score = smart money loading before the move.'),
('ACCUMULATION_TRACKER_SUBTITLE','en','quiet coins being loaded - before the pump'),
('ACCUMULATION_TRACKER_EMPTY','en','No stealth accumulation detected right now. Signals appear when a flat-priced coin shows CVD absorption, rising open interest, or heavy taker buying.'),
('DISTRIBUTION_TRACKER_TITLE','en','Distribution Tracker'),
('DISTRIBUTION_TRACKER_TOOLTIP','en','Scores every coin for profit-taking by big players: price still up on the day while CVD shows sellers into strength, open interest unwinds out of the rally, top traders lean out of longs, and retail keeps paying positive funding (buying what whales sell). High score = distribution phase - caution on new longs.'),
('DISTRIBUTION_TRACKER_SUBTITLE','en','winners being sold into - big players taking profit'),
('DISTRIBUTION_TRACKER_EMPTY_TITLE','en','No distribution detected'),
('DISTRIBUTION_TRACKER_EMPTY_SUB','en','Signals appear when a coin shows sellers into strength, OI unwinding, or whales leaning out.'),
('ALERT_OUTCOMES_TITLE','en','Alert Track Record'),
('ALERT_OUTCOMES_TOOLTIP','en','How this app''s own directional alerts actually performed: the signed price move by 24h after each alert fired, misses included - not a backtest, the real record. Only alert types with a clear implied direction are scored (squeeze, EMA cross, distribution, RSI, whale trades).'),
('ALERT_OUTCOMES_SUBTITLE','en','24h outcome · misses included'),
('ALERT_OUTCOMES_LOADING_SR','en','Loading…'),
('ALERT_OUTCOMES_EMPTY_TITLE','en','No resolved outcomes yet'),
('ALERT_OUTCOMES_EMPTY_SUB','en','Outcomes fill in ~24h after each squeeze, EMA cross, distribution, RSI, or whale alert fires.'),
('ALERT_OUTCOMES_RECENT_FIRES','en','Recent Fires'),
('ALERT_OUTCOMES_PENDING_LABEL','en','pending'),
('ALERT_OUTCOMES_RULE_SQUEEZE','en','Squeeze / Flush'),
('ALERT_OUTCOMES_RULE_EMA_CROSS','en','200 EMA Cross'),
('ALERT_OUTCOMES_RULE_DISTRIBUTION','en','Distribution'),
('ALERT_OUTCOMES_RULE_RSI','en','RSI Overbought/Oversold'),
('ALERT_OUTCOMES_RULE_WHALES','en','Whale Trades'),
('ABSORPTION_DETECTOR_LOADING_SR','en','Loading…'),
('ABSORPTION_DETECTOR_TITLE','en','Absorption Detector · 15M'),
('ABSORPTION_DETECTOR_FAILED','en','Failed'),
('ABSORPTION_DETECTOR_ACCUMULATION_BADGE','en','▲ ACCUMULATION'),
('ABSORPTION_DETECTOR_DISTRIBUTION_BADGE','en','▼ DISTRIBUTION'),
('ABSORPTION_DETECTOR_NO_SIGNAL','en','No Signal'),
('ABSORPTION_DETECTOR_LEVEL_LABEL','en','Level'),
('ABSORPTION_DETECTOR_MTF_BADGE','en','1H ✓'),
('ABSORPTION_DETECTOR_MTF_TEXT','en','Multi-timeframe confirmed - institutional activity'),
('ABSORPTION_DETECTOR_FOOTER','en','Accum = buyers absorbing sells (price should fall but holds) · Distrib = sellers absorbing buys · 15M + 1H'),
('SETUP_SCANNER_OI_NONE','en','Open Int -'),
('SETUP_SCANNER_OI_STRONG_UP','en','Open Int ↑↑'),
('SETUP_SCANNER_OI_WEAK_UP','en','Open Int ↑'),
('SETUP_SCANNER_OI_WEAK_DOWN','en','Open Int ↓'),
('SETUP_SCANNER_OI_STRONG_DOWN','en','Open Int ↓↓'),
('SETUP_SCANNER_CVD_NONE','en','CVD -'),
('SETUP_SCANNER_CVD_BULL','en','CVD ↑'),
('SETUP_SCANNER_CVD_BEAR','en','CVD ↓'),
('SETUP_SCANNER_TAKER_NONE','en','Tkr -'),
('SETUP_SCANNER_TAKER_VAL','en','Tkr {pct}%'),
('SETUP_SCANNER_RSI_VAL','en','RSI {v}'),
('SETUP_SCANNER_STAT_FUNDING','en','Funding'),
('SETUP_SCANNER_STAT_LONG_PCT','en','Long %'),
('SETUP_SCANNER_STAT_SHORT_PCT','en','Short %'),
('SETUP_SCANNER_STAT_VOL_RATIO','en','Vol ratio'),
('SETUP_SCANNER_STAT_RSI_1H','en','RSI 1h'),
('SETUP_SCANNER_STAT_RSI_4H','en','RSI 4h'),
('SETUP_SCANNER_NO_DATA','en','No data for {coin}'),
('SETUP_SCANNER_TITLE','en','Setup Scanner'),
('SETUP_SCANNER_SUBTITLE','en','All {count} coins ranked by squeeze risk · updates with live data'),
('SETUP_SCANNER_ALERT_LONG_LIQ','en','Long liquidation risk - score {score}'),
('SETUP_SCANNER_ALERT_SHORT_SQ','en','Short squeeze setup - score {score}'),
('SETUP_SCANNER_FILTER_ALL','en','All ({count})'),
('SETUP_SCANNER_FILTER_LONG_LIQ','en','Long Liq ({count})'),
('SETUP_SCANNER_FILTER_SHORT_SQ','en','Short Squeeze ({count})'),
('SETUP_SCANNER_FILTER_NEUTRAL','en','Neutral ({count})'),
('SETUP_SCANNER_STRONG_ONLY','en','Strong Setups Only'),
('SETUP_SCANNER_STRONG_ONLY_ACTIVE','en','Strong Setups Only - {count} coins'),
('SETUP_SCANNER_SEARCH_PLACEHOLDER','en','Search coins…'),
('SETUP_SCANNER_SEARCH_ARIA','en','Search coins'),
('SETUP_SCANNER_NO_MATCH_SEARCH','en','No coins match "{search}"'),
('SETUP_SCANNER_NO_MATCH_STRONG','en','No strong setups right now - try again later or turn off the filter'),
('SETUP_SCANNER_NO_MATCH_FILTER','en','No setups match this filter right now'),
('SETUP_SCANNER_LEGEND_TITLE','en','How the score works'),
('SETUP_SCANNER_LEGEND_LONG_LABEL','en','Long Liq Risk ↓'),
('SETUP_SCANNER_LEGEND_LONG_DESC','en','too many longs. Funding +, long% high, vol spike. Whales incentivised to dump.'),
('SETUP_SCANNER_LEGEND_SHORT_LABEL','en','Short Squeeze ↑'),
('SETUP_SCANNER_LEGEND_SHORT_DESC','en','too many shorts. Funding –, short% high, vol spike. Whales incentivised to pump.'),
('SETUP_SCANNER_LEGEND_BALANCED_LABEL','en','Balanced'),
('SETUP_SCANNER_LEGEND_BALANCED_DESC','en','no extreme positioning on either side. Sit out or trade structure.'),
('SETUP_SCANNER_LEGEND_FOOTER','en','Score 0–100: funding rate (0–40 pts) + long/short ratio (0–40 pts) + volume spike bonus (0–20 pts)'),
('HYPOTHESIS_TRACKER_SIGN_IN_PROMPT','en','Sign in to use the Research Hypothesis Tracker.'),
('HYPOTHESIS_TRACKER_TITLE','en','Research Hypotheses'),
('HYPOTHESIS_TRACKER_SUBTITLE','en','Track structured market theses with measurable criteria and evidence'),
('HYPOTHESIS_TRACKER_NEW_BUTTON','en','+ New Hypothesis'),
('HYPOTHESIS_TRACKER_CANCEL_BUTTON','en','✕ Cancel'),
('HYPOTHESIS_TRACKER_FORM_HEADING','en','New Hypothesis'),
('HYPOTHESIS_TRACKER_TITLE_FIELD_LABEL','en','Title'),
('HYPOTHESIS_TRACKER_TITLE_PLACEHOLDER','en','e.g. BTC enters accumulation phase below $60k'),
('HYPOTHESIS_TRACKER_THESIS_FIELD_LABEL','en','Thesis - What do you believe and why?'),
('HYPOTHESIS_TRACKER_THESIS_PLACEHOLDER','en','Describe your hypothesis in detail. Include your reasoning, the market context that supports it, and what price action or on-chain data you expect to see.'),
('HYPOTHESIS_TRACKER_CRITERIA_FIELD_LABEL','en','Acceptance Criteria - When is this confirmed?'),
('HYPOTHESIS_TRACKER_CRITERION_PLACEHOLDER','en','Criterion {n} - e.g. "BTC closes above $72k on weekly"'),
('HYPOTHESIS_TRACKER_ADD_CRITERION_BUTTON','en','+ Add criterion'),
('HYPOTHESIS_TRACKER_TARGET_DATE_LABEL','en','Target Date (optional)'),
('HYPOTHESIS_TRACKER_SAVE_ERROR_FALLBACK','en','Failed to save hypothesis'),
('HYPOTHESIS_TRACKER_NETWORK_ERROR','en','Network error - please try again'),
('HYPOTHESIS_TRACKER_DELETE_CONFIRM','en','Delete this hypothesis and all its evidence?'),
('HYPOTHESIS_TRACKER_SAVING','en','Saving…'),
('HYPOTHESIS_TRACKER_SAVE_BUTTON','en','Save Hypothesis'),
('HYPOTHESIS_TRACKER_LOADING','en','Loading…'),
('HYPOTHESIS_TRACKER_EMPTY_STATE','en','No hypotheses yet. Click "New Hypothesis" to track your first market thesis.'),
('HYPOTHESIS_TRACKER_STATUS_ACTIVE','en','Active'),
('HYPOTHESIS_TRACKER_STATUS_CONFIRMED','en','Confirmed'),
('HYPOTHESIS_TRACKER_STATUS_DISCONFIRMED','en','Disconfirmed'),
('HYPOTHESIS_TRACKER_STATUS_EXPIRED','en','Expired'),
('HYPOTHESIS_TRACKER_TARGET_DATE_DISPLAY','en','Target: {date}'),
('HYPOTHESIS_TRACKER_LAST_ANALYSIS','en','Last analysis: {date}'),
('HYPOTHESIS_TRACKER_CRITERIA_HEADING','en','Acceptance Criteria'),
('HYPOTHESIS_TRACKER_GROK_VERDICT_PREFIX','en','GROK: {verdict}'),
('HYPOTHESIS_TRACKER_NEXT_CHECK_LABEL','en','Next check:'),
('HYPOTHESIS_TRACKER_ANALYZING','en','Grok is analyzing evidence…'),
('HYPOTHESIS_TRACKER_RERUN_ANALYSIS_BUTTON','en','↻ Re-run Grok Analysis'),
('HYPOTHESIS_TRACKER_RUN_ANALYSIS_BUTTON','en','Run Grok Analysis'),
('HYPOTHESIS_TRACKER_EVIDENCE_HEADING','en','Evidence ({count})'),
('HYPOTHESIS_TRACKER_NO_EVIDENCE','en','No evidence logged yet. Add observations below.'),
('HYPOTHESIS_TRACKER_DELETE_EVIDENCE_TOOLTIP','en','Delete evidence'),
('HYPOTHESIS_TRACKER_ADD_EVIDENCE_HEADING','en','Add Evidence'),
('HYPOTHESIS_TRACKER_EV_SUPPORTING','en','Supporting'),
('HYPOTHESIS_TRACKER_EV_AGAINST','en','Against'),
('HYPOTHESIS_TRACKER_EV_NEUTRAL','en','Neutral'),
('HYPOTHESIS_TRACKER_EVIDENCE_PLACEHOLDER','en','Describe the evidence or observation…'),
('HYPOTHESIS_TRACKER_SOURCE_PLACEHOLDER','en','Source (optional - e.g. Glassnode, X/Twitter, price action)'),
('HYPOTHESIS_TRACKER_ADD_EVIDENCE_BUTTON','en','Add Evidence'),
('HYPOTHESIS_TRACKER_STATUS_LABEL','en','Status:'),
('HYPOTHESIS_TRACKER_DELETE_BUTTON','en','Delete')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
