-- Wave 8: MultiTFAlignment, CoinHeatmap, MultiTFSqueezeView, DrawdownChart, CycleChart, GexTable.
-- Sparkline / Sparkline24h have zero hardcoded text (pure SVG renderers) - not part of this wave.
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('MULTI_TF_ALIGNMENT_TOOLTIP','en','Checks RSI(14) across three timeframes (15m = short-term momentum, 1h = medium, 4h = trend). When 2+ timeframes agree, the bias is meaningful. RSI above 57 = bullish zone, below 43 = bearish zone.'),
('MULTI_TF_ALIGNMENT_TITLE','en','Multi-Timeframe Alignment'),
('MULTI_TF_ALIGNMENT_SUBTITLE','en','{coin} RSI direction - 15m · 1h · 4h'),
('MULTI_TF_ALIGNMENT_COL_TF','en','TF'),
('MULTI_TF_ALIGNMENT_COL_RSI','en','RSI(14)'),
('MULTI_TF_ALIGNMENT_COL_VAL','en','VAL'),
('MULTI_TF_ALIGNMENT_COL_BIAS','en','BIAS'),
('MULTI_TF_ALIGNMENT_BIAS_BULLISH','en','Bullish'),
('MULTI_TF_ALIGNMENT_BIAS_BEARISH','en','Bearish'),
('MULTI_TF_ALIGNMENT_BIAS_NEUTRAL','en','Neutral'),
('MULTI_TF_ALIGNMENT_VERDICT_BULLISH','en','▲ Bullish'),
('MULTI_TF_ALIGNMENT_VERDICT_BEARISH','en','▼ Bearish'),
('MULTI_TF_ALIGNMENT_VERDICT_CONFLICTING','en','Conflicting'),
('MULTI_TF_ALIGNMENT_VERDICT_MIXED','en','Mixed Signals'),
('MULTI_TF_ALIGNMENT_FOOTER_BULLISH','en','RSI aligned bullish across timeframes. Momentum favors longs.'),
('MULTI_TF_ALIGNMENT_FOOTER_BEARISH','en','RSI aligned bearish across timeframes. Momentum favors shorts.'),
('MULTI_TF_ALIGNMENT_FOOTER_CONFLICTING','en','Higher and lower timeframes disagree. Stay out or reduce size - no clear edge.'),
('MULTI_TF_ALIGNMENT_FOOTER_MIXED','en','No clear directional bias across timeframes. Wait for RSI to pick a side.'),
('COIN_HEATMAP_TOOLTIP','en','Every tracked coin''s 24h price change, sized and colored by move. Green = up, red = down - a quick scan to spot which coins are leading or lagging the market right now.'),
('COIN_HEATMAP_TITLE','en','Market Heatmap · 24 Hour'),
('COIN_HEATMAP_CAT_ALL','en','All'),
('COIN_HEATMAP_CAT_MAJORS','en','Majors'),
('COIN_HEATMAP_CAT_ALTS','en','Alts'),
('COIN_HEATMAP_CAT_DEFI','en','DeFi/AI'),
('COIN_HEATMAP_CAT_MEME','en','Meme'),
('COIN_HEATMAP_SCALE_LABEL','en','Scale:'),
('MULTI_TF_SQUEEZE_VIEW_TITLE','en','Multi-Timeframe Squeeze Scanner'),
('MULTI_TF_SQUEEZE_VIEW_TOOLTIP','en','Checks RSI (amplified by funding rate and long/short ratio) on each timeframe for every coin. When multiple timeframes agree - all showing squeeze or all showing flush - that confluence is a stronger signal than any single timeframe alone.'),
('MULTI_TF_SQUEEZE_VIEW_SQUEEZE_BADGE','en','↑ {count} squeeze'),
('MULTI_TF_SQUEEZE_VIEW_FLUSH_BADGE','en','↓ {count} flush'),
('MULTI_TF_SQUEEZE_VIEW_COL_COIN','en','Coin'),
('MULTI_TF_SQUEEZE_VIEW_TF_15M','en','15 Min'),
('MULTI_TF_SQUEEZE_VIEW_TF_1H','en','1 Hour'),
('MULTI_TF_SQUEEZE_VIEW_TF_4H','en','4 Hour'),
('MULTI_TF_SQUEEZE_VIEW_TF_1D','en','1 Day'),
('MULTI_TF_SQUEEZE_VIEW_COL_SQUEEZE','en','Squeeze'),
('MULTI_TF_SQUEEZE_VIEW_SEARCH_PLACEHOLDER','en','Search coins…'),
('MULTI_TF_SQUEEZE_VIEW_CLEAR_SEARCH_ARIA','en','Clear search'),
('MULTI_TF_SQUEEZE_VIEW_NO_MATCH','en','No coins match "{search}"'),
('MULTI_TF_SQUEEZE_VIEW_SHOW_LESS','en','Show less ▲'),
('MULTI_TF_SQUEEZE_VIEW_SHOW_ALL','en','Show all {count} coins ▼'),
('MULTI_TF_SQUEEZE_VIEW_LEGEND_SQUEEZE','en','↑ Squeeze = shorts overcrowded, bounce likely'),
('MULTI_TF_SQUEEZE_VIEW_LEGEND_FLUSH','en','↓ Flush = longs overcrowded, drop likely'),
('MULTI_TF_SQUEEZE_VIEW_LEGEND_FORMULA','en','RSI + Funding Rate + L/S ratio'),
('DRAWDOWN_CHART_TITLE','en','Drawdown from All-Time High'),
('DRAWDOWN_CHART_TOOLTIP','en','How far each coin sits below its all-time high price, worst first. A deep drawdown means a coin needs a huge rally just to recover - useful context before sizing a long.'),
('DRAWDOWN_CHART_NEAR_ATH_BADGE','en','{count} near ATH'),
('DRAWDOWN_CHART_SOURCE','en','via CoinGecko'),
('DRAWDOWN_CHART_LOADING_SR','en','Loading ATH data…'),
('DRAWDOWN_CHART_ERROR','en','Failed to load ATH data · {error}'),
('DRAWDOWN_CHART_EMPTY','en','No drawdown data available.'),
('DRAWDOWN_CHART_ATH_PRICE','en','→ ATH {price}'),
('DRAWDOWN_CHART_LEGEND_UNDER_20','en','< 20% down'),
('DRAWDOWN_CHART_LEGEND_20_40','en','20-40%'),
('DRAWDOWN_CHART_LEGEND_40_60','en','40-60%'),
('DRAWDOWN_CHART_LEGEND_60_80','en','60-80%'),
('DRAWDOWN_CHART_LEGEND_OVER_80','en','> 80%'),
('CYCLE_CHART_LEGEND_2016','en','2016 Cycle'),
('CYCLE_CHART_LEGEND_2020','en','2020 Cycle'),
('CYCLE_CHART_LEGEND_2024','en','2024 Cycle (current)'),
('CYCLE_CHART_TITLE','en','Cycle Comparison · Days Since Halving'),
('CYCLE_CHART_CURRENT_DAY','en','Day {day} of 2024 cycle'),
('CYCLE_CHART_LOADING_SR','en','Loading cycle data…'),
('CYCLE_CHART_LOAD_ERROR','en','Failed to load: {err}'),
('CYCLE_CHART_FOOTER_YAXIS','en','Y axis: price multiple from halving day (log scale)'),
('CYCLE_CHART_FOOTER_SOURCE','en','2024 via Bybit · 1h cache'),
('GEX_TABLE_TITLE','en','BTC Options Market Pressure'),
('GEX_TABLE_TITLE_SUFFIX','en','(GEX)'),
('GEX_TABLE_NET_LABEL','en','{value} net'),
('GEX_TABLE_FETCHING_SR','en','Fetching…'),
('GEX_TABLE_MAX_PAIN_LABEL','en','Max pain: ${price}'),
('GEX_TABLE_MAX_PAIN_DESC','en','(the price where the most option bets lose - BTC often drifts toward it as expiry nears)'),
('GEX_TABLE_SUBTITLE','en','Where the big Bitcoin options bets sit - and whether they''re calming price down (range) or fueling it (trend). Use it to decide: fade the moves, or follow them.'),
('GEX_TABLE_CALCULATING_SR','en','Calculating from Deribit options chain…'),
('GEX_TABLE_LEAN_ABOVE_FLIP','en','price is holding above the ${flip} flip line (the calmer side)'),
('GEX_TABLE_LEAN_BELOW_FLIP','en','price has slipped below the ${flip} flip line (the jumpier side)'),
('GEX_TABLE_LEAN_MAGNET_ABOVE','en','the strongest magnet (${strike}K) sits above price, pulling up'),
('GEX_TABLE_LEAN_MAGNET_BELOW','en','the strongest magnet (${strike}K) sits below price, pulling down'),
('GEX_TABLE_LEAN_BULLISH','en','↑ BULLISH LEAN'),
('GEX_TABLE_LEAN_BEARISH','en','↓ BEARISH LEAN'),
('GEX_TABLE_LEAN_NEUTRAL','en','→ NEUTRAL'),
('GEX_TABLE_REGIME_RANGING','en','RANGING'),
('GEX_TABLE_REGIME_TRENDING','en','TRENDING'),
('GEX_TABLE_REGIME_DESC_RANGING','en','the market likes to chop and bounce right now - fade the extremes, don''t chase breakouts'),
('GEX_TABLE_REGIME_DESC_TRENDING','en','moves tend to keep running right now - follow the momentum, don''t try to catch the top or bottom'),
('GEX_TABLE_COL_PRICE_LEVEL','en','Price level'),
('GEX_TABLE_COL_WALL_STRENGTH','en','Wall strength (bigger = stronger magnet)'),
('GEX_TABLE_COL_SIZE','en','$ size'),
('GEX_TABLE_CURRENT_PRICE_MARKER','en','← current price'),
('GEX_TABLE_FLIP_LINE_LABEL','en','Flip line:'),
('GEX_TABLE_FLIP_LINE_DESC','en','- if BTC breaks {dir} this, the calming effect switches off and big, fast moves get more likely'),
('GEX_TABLE_DIR_BELOW','en','below'),
('GEX_TABLE_DIR_ABOVE','en','above'),
('GEX_TABLE_STRONGEST_MAGNET_LABEL','en','Strongest magnet:'),
('GEX_TABLE_STRONGEST_MAGNET_DESC','en','- the price level BTC tends to get pulled toward')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
