-- NAV_* rows for components/NavDrawer.tsx (already migrated in b8cf12d, keys
-- already in lib/labelKeys.ts, but seed rows were never added). Run once
-- against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('NAV_DASHBOARD','en','Dashboard'),
('NAV_ARENA','en','Arena'),
('NAV_BRIEFING','en','Briefing'),
('NAV_MARKETS','en','Markets'),
('NAV_LIVE_PRICES','en','Live Prices'),
('NAV_SETUP_SCANNER','en','Setup Scanner'),
('NAV_LIQUIDATION_MAP','en','Liquidation Map'),
('NAV_FR_HISTORY','en','FR History'),
('NAV_CORRELATION','en','Correlation'),
('NAV_BACKTEST','en','Backtest'),
('NAV_LIVE_TRACKING','en','Live Tracking'),
('NAV_JOURNAL','en','Journal'),
('NAV_RESEARCH','en','Research'),
('NAV_CALCULATORS','en','Calculators'),
('NAV_POSITION_SIZER','en','Position Sizer'),
('NAV_ECON_CALENDAR','en','Economic Calendar'),
('NAV_ALERTS','en','Alerts'),
('NAV_BEST_HOURS','en','Best Hours'),
('NAV_PLAYBOOK','en','Playbook'),
('NAV_NEWS','en','News'),
('NAV_GLOSSARY','en','Glossary'),
('NAV_SETTINGS_LABEL','en','Settings'),
('NAV_ABOUT','en','About'),
('NAV_HOME','en','Home'),
('NAV_MORE','en','More'),
('NAV_DROPDOWN_SCANNERS','en','Scanners'),
('NAV_DROPDOWN_TOOLS','en','Tools'),
('NAV_SECTION_MAIN','en','Main'),
('NAV_SECTION_ANALYSIS','en','Analysis'),
('NAV_SECTION_RESEARCH','en','Research'),
('NAV_SECTION_MY_TOOLS','en','My Tools'),
('NAV_SECTION_ACCOUNT','en','Account'),
('NAV_SIGN_IN','en','Sign In'),
('NAV_SIGN_OUT_MENU','en','Sign out'),
('NAV_SIGN_OUT_DRAWER','en','Sign Out'),
('NAV_SEARCH_PLACEHOLDER','en','Search pages'),
('NAV_NO_MATCHES','en','No pages match "{query}"'),
('NAV_VIEW_USAGE','en','LiquidityAI - view usage')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
