-- LIVE_TRACKING_*, LIQ_* rows (app/live-tracking/page.tsx, app/liq/page.tsx).
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('LIVE_TRACKING_ERROR_SUPABASE_NOT_CONFIGURED','en','Supabase not configured'),
('LIVE_TRACKING_TITLE','en','Live Outcome Tracking'),
('LIVE_TRACKING_SUBTITLE','en','Real EMA Ribbon signals (default filter, majors, 1h + 4h) as they actually fired - not a replay. Complements the historical backtest by validating the strategy against current market conditions.'),
('LIVE_TRACKING_LOADING','en','Loading…'),
('LIVE_TRACKING_ERROR','en','Error: {message}'),
('LIVE_TRACKING_EMPTY_TITLE','en','No signals logged yet'),
('LIVE_TRACKING_EMPTY_SUB','en','This page populates as the live tracker detects and resolves real EMA Ribbon signals over time.'),
('LIVE_TRACKING_LIVE_SIDECARD_TITLE','en','LIVE (ANTI-CHOP ON)'),
('LIVE_TRACKING_PER_COIN_BREAKDOWN','en','Per-Coin Breakdown'),
('LIVE_TRACKING_TABLE_COIN','en','Coin'),
('LIVE_TRACKING_TABLE_TRADES','en','Trades'),
('LIVE_TRACKING_TABLE_WIN_RATE','en','Win Rate'),
('LIVE_TRACKING_TIP_AVG_R','en','R = risk multiple. +1R means the trade won exactly what was risked (distance to stop-loss); +2R means it won double. Avg R across all trades tells you if wins are outsized enough to cover the losses.'),
('LIVE_TRACKING_TABLE_AVG_R','en','Avg R'),
('LIVE_TRACKING_TIP_PROFIT_FACTOR','en','Total profit from winning trades divided by total loss from losing trades. Above 1.0 means the strategy is net profitable over this sample; below 1.0 means it''s losing money even if the win rate looks decent.'),
('LIVE_TRACKING_TABLE_PROFIT_FACTOR','en','Profit Factor'),
('LIVE_TRACKING_RECENT_SIGNALS','en','Recent Signals'),
('LIVE_TRACKING_TABLE_TF','en','TF'),
('LIVE_TRACKING_TABLE_DIR','en','Dir'),
('LIVE_TRACKING_TABLE_ENTRY','en','Entry'),
('LIVE_TRACKING_TABLE_SIGNAL_TIME','en','Signal Time'),
('LIVE_TRACKING_TABLE_STATUS','en','Status'),
('LIVE_TRACKING_STATUS_WIN','en','WIN ({multiple})'),
('LIVE_TRACKING_STATUS_LOSS','en','LOSS (-1R)'),
('LIVE_TRACKING_STATUS_OPEN','en','OPEN'),
('LIQ_RANGE_LABEL_12H','en','12h'),
('LIQ_RANGE_LABEL_24H','en','24h'),
('LIQ_RANGE_LABEL_48H','en','48h'),
('LIQ_RANGE_LABEL_3D','en','3 days'),
('LIQ_RANGE_LABEL_1W','en','1 week'),
('LIQ_RANGE_HINT_12H','en','Short-term moves · showing clusters within ±5% of current price'),
('LIQ_RANGE_HINT_24H','en','Day trade range · showing clusters within ±10% of current price'),
('LIQ_RANGE_HINT_48H','en','2-day swing range · showing clusters within ±13% of current price'),
('LIQ_RANGE_HINT_3D','en','Multi-day swing range · showing clusters within ±25% of current price'),
('LIQ_RANGE_HINT_1W','en','Full week range · showing all clusters within ±50% of current price'),
('LIQ_CLUSTERS_BUILDING','en','Real cluster data building from live Binance + Bybit feeds - takes a few minutes on first load.'),
('LIQ_CLUSTERS_TITLE','en','Real Liquidation Clusters'),
('LIQ_CLUSTERS_LIVE_BADGE','en','LIVE DATA'),
('LIQ_CLUSTERS_WINDOW_LABEL','en','24h window · Binance + Bybit'),
('LIQ_CLUSTERS_COL_PRICE','en','Price'),
('LIQ_CLUSTERS_COL_VOLUME','en','Volume (longs red · shorts green)'),
('LIQ_CLUSTERS_COL_TOTAL','en','Total'),
('LIQ_CLUSTERS_ABOVE','en','↑ above'),
('LIQ_CLUSTERS_BELOW','en','↓ below'),
('LIQ_CLUSTERS_DOM_LONG','en','L'),
('LIQ_CLUSTERS_DOM_SHORT','en','S'),
('LIQ_CLUSTERS_FOOTER_LEGEND','en','Red bars = long liquidations at that price · Green bars = short liquidations · L/S = dominant side'),
('LIQ_BIAS_LONG_HEAVY','en','Long-heavy'),
('LIQ_BIAS_LONG_HEAVY_SUB','en','More trapped longs below - larger traders may push price down to trigger them'),
('LIQ_BIAS_SHORT_HEAVY','en','Short-heavy'),
('LIQ_BIAS_SHORT_HEAVY_SUB','en','More trapped shorts above - larger traders may push price up to trigger them'),
('LIQ_BIAS_BALANCED','en','Balanced'),
('LIQ_BIAS_BALANCED_SUB','en','Roughly equal liquidation pressure on both sides - no strong directional lean'),
('LIQ_TITLE','en','Liquidation Map'),
('LIQ_SUBTITLE','en','Estimated liquidation zones · nearest dense cluster = price magnet'),
('LIQ_COIN_COUNT','en','{count} coins'),
('LIQ_LOADING_SR','en','Loading {coin}…'),
('LIQ_NO_OI_DATA','en','No open interest data for {coin}'),
('LIQ_STAT_LONG_ACCOUNTS','en','Long accounts'),
('LIQ_STAT_BYBIT_PERIOD','en','Bybit · {period}'),
('LIQ_STAT_BINANCE_PERIOD','en','Binance · {period}'),
('LIQ_STAT_OPEN_INTEREST','en','Open Interest'),
('LIQ_STAT_ZONES_IN_WINDOW','en','{count}/17 zones in window'),
('LIQ_STAT_SHORT_ACCOUNTS','en','Short accounts'),
('LIQ_DELTA_NET_LONGS','en','Net longs liquidated'),
('LIQ_DELTA_NET_SHORTS','en','Net shorts liquidated'),
('LIQ_DELTA_BALANCED','en','Balanced'),
('LIQ_DELTA_SUMMARY','en','{netText} in the last 15m - Longs {longUsd} · Shorts {shortUsd}'),
('LIQ_DELTA_WARMING_UP','en','Warming up - waiting for enough liquidation volume in the last 15m.'),
('LIQ_DELTA_UNAVAILABLE','en','Liquidation delta unavailable for {coin} - tracked for {coins} only.'),
('LIQ_WHALE_TITLE','en','Whale Positioning'),
('LIQ_WHALE_BADGE_LONG','en','Whale Long'),
('LIQ_WHALE_BADGE_SHORT','en','Whale Short'),
('LIQ_WHALE_SOURCE_LABEL','en','Binance top traders · position-weighted · {period}'),
('LIQ_WHALE_LONG_SUFFIX','en','whale long'),
('LIQ_WHALE_SHORT_SUFFIX','en','whale short'),
('LIQ_WHALE_LONG_SQUEEZE_TITLE','en','Long squeeze setup.'),
('LIQ_WHALE_LONG_SQUEEZE_BODY','en','Retail is {retailPct}% long but whales are positioned {whalePct}% short. Whales have the money to push price down and force-close retail longs.'),
('LIQ_WHALE_SHORT_SQUEEZE_TITLE','en','Short squeeze setup.'),
('LIQ_WHALE_SHORT_SQUEEZE_BODY','en','Retail is {retailPct}% short but whales are positioned {whalePct}% long. Whales have the money to push price up and force-close retail shorts.'),
('LIQ_HEATMAP_SHORT_HEADER','en','↑ Short squeeze zones'),
('LIQ_HEATMAP_SHORT_SUB','en','price pumps, shorts get force-closed · {range}'),
('LIQ_HEATMAP_SHORT_ARIA','en','Short squeeze liquidation zones'),
('LIQ_HEATMAP_COL_PRICE','en','Price'),
('LIQ_HEATMAP_COL_PCT_AWAY','en','% Away'),
('LIQ_HEATMAP_COL_LEV_TITLE','en','Leverage'),
('LIQ_HEATMAP_COL_LEV_ABBR','en','Lev.'),
('LIQ_HEATMAP_COL_DENSITY','en','Relative density (model)'),
('LIQ_HEATMAP_COL_EST_USD','en','Est. USD'),
('LIQ_HEATMAP_LIVE_TAG','en','LIVE'),
('LIQ_HEATMAP_OI_LABEL','en','{amount} Open Interest'),
('LIQ_HEATMAP_LONG_HEADER','en','↓ Long liquidation zones'),
('LIQ_HEATMAP_LONG_SUB','en','price drops, longs get force-closed · {range}'),
('LIQ_HEATMAP_LONG_ARIA','en','Long liquidation zones'),
('LIQ_LEGEND_TITLE','en','How to read this'),
('LIQ_LEGEND_SHORT_BOLD','en','Short Squeeze Zones'),
('LIQ_LEGEND_SHORT_TEXT','en','price levels above current price where modeled short positions get force-closed. Larger traders push price UP into these to trigger them.'),
('LIQ_LEGEND_LONG_BOLD','en','Long Liquidation Zones'),
('LIQ_LEGEND_LONG_TEXT','en','price levels below current price where modeled long positions get force-closed. Larger traders dump price DOWN into these.'),
('LIQ_LEGEND_MAGNET_BOLD','en','Magnet'),
('LIQ_LEGEND_MAGNET_TEXT','en','the largest estimated cluster in the selected window. The most likely price target for the next big move.'),
('LIQ_DISCLAIMER','en','Model only - price levels are mathematically correct (1/leverage), bar widths and USD amounts show relative density across tiers modeled from open interest.')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
