-- HOURS_* rows (app/hours/page.tsx). Run once against BOTH lhq_labels
-- (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('HOURS_TITLE','en','Best Hours'),
('HOURS_SUBTITLE','en','Live PHT clock + session window detector'),
('HOURS_AMPM_PHT','en','{ampm} PHT'),
('HOURS_AM','en','AM'),
('HOURS_PM','en','PM'),
('HOURS_DAY_SUN','en','Sunday'),
('HOURS_DAY_MON','en','Monday'),
('HOURS_DAY_TUE','en','Tuesday'),
('HOURS_DAY_WED','en','Wednesday'),
('HOURS_DAY_THU','en','Thursday'),
('HOURS_DAY_FRI','en','Friday'),
('HOURS_DAY_SAT','en','Saturday'),
('HOURS_MONTH_JAN','en','Jan'),
('HOURS_MONTH_FEB','en','Feb'),
('HOURS_MONTH_MAR','en','Mar'),
('HOURS_MONTH_APR','en','Apr'),
('HOURS_MONTH_MAY','en','May'),
('HOURS_MONTH_JUN','en','Jun'),
('HOURS_MONTH_JUL','en','Jul'),
('HOURS_MONTH_AUG','en','Aug'),
('HOURS_MONTH_SEP','en','Sep'),
('HOURS_MONTH_OCT','en','Oct'),
('HOURS_MONTH_NOV','en','Nov'),
('HOURS_MONTH_DEC','en','Dec'),
('HOURS_WINDOW_ACTIVE_NOW','en','{name} - Active now'),
('HOURS_DEAD_ZONE_MSG','en','Dead zone - do not trade'),
('HOURS_OUTSIDE_PRIME','en','Outside prime windows'),
('HOURS_SESSION_MAP_TIP','en','Highlights the hours when major markets (Asia, London, New York) are open and overlapping. Volume and volatility concentrate in these windows - the best liquidity to trade into, and where most large moves start.'),
('HOURS_SESSION_MAP_TITLE','en','24h Session Map'),
('HOURS_SESSION_MAP_SUBTITLE','en','PHT · typical weekday'),
('HOURS_SEG_NY','en','NY'),
('HOURS_SEG_PRIME','en','PRIME'),
('HOURS_SEG_ASIA','en','ASIA'),
('HOURS_SEG_DEAD','en','DEAD'),
('HOURS_SEG_LONDON','en','LONDON'),
('HOURS_SEG_PRE_NY','en','PRE-NY'),
('HOURS_TICK_MIDNIGHT','en','12A'),
('HOURS_TICK_NOON','en','12P'),
('HOURS_TICK_AM','en','{hr}A'),
('HOURS_TICK_PM','en','{hr}P'),
('HOURS_NOW_PREFIX','en','▲ now: '),
('HOURS_NOW_TIME','en','{time} {ampm} PHT'),
('HOURS_DOT_SEPARATOR','en','·'),
('HOURS_DOT_DEAD_ZONE','en','· Dead Zone'),
('HOURS_NEXT_WINDOWS','en','Next windows'),
('HOURS_WINDOW_ACTIVE_RIGHT_NOW','en','{name} is active RIGHT NOW'),
('HOURS_GO_HUNT','en','Go hunt.'),
('HOURS_NO_WINDOWS','en','No windows detected in next 7 days'),
('HOURS_ALL_WINDOWS','en','All windows'),
('HOURS_WIN_GOD_BADGE','en','GOD TIER'),
('HOURS_WIN_GOD_TIME','en','Sunday 11PM – Monday 3AM PHT'),
('HOURS_WIN_GOD_DESC','en','Lowest volume of the week. Retail asleep globally. Minimum capital needed to move price. Highest probability of violent raids. Maximum priority.'),
('HOURS_WIN_PRIME_BADGE','en','PRIME'),
('HOURS_WIN_PRIME_TIME','en','Daily 2AM – 5AM PHT'),
('HOURS_WIN_PRIME_DESC','en','Asia/Europe overlap. High institutional activity. Volume picks up. Best daily window for clean setups. 4:00–4:45AM PHT is the single most consistent reversal sub-window.'),
('HOURS_WIN_MON_EVE_BADGE','en','MON EVENING'),
('HOURS_WIN_MON_EVE_TIME','en','Monday 8PM – 11PM PHT'),
('HOURS_WIN_MON_EVE_DESC','en','Weekly liquidity build-up complete. US session active. Strong trend continuation or violent reversal setups. High probability of 3-5% moves.'),
('HOURS_WIN_LONDON_BADGE','en','LONDON OPEN'),
('HOURS_WIN_LONDON_TIME','en','3PM – 6PM PHT (9:30–11AM UTC)'),
('HOURS_WIN_LONDON_DESC','en','European institutions enter. Volume spike. Almost always a fake move first to trap early entries, then real direction emerges. Never trade the first 15 minutes.'),
('HOURS_WIN_DEAD_BADGE','en','DEAD ZONE'),
('HOURS_WIN_DEAD_TIME','en','12PM – 3PM PHT'),
('HOURS_WIN_DEAD_DESC','en','Do not trade. US pre-market, Europe lunch, Asia sleeping. Fake moves, tight spreads, no follow-through. Highest probability of stopping out on noise.')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
