-- ABOUT_* rows. Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('ABOUT_PAGE_TITLE','en','About'),
('ABOUT_PAGE_SUBTITLE','en','Liquidity Hunter HQ - private trading intelligence tool'),
('ABOUT_WHAT_THIS_IS_LABEL','en','What this is'),
('ABOUT_WHAT_THIS_IS_BODY','en','A personal crypto trading intelligence tool built around one core belief: the market is a machine for hunting stop losses. This app helps you read the liquidation map, identify the highest-probability raid setups, and time your entries around institutional windows.'),
('ABOUT_DATA_SOURCES_LABEL','en','Data sources'),
('ABOUT_DATA_SOURCE_PRICES_LABEL','en','Prices'),
('ABOUT_DATA_SOURCE_PRICES_VALUE','en','Binance WebSocket + REST - 50 coins (majors, alts, memes)'),
('ABOUT_DATA_SOURCE_ALTCOINS_LABEL','en','HYPE / PEPE / BONK'),
('ABOUT_DATA_SOURCE_ALTCOINS_VALUE','en','Bybit REST API'),
('ABOUT_DATA_SOURCE_FUNDING_OI_LABEL','en','Funding & Open Interest'),
('ABOUT_DATA_SOURCE_FUNDING_OI_VALUE','en','Bybit Public API'),
('ABOUT_DATA_SOURCE_LONG_SHORT_LABEL','en','Long/Short Ratio'),
('ABOUT_DATA_SOURCE_LONG_SHORT_VALUE','en','Bybit Account Ratio'),
('ABOUT_DATA_SOURCE_FEAR_GREED_LABEL','en','Fear & Greed'),
('ABOUT_DATA_SOURCE_FEAR_GREED_VALUE','en','Alternative.me'),
('ABOUT_DATA_SOURCE_BTC_DOMINANCE_LABEL','en','BTC Dominance'),
('ABOUT_DATA_SOURCE_BTC_DOMINANCE_VALUE','en','CoinMarketCap'),
('ABOUT_DATA_SOURCE_BREAKING_NEWS_LABEL','en','Breaking News'),
('ABOUT_DATA_SOURCE_BREAKING_NEWS_VALUE','en','Finnhub WebSocket'),
('ABOUT_DATA_SOURCE_CRYPTO_NEWS_LABEL','en','Crypto News'),
('ABOUT_DATA_SOURCE_CRYPTO_NEWS_VALUE','en','Finnhub + RSS (Reuters/AP/CoinDesk)'),
('ABOUT_DATA_SOURCE_ECON_CALENDAR_LABEL','en','Econ Calendar'),
('ABOUT_DATA_SOURCE_ECON_CALENDAR_VALUE','en','Finnhub Calendar API'),
('ABOUT_DATA_SOURCE_AI_SIGNAL_LABEL','en','AI Signal'),
('ABOUT_DATA_SOURCE_AI_SIGNAL_VALUE','en','LiquidityAI (xAI)'),
('ABOUT_HOW_TO_USE_LABEL','en','How to use'),
('ABOUT_STEP1_BOLD','en','Open the Liquidation Map'),
('ABOUT_STEP1_TEXT','en','24h window. Find the brightest, tightest cluster.'),
('ABOUT_STEP2_BOLD','en','Check the Raid Meter'),
('ABOUT_STEP2_TEXT','en','needs at least 60/100 to be worth trading.'),
('ABOUT_STEP3_BOLD','en','Run the Scanner'),
('ABOUT_STEP3_TEXT','en','7-question system. If it says NO, stay flat.'),
('ABOUT_STEP4_BOLD','en','Check Best Hours'),
('ABOUT_STEP4_TEXT','en','God Tier or Prime window only.'),
('ABOUT_STEP5_BOLD','en','Run LiquidityAI Arena'),
('ABOUT_STEP5_TEXT','en','confirms news sentiment aligns with setup.'),
('ABOUT_STEP6_BOLD','en','Enter 0.8–1.5% before the cluster.'),
('ABOUT_STEP6_TEXT','en','Exit the second it touches. Never hold.'),
('ABOUT_REMINDER_LABEL','en','Reminder'),
('ABOUT_REMINDER_TITLE','en','This is a private tool - not financial advice'),
('ABOUT_REMINDER_BODY','en','Built for one trader. No warranties. No signals service. All decisions are yours. The market does not care about your analysis.')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
