-- Wave 12 (final wave): /ops staff-only admin console - layout, login,
-- overview cards, team, users, user detail, config.
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('OPS_LAYOUT_DENY_TITLE','en','Access denied'),
('OPS_LAYOUT_DENY_EMAIL_PREFIX','en','You are signed in as'),
('OPS_LAYOUT_DENY_EMAIL_SUFFIX','en',', which is not an admin account.'),
('OPS_LAYOUT_DENY_NO_EMAIL','en','This account does not have admin access.'),
('OPS_LAYOUT_DENY_HINT','en','Ask an owner to grant you access from the Team page.'),
('OPS_LAYOUT_SIGN_OUT_SWITCH','en','Sign out & switch account'),
('OPS_LAYOUT_BACK_TO_APP','en','← Back to app'),
('OPS_LAYOUT_CHECKING_ACCESS','en','Checking access…'),
('OPS_LAYOUT_NAV_OVERVIEW','en','Overview'),
('OPS_LAYOUT_NAV_USERS','en','Users'),
('OPS_LAYOUT_NAV_TEAM','en','Team'),
('OPS_LAYOUT_NAV_CONFIG','en','Config'),
('OPS_LAYOUT_NAV_SIGN_OUT','en','Sign out'),
('OPS_LOGIN_ERROR_NOT_CONFIGURED','en','Auth is not configured.'),
('OPS_LOGIN_SIGNING_IN','en','Signing you in…'),
('OPS_LOGIN_SUBTITLE','en','Staff sign in'),
('OPS_LOGIN_EMAIL_LABEL','en','Email'),
('OPS_LOGIN_PASSWORD_LABEL','en','Password'),
('OPS_LOGIN_SUBMIT_BUSY','en','Signing in…'),
('OPS_LOGIN_SUBMIT_BUTTON','en','Sign in'),
('OPS_LOGIN_DIVIDER_OR','en','or'),
('OPS_LOGIN_GOOGLE_BUTTON','en','Sign in with Google'),
('OPS_CARDS_RELOAD_ARIA','en','Reload'),
('OPS_CARDS_LOADING','en','Loading…'),
('OPS_CARDS_NOT_AUTHORIZED','en','Not authorized'),
('OPS_CARDS_OVERVIEW_TITLE','en','Users & revenue'),
('OPS_CARDS_TOTAL_USERS','en','Total users'),
('OPS_CARDS_PRO','en','Pro'),
('OPS_CARDS_PAYING_SUB','en','{count} paying'),
('OPS_CARDS_FREE','en','Free'),
('OPS_CARDS_NEW_7D','en','New · 7d'),
('OPS_CARDS_IN_30D_SUB','en','{count} in 30d'),
('OPS_CARDS_ACTIVE_7D','en','Active · 7d'),
('OPS_CARDS_PRO_RATE','en','Pro rate'),
('OPS_CARDS_CRON_HEALTH_TITLE','en','Cron health'),
('OPS_CARDS_CRON_NOTE','en','Scanner & tracker show last activity, not last run - a quiet market fires nothing. The resolver''s overdue count is the true health signal.'),
('OPS_CARDS_AI_COST_TITLE','en','AI cost · Grok'),
('OPS_CARDS_CRON_CALLS_24H','en','Cron calls · 24h'),
('OPS_CARDS_CRON_CALLS_7D','en','Cron calls · 7d'),
('OPS_CARDS_NO_AI_USAGE','en','No per-user AI usage in the last 7 days.'),
('OPS_CARDS_AI_COST_NOTE','en','14-day system call volume; top AI users last 7d (deep + quick + chat + search + briefing).'),
('OPS_CARDS_SIGNAL_ACCURACY_TITLE','en','Signal accuracy'),
('OPS_CARDS_ALERT_24H_WIN','en','Alert 24h win'),
('OPS_CARDS_RESOLVED_SUB','en','{count} resolved'),
('OPS_CARDS_LIVE_SIG_WIN','en','Live sig win'),
('OPS_CARDS_AVG_R','en','Avg R'),
('OPS_CARDS_NO_RESOLVED_ALERTS','en','No resolved alerts yet.'),
('OPS_TEAM_ERR_NOT_SIGNED_IN','en','Not signed in'),
('OPS_TEAM_ERR_OWNER_ONLY','en','Owner only'),
('OPS_TEAM_ERR_FAILED_TO_ADD','en','Failed to add.'),
('OPS_TEAM_ADD_SUCCESS_NEW','en','Added {email}. They can sign in now with the password you set.'),
('OPS_TEAM_ADD_SUCCESS_EXISTING','en','{email} already had an account - granted admin access (their existing password is unchanged).'),
('OPS_TEAM_ADD_EMAIL_SENT_NOTE','en','Emailed them a heads-up.'),
('OPS_TEAM_ADD_EMAIL_NOT_SENT_NOTE','en','(No email sent - notifications not configured.)'),
('OPS_TEAM_ERR_UPDATE_FAILED','en','Update failed.'),
('OPS_TEAM_ERR_REMOVE_FAILED','en','Remove failed.'),
('OPS_TEAM_PAGE_TITLE','en','Team'),
('OPS_TEAM_ADD_ADMIN_HEADING','en','Add admin'),
('OPS_TEAM_EMAIL_PLACEHOLDER','en','Email'),
('OPS_TEAM_PASSWORD_PLACEHOLDER','en','Initial password (min 8 chars)'),
('OPS_TEAM_ROLE_STAFF','en','Staff'),
('OPS_TEAM_ROLE_OWNER','en','Owner'),
('OPS_TEAM_ADDING_BUTTON','en','Adding…'),
('OPS_TEAM_ADD_BUTTON','en','Add'),
('OPS_TEAM_LOADING','en','Loading…'),
('OPS_TEAM_EMPTY','en','No admins yet.'),
('OPS_TEAM_DISABLED_BADGE','en','DISABLED'),
('OPS_TEAM_YOU_SUFFIX','en','(you)'),
('OPS_TEAM_ADDED_AGO','en','added {ago}'),
('OPS_TEAM_MAKE_STAFF','en','Make staff'),
('OPS_TEAM_MAKE_OWNER','en','Make owner'),
('OPS_TEAM_DISABLE','en','Disable'),
('OPS_TEAM_ENABLE','en','Enable'),
('OPS_TEAM_REMOVE','en','Remove'),
('OPS_TEAM_FOOTER_NOTE','en','Passwords are handled by Supabase Auth, never stored here. Removing an admin revokes /ops access but does not delete their app account.'),
('OPS_USERS_ERR_NOT_SIGNED_IN','en','Not signed in'),
('OPS_USERS_PAGE_TITLE','en','Users'),
('OPS_USERS_SEARCH_PLACEHOLDER','en','Search by email…'),
('OPS_USERS_ERR_NOT_AUTHORIZED','en','Not authorized'),
('OPS_USERS_LOADING','en','Loading…'),
('OPS_USERS_EMPTY','en','No users match.'),
('OPS_USERS_PRO_BADGE','en','PRO'),
('OPS_USERS_BANNED_BADGE','en','BANNED'),
('OPS_USERS_JOINED_ACTIVE','en','joined {joined} · active {active}'),
('OPS_USERS_PREV','en','← Prev'),
('OPS_USERS_PAGE_OF','en','Page {page} of {total}'),
('OPS_USERS_NEXT','en','Next →'),
('OPS_USER_DETAIL_BAN_CONFIRM','en','Ban this account? They will be unable to sign in until unbanned.'),
('OPS_USER_DETAIL_ACTION_FAILED','en','Action failed.'),
('OPS_USER_DETAIL_DONE','en','Done.'),
('OPS_USER_DETAIL_BACK_LINK','en','← Back to users'),
('OPS_USER_DETAIL_LOADING','en','Loading…'),
('OPS_USER_DETAIL_NOT_FOUND','en','User not found'),
('OPS_USER_DETAIL_NOT_AUTHORIZED','en','Not authorized'),
('OPS_USER_DETAIL_PRO_BADGE','en','PRO'),
('OPS_USER_DETAIL_BANNED_BADGE','en','BANNED'),
('OPS_USER_DETAIL_META','en','joined {joined} · last active {active} · id {id}'),
('OPS_USER_DETAIL_SUBSCRIPTION','en','Subscription'),
('OPS_USER_DETAIL_ROLE','en','Role'),
('OPS_USER_DETAIL_LS_STATUS','en','LS status'),
('OPS_USER_DETAIL_PERIOD_END','en','Period end'),
('OPS_USER_DETAIL_ONBOARDING_DEVICES','en','Onboarding & devices'),
('OPS_USER_DETAIL_TOUR_SEEN','en','Tour seen'),
('OPS_USER_DETAIL_YES','en','Yes'),
('OPS_USER_DETAIL_NO','en','No'),
('OPS_USER_DETAIL_CHECKLIST','en','Checklist'),
('OPS_USER_DETAIL_PUSH_DEVICES','en','Push devices'),
('OPS_USER_DETAIL_ACTIVITY_COUNTS','en','Activity counts'),
('OPS_USER_DETAIL_TRADES_LOGGED','en','Trades logged'),
('OPS_USER_DETAIL_HYPOTHESES','en','Hypotheses'),
('OPS_USER_DETAIL_PRICE_ALERTS','en','Price alerts'),
('OPS_USER_DETAIL_COUNTS_NOTE','en','Counts only - journal/hypothesis content stays private.'),
('OPS_USER_DETAIL_AI_USAGE_TITLE','en','AI usage · 14d'),
('OPS_USER_DETAIL_TOTAL_CALLS','en','Total calls'),
('OPS_USER_DETAIL_ACTIONS','en','Actions'),
('OPS_USER_DETAIL_WORKING','en','Working…'),
('OPS_USER_DETAIL_REVOKE_PRO','en','Revoke Pro'),
('OPS_USER_DETAIL_GRANT_PRO','en','Grant Pro'),
('OPS_USER_DETAIL_UNBAN','en','Unban'),
('OPS_USER_DETAIL_BAN_SELF_TITLE','en','You can''t ban the account you''re signed in as.'),
('OPS_USER_DETAIL_BAN_SELF_LABEL','en','Ban account (not your own)'),
('OPS_USER_DETAIL_BAN_ACCOUNT','en','Ban account'),
('OPS_USER_DETAIL_RESET_AI_LIMIT','en','Reset today''s AI limit'),
('OPS_USER_DETAIL_ACTIONS_NOTE','en','Grant/Revoke Pro only touches the role - an existing paid subscription''s billing fields are untouched. Ban blocks sign-in via Supabase Auth; you cannot ban yourself. Every action is written to the audit log.'),
('OPS_CONFIG_FEATURE_GROK','en','Grok / LiquidityAI'),
('OPS_CONFIG_FEATURE_TELEGRAM','en','Telegram alerts'),
('OPS_CONFIG_DURATION_NO_EXPIRY','en','No expiry'),
('OPS_CONFIG_DURATION_1H','en','1 hour'),
('OPS_CONFIG_DURATION_6H','en','6 hours'),
('OPS_CONFIG_DURATION_24H','en','24 hours'),
('OPS_CONFIG_DURATION_3D','en','3 days'),
('OPS_CONFIG_DURATION_7D','en','7 days'),
('OPS_CONFIG_STATUS_LIVE','en','Live'),
('OPS_CONFIG_STATUS_EXPIRED','en','Expired'),
('OPS_CONFIG_STATUS_OFF','en','Off'),
('OPS_CONFIG_STATUS_REPLACED','en','Replaced'),
('OPS_CONFIG_TITLE','en','App config'),
('OPS_CONFIG_LOADING','en','Loading…'),
('OPS_CONFIG_ERR_OWNER_ONLY','en','Owner only'),
('OPS_CONFIG_SAVE_FAILED','en','Save failed.'),
('OPS_CONFIG_SAVE_SUCCESS','en','Saved. Live app picks it up within ~15s.'),
('OPS_CONFIG_MAINTENANCE_TITLE','en','Maintenance mode'),
('OPS_CONFIG_MAINTENANCE_ON_BADGE','en','ON'),
('OPS_CONFIG_MAINTENANCE_NOTE','en','When on, every page except /ops shows a maintenance screen - the whole app is closed to signed-in users too. /ops stays reachable so you can turn it back off.'),
('OPS_CONFIG_WORKING','en','Working…'),
('OPS_CONFIG_TURN_OFF_MAINTENANCE','en','Turn off maintenance mode'),
('OPS_CONFIG_TURN_ON_MAINTENANCE','en','Turn on maintenance mode'),
('OPS_CONFIG_FEATURE_FLAGS_TITLE','en','Feature kill switches'),
('OPS_CONFIG_FEATURE_FLAGS_NOTE','en','Turns off one feature for everyone without a full maintenance-mode outage. Live app picks it up within ~15s. Grok off also silences the AI commentary line in Telegram alerts (the alerts themselves still send).'),
('OPS_CONFIG_OFF_BADGE','en','OFF'),
('OPS_CONFIG_TURN_OFF','en','Turn off'),
('OPS_CONFIG_TURN_ON','en','Turn on'),
('OPS_CONFIG_BANNER_TITLE','en','Announcement banner'),
('OPS_CONFIG_NO_BANNER_SET','en','No banner set'),
('OPS_CONFIG_BANNER_VISIBLE_EXPIRY','en','Visible to everyone, auto-hides {expiry} ({date})'),
('OPS_CONFIG_BANNER_VISIBLE_NO_EXPIRY','en','Visible to everyone, no expiry set'),
('OPS_CONFIG_BANNER_EXPIRED','en','Expired {date} - no longer shown'),
('OPS_CONFIG_BANNER_NOTHING_SHOWN','en','Nothing shown on the live app'),
('OPS_CONFIG_CLEAR_BUTTON','en','Clear'),
('OPS_CONFIG_BANNER_NOTE','en','Shown above the app on every page (dismissible per-visitor). Empty text = hidden.'),
('OPS_CONFIG_BANNER_TEXT_PLACEHOLDER','en','Banner text (empty = hidden)'),
('OPS_CONFIG_BANNER_LINK_PLACEHOLDER','en','Link (optional, e.g. /about)'),
('OPS_CONFIG_SAVING','en','Saving…'),
('OPS_CONFIG_POST_BANNER','en','Post banner'),
('OPS_CONFIG_HISTORY_TITLE','en','History'),
('OPS_CONFIG_CLEARED','en','(cleared)'),
('OPS_CONFIG_HISTORY_BY','en','{ago} by {email}'),
('OPS_CONFIG_HISTORY_EXPIRY_SUFFIX','en',' · expiry {date}'),
('OPS_CONFIG_REUSE_BUTTON','en','Reuse')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
