-- BRIEFING_* rows (app/briefing/page.tsx). Run once against BOTH lhq_labels
-- (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('BRIEFING_PAGE_TITLE','en','Morning Briefing'),
('BRIEFING_HINT_TITLE','en','Morning Briefing'),
('BRIEFING_HINT_BODY','en','Your daily market summary - top setups, key support and resistance levels, macro signals, and AI-generated trade ideas updated each morning.'),
('BRIEFING_SIGN_IN_REQUIRED','en','Sign in to generate a briefing.'),
('BRIEFING_SESSION_EXPIRED','en','Session expired - please sign in again.'),
('BRIEFING_RATE_LIMIT_DEFAULT','en','Rate limit reached.'),
('BRIEFING_RATE_LIMIT_MSG','en','{error} Resets at {resetTime}.'),
('BRIEFING_UNKNOWN_ERROR','en','Unknown error'),
('BRIEFING_TOP3_TITLE','en','Top 3 Setups Today'),
('BRIEFING_SEE_ALL_ARENA','en','See all in Arena →'),
('BRIEFING_LOADING_MARKET_SR','en','Loading market data…'),
('BRIEFING_NO_SETUPS','en','No strong setups right now - market positioning is balanced.'),
('BRIEFING_DIR_LONG','en','Long ↑'),
('BRIEFING_DIR_SHORT','en','Short ↓'),
('BRIEFING_TAG_FR_POS','en','FR +{value}%'),
('BRIEFING_TAG_FR_ELEVATED','en','FR Elevated'),
('BRIEFING_TAG_FR_NEG_VALUE','en','FR {value}%'),
('BRIEFING_TAG_FR_NEG','en','FR Neg'),
('BRIEFING_TAG_LONGS_PCT','en','Longs {pct}%'),
('BRIEFING_TAG_SHORTS_PCT','en','Shorts {pct}%'),
('BRIEFING_TAG_TAKER_SELL','en','Taker Sell'),
('BRIEFING_TAG_TAKER_BUY','en','Taker Buy'),
('BRIEFING_TAG_VOL','en','Vol {x}x'),
('BRIEFING_TAG_RSI','en','RSI {value}'),
('BRIEFING_TAG_OI_DOWN','en','Open Int ↓'),
('BRIEFING_TAG_OI_UP','en','Open Int ↑'),
('BRIEFING_AI_TITLE','en','AI Pre-Session Briefing'),
('BRIEFING_BTN_GENERATING','en','Generating…'),
('BRIEFING_BTN_REGENERATE','en','↻ Regenerate'),
('BRIEFING_BTN_GENERATE','en','Generate Briefing'),
('BRIEFING_EMPTY_STATE','en','Hit Generate to get a LiquidityAI pre-session summary - market conditions, best setup, what to watch.'),
('BRIEFING_BRIEF_CACHED','en','Generated {label} · expires in {mins}m'),
('BRIEFING_CVD_TITLE','en','Active CVD Divergences'),
('BRIEFING_CVD_BULL','en','▲ Bull'),
('BRIEFING_CVD_BEAR','en','▼ Bear'),
('BRIEFING_MACRO_PULSE_TITLE','en','Macro Pulse'),
('BRIEFING_FNG_TIP','en','A 0-100 gauge of overall crypto sentiment built from volatility, momentum, and volume. Extreme fear (low) often marks bottoms, while extreme greed (high) often precedes a pullback.'),
('BRIEFING_FNG_LABEL','en','Fear & Greed'),
('BRIEFING_BTCDOM_TIP','en','Bitcoin''s share of the total crypto market cap. Rising dominance means money is rotating into BTC and altcoins are bleeding; falling dominance means alts are outperforming (alt season).'),
('BRIEFING_BTCDOM_LABEL','en','BTC Dom'),
('BRIEFING_DXY_TIP','en','The US dollar''s strength against a basket of major currencies. A rising dollar usually pulls liquidity out of risk assets like crypto (headwind); a falling dollar is typically a tailwind.'),
('BRIEFING_DXY_LABEL','en','DXY'),
('BRIEFING_ETF_TIP','en','Net daily money flowing into or out of US spot Bitcoin ETFs. Sustained inflows signal institutional buying demand; sustained outflows signal institutions cutting exposure.'),
('BRIEFING_ETF_LABEL','en','BTC ETF Flow'),
('BRIEFING_DOM_ALTS_WEAK','en','↑ Alts weak'),
('BRIEFING_DOM_ALTS_ACTIVE','en','↓ Alts active'),
('BRIEFING_DXY_HEADWIND','en','↑ BTC headwind'),
('BRIEFING_DXY_TAILWIND','en','↓ BTC tailwind'),
('BRIEFING_DXY_NEUTRAL','en','Neutral'),
('BRIEFING_ETF_STRONG_IN','en','Strong inflow'),
('BRIEFING_ETF_MILD_IN','en','Mild inflow'),
('BRIEFING_ETF_STRONG_OUT','en','Strong outflow'),
('BRIEFING_ETF_MILD_OUT','en','Mild outflow'),
('BRIEFING_YEN_WATCH_TITLE','en','Yen Watch'),
('BRIEFING_FETCHING_RATE_SR','en','Fetching rate…'),
('BRIEFING_YEN_DANGER','en','DANGER'),
('BRIEFING_YEN_WARNING','en','WARNING'),
('BRIEFING_YEN_SAFE','en','SAFE'),
('BRIEFING_YEN_DANGER_DESC','en','BOJ intervention risk high - carry trade unwind can trigger BTC liquidations. Reduce leverage.'),
('BRIEFING_YEN_WARNING_DESC','en','Approaching 160 danger zone. Watch for BOJ rhetoric or surprise rate hike signals.'),
('BRIEFING_YEN_SAFE_DESC','en','Yen carry trade stable. Reduced crypto liquidation risk from JPY side.'),
('BRIEFING_YEN_PAIR_LABEL','en','USD/JPY'),
('BRIEFING_YEN_UPDATED','en','Updated {time}'),
('BRIEFING_NOTABLE_SIGNALS_TITLE','en','Notable Signals'),
('BRIEFING_FULL_SCANNER_LINK','en','Full scanner →'),
('BRIEFING_NO_SIGNALS','en','All quiet - no extreme signals right now.'),
('BRIEFING_MORE_SIGNALS','en','+{count} more coins with signals - Full scanner →'),
('BRIEFING_TAG_OI_STRONG_UP','en','OI ↑↑'),
('BRIEFING_TAG_OI_STRONG_DOWN','en','OI ↓↓'),
('BRIEFING_TAG_CVD_BULL','en','CVD Bull'),
('BRIEFING_TAG_CVD_BEAR','en','CVD Bear'),
('BRIEFING_EVENTS_NEWS_TITLE','en','Events & News'),
('BRIEFING_NO_EVENTS','en','No active events in the next 24h. Clean macro backdrop.'),
('BRIEFING_WHALE_PREFIX','en','WHALE {side}')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
