-- BACKTEST_*, SCANNER_* rows (app/backtest/page.tsx, app/scanner/page.tsx).
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('BACKTEST_LOADING','en','Loading…'),
('BACKTEST_UPGRADE_TITLE','en','Backtesting is part of Pro.'),
('BACKTEST_UPGRADE_DESC','en','Replay the full signal engine against years of historical candles - every coin, every timeframe, Anti-Chop on and off side by side - plus the order flow backtest and the AI strategy research tools.'),
('BACKTEST_PAGE_TITLE','en','Strategy Backtest'),
('BACKTEST_PAGE_SUBTITLE','en','EMA ribbon strategy replayed against historical candles - Anti-Chop ON vs OFF, side by side'),
('BACKTEST_MAJORS_BUTTON','en','Majors ({count})'),
('BACKTEST_ALL_COINS_BUTTON','en','All Coins ({count})'),
('BACKTEST_LOOKBACK_INFO','en','Lookback: {years} years · Pooled across {count} coin{s} · Fixed 2:1 R:R per signal (matches live strategy SL/TP rule) · Net of an estimated {roundTripPct}% round-trip cost ({takerFeePct}% taker fee + {slippagePct}% slippage, each side) - not gross'),
('BACKTEST_RUNNING_PROGRESS','en','Running… {done}/{total}{coinSuffix}'),
('BACKTEST_RUN_BUTTON','en','Run Backtest'),
('BACKTEST_ERROR_PREFIX','en','Error: {error}'),
('BACKTEST_TOOLS_INTRO','en','4 tools on this page - pick one to get started'),
('BACKTEST_TOOL_BACKTEST_LABEL','en','Strategy Backtest'),
('BACKTEST_TOOL_BACKTEST_DESC','en','Replay the EMA ribbon against 2-4 years of candles. Pick a timeframe and scope above, then hit Run Backtest.'),
('BACKTEST_TOOL_RESEARCH_LABEL','en','Strategy Research'),
('BACKTEST_TOOL_RESEARCH_DESC','en','Describe any trading strategy in plain English. Grok evaluates its edge, risks, and optimal entry conditions. Scroll down.'),
('BACKTEST_TOOL_SMC_LABEL','en','SMC Snapshot'),
('BACKTEST_TOOL_SMC_DESC','en','Pick a coin and timeframe. Grok reads live candles and identifies Break of Structure, Fair Value Gaps, Order Blocks, and Liquidity zones.'),
('BACKTEST_TOOL_UNLOCK_LABEL','en','Token Unlock Forecaster'),
('BACKTEST_TOOL_UNLOCK_DESC','en','Enter any token ticker. Grok assesses 30-day and 90-day sell pressure risk based on vesting schedules and unlock history.'),
('BACKTEST_SKIPPED_COINS','en','Skipped {count} coin{s} (no data or fetch error): {list}'),
('BACKTEST_SIDECARD_ANTICHOP_ON','en','ANTI-CHOP ON'),
('BACKTEST_SIDECARD_ANTICHOP_OFF','en','ANTI-CHOP OFF'),
('BACKTEST_WT_TUNING_TITLE','en','WaveTrend Confirming-Layer Tuning'),
('BACKTEST_WT_TUNING_DESC','en','Each row requires WaveTrend to also agree before counting an Anti-Chop ON signal as a trade. Compare against the Anti-Chop ON baseline above ({winRate} win rate, {trades} trades, PF {pf}).'),
('BACKTEST_COL_VARIANT','en','Variant'),
('BACKTEST_COL_TRADES','en','Trades'),
('BACKTEST_COL_WIN_RATE','en','Win Rate'),
('BACKTEST_COL_AVG_R','en','Avg R'),
('BACKTEST_COL_PROFIT_FACTOR','en','Profit Factor'),
('BACKTEST_COL_MAX_DD','en','Max DD'),
('BACKTEST_COL_COIN','en','Coin'),
('BACKTEST_PERCOIN_TITLE_ON','en','Per-Coin Breakdown (Anti-Chop ON)'),
('BACKTEST_PERCOIN_TITLE','en','Per-Coin Breakdown'),
('BACKTEST_OF_SECTION_TITLE','en','Order Flow Setup Validation'),
('BACKTEST_OF_SECTION_SUBTITLE','en','Tests the Arena page''s "Order Flow Setup" card - but only the 5 signals that can be faithfully replayed from history: RSI on 15m/1h/4h, price vs POC, price vs VWAP, and funding rate.'),
('BACKTEST_OF_INFO','en','Open Interest trend, CVD divergence, and taker buy ratio (3 of the live card''s 8 signals) are intentionally excluded - those need trade-level/positioning data exchanges don''t retain far enough back to backtest meaningfully (Binance''s OI history, for example, only goes back ~30 days). Lookback is {years} year{s} (shorter than the EMA backtest above - fetching 15m+1h+4h+funding per coin is a much heavier pull) · uses the same coin scope selected above ({count} coins). Also net of the same {roundTripPct}% round-trip fee + slippage estimate.'),
('BACKTEST_RUN_OF_BUTTON','en','Run Order Flow Backtest'),
('BACKTEST_OF_ERROR_PREFIX','en','Error: {error}'),
('BACKTEST_OF_SKIPPED_COINS','en','Skipped {count} coin{s} (no data or fetch error): {list}'),
('BACKTEST_SIDECARD_OF_TITLE','en','ORDER FLOW SETUP (5 SIGNALS)'),
('BACKTEST_AI_RESEARCH_TITLE','en','AI Strategy Research'),
('BACKTEST_AI_RESEARCH_SUBTITLE','en','Describe any trading strategy in plain English - get an honest analysis of its edge, risks, optimal conditions, and crypto-specific parameters.'),
('BACKTEST_AI_RESEARCH_EXAMPLES','en','Examples: "EMA 9/20 crossover with RSI confirmation on 1h BTC" · "Buy the open interest spike with funding rate reversal" · "Mean reversion after 3 consecutive red 4h candles"'),
('BACKTEST_SR_PLACEHOLDER','en','Describe a strategy to research…'),
('BACKTEST_SR_RUNNING','en','Researching…'),
('BACKTEST_SR_BUTTON','en','Research Strategy'),
('BACKTEST_SR_CLEAR','en','Clear'),
('BACKTEST_SR_ANALYSIS_FAILED','en','Analysis failed'),
('BACKTEST_SR_NETWORK_ERROR','en','Network error - try again'),
('BACKTEST_SR_SECTION_THEORETICAL_EDGE','en','Theoretical Edge'),
('BACKTEST_SR_SECTION_OPTIMAL_CONDITIONS','en','Optimal Conditions'),
('BACKTEST_SR_SECTION_KEY_RISKS','en','Key Risks'),
('BACKTEST_SR_SECTION_PARAMETER_SUGGESTIONS','en','Parameter Suggestions'),
('BACKTEST_SR_SECTION_CRYPTO_NOTES','en','Crypto Notes'),
('BACKTEST_SR_SECTION_HONEST_ASSESSMENT','en','Honest Assessment'),
('BACKTEST_PINE_EXPORT_LABEL','en','Export this strategy to TradingView'),
('BACKTEST_PINE_GENERATING','en','Generating Pine Script…'),
('BACKTEST_PINE_GENERATE_BUTTON','en','Generate TradingView Alert'),
('BACKTEST_PINE_COPIED','en','Copied!'),
('BACKTEST_PINE_COPY_BUTTON','en','Copy Pine Script'),
('BACKTEST_PINE_REGENERATE','en','Regenerate'),
('BACKTEST_PINE_GENERATION_FAILED','en','Generation failed'),
('BACKTEST_PINE_NETWORK_ERROR','en','Network error - try again'),
('BACKTEST_SMC_TITLE','en','SMC Snapshot'),
('BACKTEST_SMC_SUBTITLE','en','Pick an asset and timeframe - Grok analyzes recent price action using Smart Money Concepts: Break of Structure, Fair Value Gaps, Order Blocks, and Liquidity zones.'),
('BACKTEST_SMC_ASSET_PLACEHOLDER','en','BTC'),
('BACKTEST_SMC_RUNNING','en','Analyzing…'),
('BACKTEST_SMC_RUN_BUTTON','en','Run SMC Analysis'),
('BACKTEST_SMC_CLEAR','en','Clear'),
('BACKTEST_SMC_ANALYSIS_FAILED','en','Analysis failed'),
('BACKTEST_SMC_NETWORK_ERROR','en','Network error - try again'),
('BACKTEST_SMC_SECTION_MARKET_STRUCTURE','en','Market Structure'),
('BACKTEST_SMC_SECTION_FAIR_VALUE_GAPS','en','Fair Value Gaps'),
('BACKTEST_SMC_SECTION_ORDER_BLOCKS','en','Order Blocks'),
('BACKTEST_SMC_SECTION_LIQUIDITY_ZONES','en','Liquidity Zones'),
('BACKTEST_SMC_SECTION_DIRECTIONAL_BIAS','en','Directional Bias'),
('BACKTEST_SMC_SECTION_KEY_LEVELS','en','Key Levels'),
('BACKTEST_UL_TITLE','en','Token Unlock Sell Pressure'),
('BACKTEST_UL_SUBTITLE','en','Enter a token symbol - Grok analyzes upcoming vesting cliff events and classifies sell pressure impact for the next 30 and 90 days.'),
('BACKTEST_UL_EXAMPLES','en','Examples: ARB · OP · PYTH · JUP · STRK · SUI · W · ZK · EIGEN'),
('BACKTEST_UL_PLACEHOLDER','en','e.g. ARB'),
('BACKTEST_UL_RUNNING','en','Analyzing…'),
('BACKTEST_UL_RUN_BUTTON','en','Analyze Unlock Risk'),
('BACKTEST_UL_CLEAR','en','Clear'),
('BACKTEST_UL_ANALYSIS_FAILED','en','Analysis failed'),
('BACKTEST_UL_NETWORK_ERROR','en','Network error - try again'),
('BACKTEST_UL_SECTION_CURRENT_SUPPLY','en','Current Supply'),
('BACKTEST_UL_SECTION_UNLOCK_SCHEDULE','en','Unlock Schedule'),
('BACKTEST_UL_SECTION_SELL_PRESSURE_30D','en','30-Day Sell Pressure'),
('BACKTEST_UL_SECTION_SELL_PRESSURE_90D','en','90-Day Sell Pressure'),
('BACKTEST_UL_SECTION_HISTORICAL_PATTERN','en','Historical Pattern'),
('BACKTEST_UL_SECTION_RECOMMENDATION','en','Recommendation'),
('BACKTEST_WT_VARIANT_CURRENT','en','Current (20-bar window)'),
('BACKTEST_WT_VARIANT_TIGHT_RECENCY','en','Tight Recency (5-bar, pre-tuning default)'),
('BACKTEST_WT_VARIANT_ARM_WINDOW','en','Arm Window (full cross phase)'),
('BACKTEST_WT_VARIANT_DIVERGENCE_ONLY','en','Divergence Only (no cross req.)'),
('BACKTEST_WT_VARIANT_LOOSE_THRESHOLDS','en','Loose Thresholds (±45 + arm)'),
('SCANNER_HINT_TITLE','en','Scanners'),
('SCANNER_HINT_BODY','en','Scan the market for squeeze setups, multi-timeframe confluences, and coins showing unusual accumulation or distribution patterns.')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
