-- UPGRADE_* rows (app/upgrade/page.tsx). Run once against BOTH lhq_labels
-- (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('UPGRADE_FREE_FEATURE_DASHBOARD','en','Dashboard + market overview'),
('UPGRADE_FREE_FEATURE_BRIEFING','en','Morning briefing'),
('UPGRADE_FREE_FEATURE_NEWS','en','News feed'),
('UPGRADE_FREE_FEATURE_SCANNER','en','Squeeze scanner on every tracked coin'),
('UPGRADE_FREE_FEATURE_CHARTS','en','Charts + signals on 30 minute and higher timeframes'),
('UPGRADE_FREE_FEATURE_AI_ANALYSES','en','{quick} Quick + {deep} Deep AI analyses / day'),
('UPGRADE_FREE_FEATURE_AI_CHAT','en','{chat} AI chat messages / day'),
('UPGRADE_PRO_FEATURE_EVERYTHING_FREE','en','Everything in Free'),
('UPGRADE_PRO_FEATURE_FAST_TIMEFRAMES','en','Signals on the 1 minute, 5 minute, and 15 minute charts'),
('UPGRADE_PRO_FEATURE_CONFLUENCE','en','Confluence Score, Order Flow, and Absorption Detector'),
('UPGRADE_PRO_FEATURE_BACKTESTING','en','Full strategy backtesting'),
('UPGRADE_PRO_FEATURE_ONCHAIN_MACRO','en','On-chain and global macro AI analysis'),
('UPGRADE_PRO_FEATURE_TELEGRAM','en','Telegram alerts - all signal types'),
('UPGRADE_PRO_FEATURE_UNLIMITED_ALERTS','en','Unlimited price alerts'),
('UPGRADE_PRO_FEATURE_AI_ANALYSES','en','{quick} Quick + {deep} Deep AI analyses / day'),
('UPGRADE_PRO_FEATURE_AI_CHAT_SEARCH','en','{chat} AI chat messages + {search} live searches / day'),
('UPGRADE_PRO_FEATURE_PRIORITY_SUPPORT','en','Priority support'),
('UPGRADE_LOADING_REDIRECTING','en','Redirecting…'),
('UPGRADE_LOADING','en','Loading…'),
('UPGRADE_BACK_LABEL','en','← Back'),
('UPGRADE_EYEBROW','en','Pro Plan'),
('UPGRADE_HERO_TITLE','en','Unlock the full stack'),
('UPGRADE_HERO_SUBTITLE','en','Fast timeframes, the full signal stack, backtesting, and more AI everywhere. Everything a serious trader needs in one place.'),
('UPGRADE_FREE_CARD_EYEBROW','en','Current plan'),
('UPGRADE_FREE_CARD_NAME','en','Free'),
('UPGRADE_PRICE_SUFFIX_MONTHLY','en','/mo'),
('UPGRADE_PRO_CARD_BADGE','en','Recommended'),
('UPGRADE_PRO_CARD_EYEBROW','en','Upgrade to'),
('UPGRADE_PRO_CARD_NAME','en','Pro'),
('UPGRADE_CHECKOUT_BUTTON_REDIRECTING','en','Redirecting to checkout…'),
('UPGRADE_CHECKOUT_BUTTON_CTA','en','Get Pro - $15/mo →'),
('UPGRADE_TRUST_CANCEL_ANYTIME','en','Cancel anytime'),
('UPGRADE_TRUST_INSTANT_ACCESS','en','Instant access'),
('UPGRADE_TRUST_SECURE_CHECKOUT','en','Secure checkout'),
('UPGRADE_COMING_SOON_TITLE','en','Pro payments launching soon'),
('UPGRADE_COMING_SOON_SIGNED_IN_PRE','en','We''re finalising the payment system. You''ll be notified at'),
('UPGRADE_COMING_SOON_SIGNED_IN_POST','en','as soon as Pro is available.'),
('UPGRADE_COMING_SOON_SIGNED_OUT_PRE','en','We''re finalising the payment system.'),
('UPGRADE_COMING_SOON_SIGNUP_LINK','en','Sign up'),
('UPGRADE_COMING_SOON_SIGNED_OUT_POST','en','to get notified as soon as Pro is available.'),
('UPGRADE_BACK_TO_ARENA_LINK','en','Back to Arena')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
