-- ARENA_* rows part 1/2 (app/arena/page.tsx: TF gate, browser notifications,
-- readMarket errors, page header, category tabs, scanner flyout). Run once
-- against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('ARENA_TF_LABEL_1M','en','The 1 minute timeframe'),
('ARENA_TF_LABEL_5M','en','The 5 minute timeframe'),
('ARENA_TF_LABEL_15M','en','The 15 minute timeframe'),
('ARENA_TF_LABEL_FALLBACK','en','This timeframe'),
('ARENA_ALERT_NOTIFS_UNSUPPORTED','en','Notifications not supported in this browser.'),
('ARENA_ALERT_NOTIFS_DENIED','en','Notification permission denied. Enable in browser settings.'),
('ARENA_NOTIF_FUNDING_TITLE','en','{coin} Extreme Funding'),
('ARENA_NOTIF_FUNDING_BODY','en','{pct}% - {suffix}'),
('ARENA_NOTIF_FUNDING_SUFFIX_LONG_RISK','en','Longs at risk ↓'),
('ARENA_NOTIF_FUNDING_SUFFIX_SHORT_SQUEEZE','en','Shorts being squeezed ↑'),
('ARENA_NOTIF_FNG_TITLE_FEAR','en','Extreme Fear'),
('ARENA_NOTIF_FNG_TITLE_GREED','en','Extreme Greed'),
('ARENA_NOTIF_FNG_BODY','en','Fear & Greed: {fng} ({label}) - {suffix}'),
('ARENA_NOTIF_FNG_SUFFIX_BOTTOM','en','Potential bottom signal'),
('ARENA_NOTIF_FNG_SUFFIX_OVEREXTENDED','en','Markets overextended'),
('ARENA_NOTIF_CVD_TITLE_BULL','en','{coin} Bullish CVD Divergence'),
('ARENA_NOTIF_CVD_TITLE_BEAR','en','{coin} Bearish CVD Divergence'),
('ARENA_NOTIF_CVD_BODY_BULL','en','Price falling but buyers absorbing - smart money accumulating. Watch for reversal ↑'),
('ARENA_NOTIF_CVD_BODY_BEAR','en','Price rising but sellers increasing - distribution detected. Watch for reversal ↓'),
('ARENA_NOTIF_RSI_OB_TITLE','en','{coin} Momentum too high (1H)'),
('ARENA_NOTIF_RSI_OB_BODY','en','Momentum (RSI): {rsi} - Exhaustion zone. Avoid chasing longs, watch for reversal candle.'),
('ARENA_NOTIF_RSI_OS_TITLE','en','{coin} Momentum too low (1H)'),
('ARENA_NOTIF_RSI_OS_BODY','en','Momentum (RSI): {rsi} - Bounce setup forming. Watch for volume spike + rejection candle.'),
('ARENA_NOTIF_PATTERN_BULL_TITLE','en','{coin} Bullish Pattern'),
('ARENA_NOTIF_PATTERN_BULL_BODY','en','{pattern} - Check for entry confirmation.'),
('ARENA_NOTIF_PATTERN_BEAR_TITLE','en','{coin} Bearish Pattern'),
('ARENA_NOTIF_PATTERN_BEAR_BODY','en','{pattern} - Watch for breakdown confirmation.'),
('ARENA_NOTIF_OI_UP_TITLE','en','{coin} Open Interest Spike - New Longs'),
('ARENA_NOTIF_OI_UP_BODY','en','Open interest rising with price - real trend, new money entering. Bullish continuation likely.'),
('ARENA_NOTIF_OI_DOWN_TITLE','en','{coin} Open Interest Spike - New Shorts'),
('ARENA_NOTIF_OI_DOWN_BODY','en','Open interest rising with price falling - new shorts entering. Bearish continuation likely.'),
('ARENA_NOTIF_SENTIMENT_BEAR_TITLE','en','Sentiment Extremes - Bearish'),
('ARENA_NOTIF_SENTIMENT_BEAR_BODY','en','F&G {fng} (Extreme Greed) · FR +{fr}% · {longPct}% Long - all 3 at extremes. Long flush risk elevated. Tighten stops.'),
('ARENA_NOTIF_SENTIMENT_BULL_TITLE','en','Sentiment Extremes - Contrarian Bullish'),
('ARENA_NOTIF_SENTIMENT_BULL_BODY','en','F&G {fng} (Extreme Fear) · FR {fr}% · {shortPct}% Short - all 3 at extremes. Potential reversal zone. Wait for confirmation.'),
('ARENA_ERROR_NO_DATA_SOURCE','en','No market data source for {coin}'),
('ARENA_ERROR_BINANCE_API','en','Binance API error'),
('ARENA_ERROR_BYBIT_API','en','Bybit API error'),
('ARENA_ERROR_UNKNOWN','en','Unknown error'),
('ARENA_PAGE_TITLE','en','LiquidityAI Arena'),
('ARENA_LIVE_BADGE','en','LiquidityAI · LIVE X'),
('ARENA_PAGE_SUBTITLE','en','Run the AI read on any coin - direction, confidence, and levels.'),
('ARENA_HINT_TITLE','en','Arena'),
('ARENA_HINT_BODY','en','Pick a coin and timeframe, then run the analysis. You get a plain directional read - long, short, or wait - with a confidence score and entry, stop, and target levels.'),
('ARENA_CAT_ALL','en','All'),
('ARENA_CAT_MAJORS','en','Majors'),
('ARENA_CAT_ALTS','en','Alts'),
('ARENA_CAT_DEFI','en','DeFi/AI'),
('ARENA_CAT_MEME','en','Meme'),
('ARENA_ALERTS_ON_TITLE','en','Alerts ON'),
('ARENA_ALERTS_ENABLE_TITLE','en','Enable browser alerts'),
('ARENA_SCANNER_SEARCH_PLACEHOLDER','en','Search coins…'),
('ARENA_SCANNER_CLEAR_SEARCH_ARIA','en','Clear search'),
('ARENA_SCANNER_COL_NAME','en','Name'),
('ARENA_SCANNER_COL_PRICE','en','Price'),
('ARENA_SCANNER_COL_24H','en','24h'),
('ARENA_SCANNER_COL_VS_BTC','en','vs BTC'),
('ARENA_SCANNER_COL_STATUS','en','Status'),
('ARENA_SCANNER_COL_SCORE','en','Score'),
('ARENA_SCANNER_NO_MATCH','en','No coins match "{search}"'),
('ARENA_SCANNER_BADGE_OVERBOUGHT','en','Overbought'),
('ARENA_SCANNER_BADGE_OVERSOLD','en','Oversold'),
('ARENA_SCANNER_BADGE_NEG_FUNDING','en','Neg. Funding'),
('ARENA_SCANNER_BADGE_BEATS_BTC','en','Beats BTC'),
('ARENA_SCANNER_BADGE_LAGS_BTC','en','Lags BTC'),
('ARENA_SCANNER_USDT_PERP','en','USDT Perp'),
('ARENA_SCANNER_NEUTRAL_DOT','en','· Neutral'),
('ARENA_SCANNER_STATUS_SQUEEZE','en','Squeeze'),
('ARENA_SCANNER_STATUS_FLUSH','en','Flush'),
('ARENA_SCANNER_STATUS_NEUTRAL','en','Neutral'),
('ARENA_SCANNER_FOOTER_EXPLAINER','en','Funding rate + L/S ratio · ↑ Squeeze = shorts overcrowded · ↓ Flush = longs overcrowded')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
