-- NEWS_* rows (app/news/page.tsx). Run once against BOTH lhq_labels (prod)
-- and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('NEWS_TAB_FORYOU','en','For You'),
('NEWS_TAB_BREAKING','en','Breaking'),
('NEWS_TAB_ALL','en','All'),
('NEWS_TAB_GEO','en','War & Geo'),
('NEWS_TAB_CRYPTO','en','Crypto'),
('NEWS_TAB_EVENTS','en','Calendar'),
('NEWS_TIME_JUST_NOW','en','just now'),
('NEWS_TIME_MINUTES_AGO','en','{n}m ago'),
('NEWS_TIME_HOURS_AGO','en','{n}h ago'),
('NEWS_TIME_DAYS_AGO','en','{n}d ago'),
('NEWS_ASK_GROK_PROMPT','en','Breaking news: "{headline}"

How does this affect BTC and crypto markets right now? What''s the likely short-term price impact, direction bias, and should I adjust my position?'),
('NEWS_TYPE_BADGE_BREAKING','en','Breaking'),
('NEWS_TYPE_BADGE_MACRO','en','Macro'),
('NEWS_TYPE_BADGE_CRYPTO','en','Crypto'),
('NEWS_SENTIMENT_BULLISH','en','{prefix}Bullish ↗'),
('NEWS_SENTIMENT_BEARISH','en','{prefix}Bearish ↘'),
('NEWS_COIN_BUZZ_LABEL','en','Coin buzz'),
('NEWS_ASK_AI_BUTTON','en','Ask LiquidityAI'),
('NEWS_READ_ARTICLE_LINK','en','Read article ↗'),
('NEWS_PAGE_TITLE','en','News'),
('NEWS_SOURCE_LIST','en','Reuters · AP · BBC · CoinDesk · CoinTelegraph · Decrypt · The Block · Finnhub'),
('NEWS_ALERT_COUNT','en','{count} alert{s}'),
('NEWS_BREAKING_EMPTY_TITLE','en','No breaking news'),
('NEWS_BREAKING_EMPTY_BODY','en','War · blockades · sanctions · crashes will appear here'),
('NEWS_FORYOU_FALLBACK_BANNER','en','No breaking catalysts right now - showing latest crypto news'),
('NEWS_LOADING_FEEDS','en','Loading feeds…'),
('NEWS_FORYOU_EMPTY_TITLE','en','Scanning for catalysts…'),
('NEWS_FORYOU_EMPTY_BODY','en','High-impact news + whale trades will appear here'),
('NEWS_WHALE_SIDE_BUY','en','BUY'),
('NEWS_WHALE_SIDE_SELL','en','SELL'),
('NEWS_WHALE_BADGE','en','{arrow} {symbol} Whale {side}'),
('NEWS_WHALE_BOUGHT','en','bought'),
('NEWS_WHALE_SOLD','en','sold'),
('NEWS_WHALE_HEADLINE','en','{usd} {action} at ${price}'),
('NEWS_WHALE_NOTE_BUY','en','Institutional accumulation - watch follow-through'),
('NEWS_WHALE_NOTE_SELL','en','Distribution signal - sell pressure incoming'),
('NEWS_WHALE_ASK_PROMPT','en','A whale just {action} {usd} of {symbol} at ${price}. What does this mean for the next 1-4 hours?'),
('NEWS_GEO_EMPTY','en','No war/conflict alerts yet'),
('NEWS_CRYPTO_EMPTY','en','No crypto news yet'),
('NEWS_ALL_LOADING_SR','en','Fetching news - feeds loading…'),
('NEWS_EVENTS_EMPTY','en','No upcoming high-impact US events found'),
('NEWS_EVENTS_TODAY_PREFIX','en','Today - {date}'),
('NEWS_EVENTS_LIVE_BADGE','en','LIVE'),
('NEWS_EVENTS_COL_TIME','en','TIME (PHT)'),
('NEWS_EVENTS_COL_EVENT','en','EVENT'),
('NEWS_EVENTS_COL_PREV','en','PREV'),
('NEWS_EVENTS_COL_EST','en','EST'),
('NEWS_EVENTS_COL_ACTUAL','en','ACTUAL'),
('NEWS_EVENTS_COL_IMPACT','en','IMPACT'),
('NEWS_EVENTS_NOW_BADGE','en','NOW'),
('NEWS_EVENTS_IMPACT_HIGH','en','HIGH'),
('NEWS_EVENTS_FOOTER_NOTE','en','High-impact US events · Finnhub when available · Fed calendar + computed schedule as fallback · Times in PHT')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
