-- MARKETS_* rows (app/markets/page.tsx). Run once against BOTH lhq_labels
-- (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('MARKETS_SIGNAL_LONGS_OVERCROWDED','en','Longs overcrowded'),
('MARKETS_SIGNAL_SHORTS_SQUEEZED','en','Shorts squeezed'),
('MARKETS_SIGNAL_SMART_BUYERS','en','Smart buyers active'),
('MARKETS_SIGNAL_SMART_SELLERS','en','Smart sellers active'),
('MARKETS_SIGNAL_NEW_BUYERS','en','New buyers opening'),
('MARKETS_SIGNAL_NEW_SELLERS','en','New sellers opening'),
('MARKETS_SIGNAL_SHORT_COVERING','en','Short covering'),
('MARKETS_SIGNAL_LONGS_EXITING','en','Longs exiting'),
('MARKETS_SIGNAL_NONE','en','No signal'),
('MARKETS_BACK_BUTTON','en','← Back'),
('MARKETS_PAGE_TITLE','en','Markets'),
('MARKETS_COINS_LIVE_SUFFIX','en','{count} coins live'),
('MARKETS_BULLISH_COUNT','en','▲ {count} bullish'),
('MARKETS_BEARISH_COUNT','en','▼ {count} bearish'),
('MARKETS_NEUTRAL_COUNT','en','- {count} neutral'),
('MARKETS_SEARCH_PLACEHOLDER','en','Search coins…'),
('MARKETS_SORT_VOLUME','en','Volume'),
('MARKETS_SORT_CHANGE','en','Change'),
('MARKETS_SORT_GRADE','en','Grade'),
('MARKETS_SORT_SIGNAL','en','Signal'),
('MARKETS_SORT_NAME','en','Name'),
('MARKETS_GRADE_TIP','en','An A-F health grade blending the squeeze setup score with RSI extremes, open-interest trend, and CVD divergence. A means the strongest confluence of positioning signals; F means little or conflicting signal.'),
('MARKETS_GRADE_COL_LABEL','en','Grade'),
('MARKETS_COIN_COL_LABEL','en','Coin'),
('MARKETS_PRICE_COL_LABEL','en','Price'),
('MARKETS_24H_COL_LABEL','en','24h'),
('MARKETS_PRESSURE_TIP','en','The share of recent volume that hit the ask (aggressive buying) versus the bid. Above 55% buy means buyers are lifting offers; below 45% means sellers are hitting bids.'),
('MARKETS_PRESSURE_COL_LABEL','en','Pressure'),
('MARKETS_SIGNAL_TIP','en','The single most notable derivatives signal for this coin right now - crowded funding, a CVD divergence, or an open-interest shift - color-coded green for bullish or red for bearish.'),
('MARKETS_SIGNAL_COL_LABEL','en','Signal'),
('MARKETS_LOADING_SR','en','Loading market data…'),
('MARKETS_BUY_PCT_SUFFIX','en','{pct}% buy'),
('MARKETS_NO_MATCH','en','No coins match "{query}"'),
('MARKETS_RANGE_OF','en','{start}–{end} of {total}'),
('MARKETS_PREV_BUTTON','en','← Prev'),
('MARKETS_NEXT_BUTTON','en','Next →')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
