-- Wave 9: MarketStructure, MarketRead, MarketConditionsWidget, LiqHeatmap,
-- OnChainScore, GrokSignalChart, GlobalMacroContext, VolatilityRegime.
-- Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('MARKET_STRUCTURE_LOADING_SR','en','Loading…'),
('MARKET_STRUCTURE_TITLE','en','Market Structure · 4H'),
('MARKET_STRUCTURE_FAILED','en','Failed'),
('MARKET_STRUCTURE_FLIP_TAG','en','FLIP'),
('MARKET_STRUCTURE_SWING_HIGH_LABEL','en','Swing High'),
('MARKET_STRUCTURE_SWING_LOW_LABEL','en','Swing Low'),
('MARKET_STRUCTURE_FOOTER','en','BOS = trend continuation · CHoCH = potential reversal · 4H swing lookback 3'),
('MARKET_READ_TIP','en','A plain read on whether now is a good time to trade this coin. Blends session timing, day of week, Fear & Greed, funding, order-wall proximity and a 6-signal smart-money composite into one 0-100 score.'),
('MARKET_READ_TITLE','en','Market Read'),
('MARKET_READ_EYEBROW_Q','en',' · is now a good time to trade?'),
('MARKET_READ_CONDITIONS_LABEL','en','Conditions'),
('MARKET_READ_FLAG_BULLISH','en','Contrarian bullish'),
('MARKET_READ_FLAG_CAUTION','en','Caution'),
('MARKET_READ_OVERRIDE_DEFAULT','en','override funding'),
('MARKET_READ_OVERRIDE_ACTIVE','en','funding overridden: {value}'),
('MARKET_READ_FUND_LONG_LC','en','long-heavy'),
('MARKET_READ_FUND_SHORT_LC','en','short-heavy'),
('MARKET_READ_FUND_NEUTRAL_LC','en','neutral'),
('MARKET_READ_FUND_LONG','en','Long-heavy'),
('MARKET_READ_FUND_SHORT','en','Short-heavy'),
('MARKET_READ_FUND_NEUTRAL','en','Neutral'),
('MARKET_CONDITIONS_WIDGET_TITLE','en','Market conditions'),
('MARKET_CONDITIONS_WIDGET_SUBTITLE','en','Is now a good time?'),
('MARKET_CONDITIONS_WIDGET_SOURCE_LINK','en','alternative.me'),
('MARKET_CONDITIONS_WIDGET_FNG_LABEL','en','Fear & greed'),
('MARKET_CONDITIONS_WIDGET_TREND_LABEL','en','30-day trend'),
('MARKET_CONDITIONS_WIDGET_RSI_LABEL','en','BTC RSI (14)'),
('MARKET_CONDITIONS_WIDGET_RSI_OVERBOUGHT','en','Overbought'),
('MARKET_CONDITIONS_WIDGET_RSI_OVERSOLD','en','Oversold'),
('MARKET_CONDITIONS_WIDGET_RSI_NEUTRAL','en','Neutral'),
('MARKET_CONDITIONS_WIDGET_LONG_SHORT_LABEL','en','BTC long / short'),
('MARKET_CONDITIONS_WIDGET_LONG_PCT','en','Long {pct}%'),
('MARKET_CONDITIONS_WIDGET_SHORT_PCT','en','Short {pct}%'),
('MARKET_CONDITIONS_WIDGET_LOADING_SR','en','Loading…'),
('MARKET_CONDITIONS_WIDGET_DATA_SOURCE','en','Data by Binance'),
('LIQ_HEATMAP_TITLE','en','BTC Liquidation Clusters'),
('LIQ_HEATMAP_SUBTITLE','en','BTC only · Coinglass'),
('LIQ_HEATMAP_SHORT_SECTION_LABEL','en','Short liquidations above - bulls target here'),
('LIQ_HEATMAP_CURRENT_LABEL','en','Current'),
('LIQ_HEATMAP_LONG_SECTION_LABEL','en','Long liquidations below - bears target here'),
('ON_CHAIN_SCORE_TITLE','en','On-Chain Composite Score'),
('ON_CHAIN_SCORE_SUBTITLE','en','MVRV · SOPR · NVT · Exchange Flows · Whale Activity'),
('ON_CHAIN_SCORE_UPDATED','en','Updated {time}'),
('ON_CHAIN_SCORE_ANALYZE','en','Analyze'),
('ON_CHAIN_SCORE_REANALYZE','en','Re-analyze'),
('ON_CHAIN_SCORE_ANALYZING','en','Analyzing…'),
('ON_CHAIN_SCORE_EMPTY_STATE','en','Click Analyze to fetch live on-chain metrics via Grok web search.'),
('ON_CHAIN_SCORE_LOADING_SR','en','Searching web for MVRV, SOPR, NVT, exchange flows…'),
('ON_CHAIN_SCORE_VALUATION','en','Valuation'),
('ON_CHAIN_SCORE_ACTIVITY','en','Activity'),
('ON_CHAIN_SCORE_CAPITAL_FLOW','en','Capital Flow'),
('ON_CHAIN_SCORE_WHALE','en','Whale'),
('ON_CHAIN_SCORE_MVRV','en','MVRV'),
('ON_CHAIN_SCORE_SOPR','en','SOPR'),
('ON_CHAIN_SCORE_NVT','en','NVT'),
('ON_CHAIN_SCORE_METRIC_VIA','en','via {source}'),
('ON_CHAIN_SCORE_EXCHANGE_FLOW_LABEL','en','Exchange Flow'),
('ON_CHAIN_SCORE_ACTIVE_ADDRESSES_LABEL','en','Active Addresses'),
('ON_CHAIN_SCORE_REQUEST_FAILED','en','Request failed'),
('ON_CHAIN_SCORE_FETCH_ERROR','en','Failed to fetch on-chain data'),
('GROK_SIGNAL_CHART_EXIT_FULLSCREEN','en','Exit fullscreen'),
('GROK_SIGNAL_CHART_FULLSCREEN','en','Fullscreen'),
('GLOBAL_MACRO_CONTEXT_TOOLTIP','en','Live DXY, VIX, Gold, Oil, and 10Y Treasury data from Yahoo Finance. Grok classifies the composite macro backdrop and gives crypto positioning implications. Updates every 2 hours.'),
('GLOBAL_MACRO_CONTEXT_TITLE','en','Global Macro Context'),
('GLOBAL_MACRO_CONTEXT_FETCHING_SR','en','Fetching macro data…'),
('GLOBAL_MACRO_CONTEXT_SIGNIN_PROMPT','en','Sign in to view macro context.'),
('GLOBAL_MACRO_CONTEXT_FETCH_FAILED','en','Failed'),
('GLOBAL_MACRO_CONTEXT_RETRY','en','Retry'),
('GLOBAL_MACRO_CONTEXT_SIGNAL_RISK_ON','en','Risk On'),
('GLOBAL_MACRO_CONTEXT_SIGNAL_RISK_OFF','en','Risk Off'),
('GLOBAL_MACRO_CONTEXT_SIGNAL_NEUTRAL','en','Neutral'),
('GLOBAL_MACRO_CONTEXT_ROW_DXY','en','DXY'),
('GLOBAL_MACRO_CONTEXT_ROW_VIX','en','VIX'),
('GLOBAL_MACRO_CONTEXT_ROW_GOLD','en','Gold'),
('GLOBAL_MACRO_CONTEXT_ROW_OIL','en','Oil (WTI)'),
('GLOBAL_MACRO_CONTEXT_ROW_10Y_YIELD','en','10Y Yield'),
('GLOBAL_MACRO_CONTEXT_ROW_GOLD_OIL','en','Gold/Oil'),
('GLOBAL_MACRO_CONTEXT_IMPLICATIONS_TITLE','en','Crypto Implications'),
('GLOBAL_MACRO_CONTEXT_WATCH_LABEL','en','Watch: '),
('GLOBAL_MACRO_CONTEXT_REFRESH_BUTTON','en','Refresh (2h cache)'),
('VOLATILITY_REGIME_TOOLTIP','en','Historical Volatility (HV) measures how much price has moved over the past 30 days, annualized. The percentile shows where today''s HV sits vs. the past ~120 days. Low vol historically precedes expansion - volatility mean-reverts. High vol means the market is already moving hard: size down or hedge.'),
('VOLATILITY_REGIME_TITLE','en','Volatility Regime'),
('VOLATILITY_REGIME_ZONE_LOW','en','< p20'),
('VOLATILITY_REGIME_ZONE_HIGH','en','> p80'),
('VOLATILITY_REGIME_ZONE_NEUTRAL','en','p20–p80'),
('VOLATILITY_REGIME_LABEL_LOW','en','Low Vol'),
('VOLATILITY_REGIME_LABEL_NEUTRAL','en','Normal'),
('VOLATILITY_REGIME_LABEL_HIGH','en','High Vol'),
('VOLATILITY_REGIME_HINT_LOW','en','Build positions - volatility likely to expand'),
('VOLATILITY_REGIME_HINT_NEUTRAL','en','Standard position sizing'),
('VOLATILITY_REGIME_HINT_HIGH','en','Reduce exposure or hedge'),
('VOLATILITY_REGIME_UNAVAILABLE','en','Unavailable'),
('VOLATILITY_REGIME_BTC','en','BTC'),
('VOLATILITY_REGIME_ETH','en','ETH')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
