-- TERMS_* + NOT_FOUND_* rows. Run once against BOTH lhq_labels (prod) and
-- lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('TERMS_EYEBROW','en','Legal'),
('TERMS_PAGE_TITLE','en','Terms of Use.'),
('TERMS_LAST_UPDATED','en','Last updated: July 2026'),
('TERMS_CALLOUT_BODY','en','LiquidityHQ provides data analytics and software tools for informational purposes only. This is not financial, investment, or trading advice. Past performance does not guarantee future results. Trade at your own risk.'),
('TERMS_SECTION_ACCEPTANCE_TITLE','en','Acceptance of Terms'),
('TERMS_SECTION_ACCEPTANCE_BODY','en','By accessing or using LiquidityHQ ("the Platform"), you agree to be bound by these Terms of Use. If you do not agree to these terms, do not use the Platform. We reserve the right to update these terms at any time; continued use of the Platform after changes constitutes acceptance.'),
('TERMS_SECTION_ELIGIBILITY_TITLE','en','Eligibility'),
('TERMS_SECTION_ELIGIBILITY_BODY','en','You must be at least 18 years old to use LiquidityHQ. By using the Platform, you represent that you meet this requirement and that you have the legal capacity to enter into a binding agreement.'),
('TERMS_SECTION_NATURE_OF_SERVICE_TITLE','en','Nature of the Service'),
('TERMS_SECTION_NATURE_OF_SERVICE_BODY','en','LiquidityHQ is an educational and informational tool. It provides market data, charting tools, AI-generated analysis, and alerts for cryptocurrency markets. Nothing on this Platform constitutes financial, investment, legal, or tax advice. All content is for informational purposes only.'),
('TERMS_SECTION_USER_ACCOUNTS_TITLE','en','User Accounts'),
('TERMS_SECTION_USER_ACCOUNTS_BODY','en','You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized access. We reserve the right to suspend or terminate accounts that violate these terms.'),
('TERMS_SECTION_PROHIBITED_USES_TITLE','en','Prohibited Uses'),
('TERMS_SECTION_PROHIBITED_USES_BODY','en','You may not use LiquidityHQ to engage in any unlawful activity, scrape or systematically extract data without authorization, attempt to reverse-engineer or bypass any security measure, resell or redistribute the Platform''s content or signals, or interfere with the Platform''s infrastructure or other users'' access.'),
('TERMS_SECTION_IP_TITLE','en','Intellectual Property'),
('TERMS_SECTION_IP_BODY','en','All content, features, and functionality on LiquidityHQ - including but not limited to text, graphics, signals, scoring algorithms, and software - are the exclusive property of LiquidityHQ and its licensors. You may not reproduce, distribute, or create derivative works without express written permission.'),
('TERMS_SECTION_THIRD_PARTY_DATA_TITLE','en','Third-Party Data and Services'),
('TERMS_SECTION_THIRD_PARTY_DATA_BODY','en','LiquidityHQ integrates data from third-party providers including Binance, Bybit, Finnhub, Alternative.me, and xAI Grok. We do not guarantee the accuracy, completeness, or timeliness of third-party data. Use of such data is subject to the respective third parties'' terms of service.'),
('TERMS_SECTION_LIABILITY_TITLE','en','Limitation of Liability'),
('TERMS_SECTION_LIABILITY_BODY','en','To the maximum extent permitted by law, LiquidityHQ and its operator shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the Platform, including but not limited to trading losses, lost profits, or loss of data.'),
('TERMS_SECTION_INDEMNIFICATION_TITLE','en','Indemnification'),
('TERMS_SECTION_INDEMNIFICATION_BODY','en','You agree to indemnify and hold harmless LiquidityHQ, its operator, and affiliates from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Platform, your violation of these terms, or your violation of any rights of a third party.'),
('TERMS_SECTION_TERMINATION_TITLE','en','Termination'),
('TERMS_SECTION_TERMINATION_BODY','en','We reserve the right to suspend or terminate your access to LiquidityHQ at any time, with or without notice, for any reason including violation of these terms. Upon termination, your right to use the Platform ceases immediately.'),
('TERMS_SECTION_GOVERNING_LAW_TITLE','en','Governing Law'),
('TERMS_SECTION_GOVERNING_LAW_BODY','en','These Terms of Use shall be governed by and construed in accordance with applicable law. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the competent courts in the applicable jurisdiction.'),
('TERMS_SECTION_CONTACT_TITLE','en','Contact'),
('TERMS_SECTION_CONTACT_BODY','en','If you have questions about these Terms of Use, please contact us at the email address provided on the About page.'),
('TERMS_FOOTER_ACKNOWLEDGEMENT','en','By using LiquidityHQ, you acknowledge that you have read, understood, and agree to these Terms of Use.'),
('TERMS_FOOTER_COPYRIGHT','en','© {year} LiquidityHQ. All rights reserved.'),
('NOT_FOUND_TITLE','en','404 - Liquidity not found'),
('NOT_FOUND_BODY','en','This page got stop-hunted. The level you''re looking for doesn''t exist - or it was swept and never came back.'),
('NOT_FOUND_HOME_LINK','en','← Dashboard'),
('NOT_FOUND_LIQUIDATION_MAP_LINK','en','Liquidation Map')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
