-- DISCLAIMER_* rows. Run once against BOTH lhq_labels (prod) and lhq_dev_labels (dev).

insert into lhq_labels (key, locale, value) values
('DISCLAIMER_EYEBROW','en','Important Information'),
('DISCLAIMER_PAGE_TITLE','en','Disclaimer.'),
('DISCLAIMER_SECTION_EDUCATIONAL_TITLE','en','Educational Content Only'),
('DISCLAIMER_SECTION_EDUCATIONAL_BODY','en','LiquidityHQ provides market data, charting tools, and AI-generated analysis for educational and informational purposes only. Nothing on this platform - including signals, scores, alerts, or LiquidityAI commentary - constitutes a recommendation to buy, sell, or hold any asset.'),
('DISCLAIMER_SECTION_TRADING_RISKS_TITLE','en','Trading Risks'),
('DISCLAIMER_SECTION_TRADING_RISKS_BODY','en','Trading cryptocurrency and derivatives involves substantial risk and is not suitable for everyone. Prices are volatile, leverage magnifies losses as well as gains, and most active traders lose money over time. Only trade with money you can afford to lose completely.'),
('DISCLAIMER_SECTION_NO_GUARANTEES_TITLE','en','No Guarantees'),
('DISCLAIMER_SECTION_NO_GUARANTEES_BODY','en','Squeeze scores, distribution scores, EMA ribbon setups, backtest results, and every other metric on this platform describe historical or current conditions - they do not predict future price movement. Past performance does not guarantee future results.'),
('DISCLAIMER_SECTION_NOT_FINANCIAL_ADVICE_TITLE','en','Not Financial Advice'),
('DISCLAIMER_SECTION_NOT_FINANCIAL_ADVICE_BODY','en','We are not a registered investment advisor, broker, or financial planner. Nothing here should be treated as personalized financial, investment, tax, or legal advice. Consult a licensed professional before making any investment decision. You are solely responsible for your own trading decisions and outcomes.'),
('DISCLAIMER_SECTION_NO_TRADE_EXECUTION_TITLE','en','No Trade Execution'),
('DISCLAIMER_SECTION_NO_TRADE_EXECUTION_BODY','en','LiquidityHQ does not execute trades, place orders, or manage funds on your behalf, and never has access to your exchange API keys or account credentials. The platform is a data and analytics tool only - all trading decisions and actions are made by you, on your own exchange account.'),
('DISCLAIMER_SECTION_AI_ANALYSIS_TITLE','en','AI-Generated Analysis'),
('DISCLAIMER_SECTION_AI_ANALYSIS_BODY','en','LiquidityAI features (Quick Research, Deep Research, and automated alert commentary) are generated by a third-party large language model (xAI Grok). AI output can be incomplete, outdated, or simply wrong and should never be the sole basis for a trading decision. Always verify against the raw data shown alongside it.'),
('DISCLAIMER_SECTION_DATA_PROVIDERS_TITLE','en','Technology and Data Providers'),
('DISCLAIMER_SECTION_DATA_PROVIDERS_BODY','en','Price, funding, open interest, and news data are sourced from third parties including Binance, Bybit, Finnhub, and Alternative.me. These services operate independently of LiquidityHQ. We do not guarantee their accuracy, completeness, or availability. Feeds can lag, drop, or briefly disagree with the exchange you actually trade on.'),
('DISCLAIMER_SECTION_BACKTESTS_TITLE','en','Statistics and Backtests'),
('DISCLAIMER_SECTION_BACKTESTS_BODY','en','Any statistics, backtested results, or historical performance metrics shown on this platform represent past conditions only. These figures may reflect cherry-picked periods, survivorship bias, or idealized assumptions. They do not represent live trading results and should not be relied upon to predict future performance.'),
('DISCLAIMER_SECTION_NO_LIABILITY_TITLE','en','No Liability'),
('DISCLAIMER_SECTION_NO_LIABILITY_BODY','en','LiquidityHQ and its operator disclaim all liability for losses, damages, or missed opportunities arising from use of this platform, its data, or its AI-generated content, to the maximum extent permitted by law.'),
('DISCLAIMER_SECTION_PLATFORM_IDENTITY_TITLE','en','Platform Identity'),
('DISCLAIMER_SECTION_PLATFORM_IDENTITY_BODY','en','LiquidityHQ is an independent tool and is not affiliated with, endorsed by, or sponsored by Binance, Bybit, xAI, Finnhub, or any exchange or data provider referenced on this platform. All trademarks belong to their respective owners and are used solely to identify the data source.'),
('DISCLAIMER_FOOTER_ACKNOWLEDGEMENT','en','By using LiquidityHQ, you acknowledge that you understand and agree to this disclaimer. Market data and signals are for informational use only - not investment advice.'),
('DISCLAIMER_FOOTER_COPYRIGHT','en','© {year} LiquidityHQ. All rights reserved.'),
('DISCLAIMER_FOOTER_ABOUT_LINK','en','About')
on conflict (key, locale) do update set value = excluded.value, updated_at = now();
