import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Disclaimer' };

const SECTIONS: { title: string; body: React.ReactNode }[] = [
  {
    title: 'Educational content only',
    body: 'LiquidityHQ provides market data, charting tools, and AI-generated analysis for educational and informational purposes only. Nothing on this platform — including signals, scores, alerts, or LiquidityAI commentary — constitutes a recommendation to buy, sell, or hold any asset.',
  },
  {
    title: 'Not financial advice',
    body: 'We are not a registered investment advisor, broker, or financial planner. Nothing here should be treated as personalized financial, investment, tax, or legal advice. Consult a licensed professional before making any investment decision.',
  },
  {
    title: 'Trading risk',
    body: 'Trading cryptocurrency and derivatives involves substantial risk and is not suitable for everyone. Prices are volatile, leverage magnifies losses as well as gains, and most active traders lose money over time. Only trade with money you can afford to lose completely.',
  },
  {
    title: 'No guarantees',
    body: 'Squeeze scores, distribution scores, EMA ribbon setups, backtest results, and every other metric on this platform describe historical or current conditions — they do not predict future price movement. Past performance, including any backtested strategy shown here, does not guarantee future results.',
  },
  {
    title: 'AI-generated analysis',
    body: 'LiquidityAI features (Quick Research, Deep Research, chat, and automated alert commentary) are generated by a third-party large language model (xAI’s Grok). AI output can be incomplete, outdated, or simply wrong, and should never be the sole basis for a trading decision. Always verify against the raw data shown alongside it.',
  },
  {
    title: 'Market data & third-party providers',
    body: 'Price, funding, open interest, order book, and news data are sourced from third parties including Binance, Bybit, Finnhub, and Alternative.me. These services operate independently of LiquidityHQ, and we do not control or guarantee the accuracy, completeness, or availability of their data. Feeds can lag, drop, or briefly disagree with the exchange you actually trade on.',
  },
  {
    title: 'No liability',
    body: 'LiquidityHQ and its operator disclaim all liability for losses, damages, or missed opportunities arising from use of this platform, its data, or its AI-generated content, to the maximum extent permitted by law.',
  },
  {
    title: 'Platform identity',
    body: 'LiquidityHQ is an independent tool and is not affiliated with, endorsed by, or sponsored by Binance, Bybit, xAI, Finnhub, or any exchange or data provider referenced on this platform. All trademarks belong to their respective owners and are used solely to identify the data source.',
  },
];

export default function Disclaimer() {
  return (
    <div>
      <div style={{ padding: '1rem 0 0.5rem' }}>
        <div style={{ fontSize: 20, fontWeight: 700, color: 'var(--txt)', marginBottom: 2 }}>Disclaimer</div>
        <div style={{ fontSize: 12, color: 'var(--txt3)', marginBottom: 14 }}>Important information — read before using LiquidityHQ</div>
      </div>

      <div className="card">
        <div className="pbox" style={{ marginBottom: 0 }}>
          <div className="pt">Not financial advice</div>
          <div className="pb">
            Everything on this platform — prices, scores, signals, AI commentary — is for education and research.
            You are solely responsible for your own trading decisions and outcomes.
          </div>
        </div>
      </div>

      {SECTIONS.map(s => (
        <div className="card" key={s.title}>
          <div className="lbl">{s.title}</div>
          <div style={{ fontSize: 13, color: 'var(--txt2)', lineHeight: 1.7 }}>{s.body}</div>
        </div>
      ))}
    </div>
  );
}
